### ISSUE TITLE
In non-grid forms, Query icon is overlapped by long label text for select items

### ISSUE THREAD

**Issue by pbowen-oc** [kobotoolbox/enketo-express#1001]
For non-grid forms, if a select item has long label text, the Query icon is misplaced and the text overlaps it. The Query icon should be after the text as with the other item types.

![image](https://user-images.githubusercontent.com/25179620/39321422-fef3d604-4954-11e8-858e-c829bc9f8569.png)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=repeating-group-not-displayed.xml

**Comment by MartijnR** [comment]
* [ ] check dn icon (comment icon fixed in ec)
