### ISSUE TITLE
IE11 does not have download button for file widgets

### ISSUE THREAD

**Issue by pbowen-oc** [kobotoolbox/enketo-express#1002]
In IE11, the file upload/annotate/draw/signature widgets do not have a download button.

These are working as expected in Chrome.

**Comment by MartijnR** [comment]
Yes, this was a known limitation. I could not do it for IE11: https://github.com/enketo/enketo-core/issues/249#issuecomment-363866116. But I can look at it again, and see.

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks. Since you've already looked and could not do it, there's no need to look again right now.

**Comment by MartijnR** [comment]
* [ ] merge in enketo-express-oc
