### ISSUE TITLE
Select_multiple with choice_filter is empty when loading a saved draft (in a specific context)

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/enketo-express#1003]
A user has run into an issue when there are multiple select_multiple questions, one of which has a `choice_filter`. Please see below steps to reproduce: 

- Q1 is a select_ multiple question with a choice filter.
- Q2 is a select_ multiple question with a default choice.
- Unselect this default choice from Q2, and save the draft with nothing selected in Q2.

Next time you reload the draft, Q1 has no choices available.
(If you select a value in Q2, and save the draft, the Q1 comes back normally when reloaded).

See https://ee.kobotoolbox.org/x/#ihxXHZFh
or https://www.dropbox.com/s/1i0thip8rq1avyr/aM96T4TCFTonjSCv8RaHTg.xls?dl=0 for the XLSForm.

**Comment by MartijnR** [comment]
Thanks! Will check it out.

**Comment by MartijnR** [comment]
default value for B causes this somehow

**Comment by MartijnR** [comment]
* [ ] create test

**Comment by MartijnR** [comment]
Fixed in 1.65.1. Thanks @pmusaraj!

**Comment by pmusaraj** [comment]
Thank you!
