### ISSUE TITLE
OC Only: incorrect width of dn in Grid form without w-values in Print view

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1005]
```text
group - fieldlist
   group
       q1
       q2
       dn-q1
       dn-q2
```

**Comment by MartijnR** [comment]
dn-q1 and dn-q2 should have 100% width

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1NRH2DCPLvyWYuvQeYmILyL30-rkORiNiufX8F3WLKz8/edit?usp=sharing

**Comment by MartijnR** [comment]
I have not been able to reproduce this with the emailed form (and manually adding discrepancy note questions).

@pbowen-oc, at this point it would be best if we can get access to the XForm. Could you perhaps upload the XLSForm to your OC account to get the XForm? We just need to get the inserted DN questions.

**Comment by pbowen-oc** [comment]
@MartijnR - I just sent it via email.

**Comment by MartijnR** [comment]
`http://localhost:8005/::Yh0mewV7?print=true&format=A4&margin=0.5in&landscape=false&scale=1`

**Comment by MartijnR** [comment]
* [ ] fix relevancy of dn questions (should be hidden if irrelevant)
