### ISSUE TITLE
OC Only: When query history is printed, show full timestamps, not relative time

### ISSUE THREAD

**Issue by pbowen-oc** [kobotoolbox/enketo-express#1013]
When the user prints a form and query history is included, show the full timestamp of each action, not the relative time.

**Comment by MartijnR** [comment]
@pbowen-oc like this, or take out e.g. the timezone part?

<img width="209" alt="screen shot 2018-05-11 at 4 47 00 pm" src="https://user-images.githubusercontent.com/627350/39949892-0c80832a-553b-11e8-8f6f-90094c6b3646.png">

**Comment by pbowen-oc** [comment]
Can we have the format be:
DD-Mon-YYYY HH:MM UTC-XX:XX

For example - 13-Jun-2018 13:58 UTC-04:00
