### ISSUE TITLE
Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by msschroeder** [kobotoolbox/enketo-express#1014]
Unable to submit a record due to 'Cannot read property 'nodeName' of undefined' error. 

To recreate the issue:
1. Upload an example form (attached)
2. Load the form in Enketo
3. Open the Group group. 
4. Remove the first repeat group.
5. Submit
6. Receive the error: 'Cannot read property 'nodeName' of undefined'

However, when you remove the relevant condition from the question in the repeat group (row 8), you can submit with no issue.

[Test Group Repeat Form Final2.xlsx](https://github.com/kobotoolbox/enketo-express/files/1999834/Test.Group.Repeat.Form.Final2.xlsx)

**Comment by MartijnR** [comment]
Thanks. Will look into this with priority.

**Comment by MartijnR** [comment]
Caused by caching in Form.prototype.getRelatedNodes. Challenge is to fix without causing serious performance degradation.
