### ISSUE TITLE
OC Only: add ecid, PID, parentWindowOrigin parameter to all API calls

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1023]
Do all views (sometimes) use the ecid query parameter?

Should ecid be a required parameter in all API calls?

**Comment by MartijnR** [comment]
* [ ] let Yogi know when done

**Comment by MartijnR** [comment]
less than 12 hours

**Comment by MartijnR** [comment]
* [ ] loadWarning (if not already done)
* [ ] goToErrorUrl (if not already done)

**Comment by MartijnR** [comment]
Hi @yogi-oc,

The latest Enketo Express master now has the updated API as discussed a few weeks ago. There should be no more need to manipulate webform URLs on the OC side. Yay. The only exception is the authentication token (let me know if I should add that to API and anything I may have forgotten).

See updated API Documentation: https://github.com/OpenClinica/enketo-express-oc/blob/master/doc/oc-api.md

Some of the new API parameters are required (ecid, PID), so this means OC integration is now broken until the API calls are changed on the OC side.

**Comment by MartijnR** [comment]
all is good

**Comment by pbowen-oc** [comment]
This is addressed further in #1085
