### ISSUE TITLE
loading performance idea: request form before main bundle is loaded

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1028]
Atm, the large JS bundle is loaded first, after which the form is loaded (by the js is bundle). Would be **~~very~~ worthwhile** to split that up.

**Comment by MartijnR** [comment]
I think this could be done by:

* [ ] changing `connection.getFormParts()` to a GET request. We may be able to just use a fixed URL and determine the parameters from the origin of the request (so on the server).
* [ ] using `<link rel="preload">` for the URL in that request
* [ ] test all views
* [ ] to the same with `connection.getInstance()`

**Comment by MartijnR** [comment]
It will approximately save the time it takes to download the js bundle file (not hugely significant)

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#59
