### ISSUE TITLE
Do not apply widget CSS if widget appearance is used on incorrect question type

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1032]
![image 1](https://user-images.githubusercontent.com/627350/40385159-f33b4860-5dc2-11e8-8c38-0414090933b2.png)

**Comment by MartijnR** [comment]
for master

**Comment by MartijnR** [comment]
Might be related to form or oc fork.

<img width="1063" alt="screen shot 2018-05-23 at 1 05 16 pm" src="https://user-images.githubusercontent.com/627350/40445667-07f6f64c-5e8a-11e8-8cbd-471d9ffc449f.png">

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1Wqo6UHKklTXIpT-yEItoPTVBFFFftho2GoB1e-w5R08/edit#gid=0

**Comment by pbowen-oc** [comment]
I looked at the form definition and saw that it had appearance "analog-scale horizontal". I know this is not appropriate for a select_one item, so I'm not sure if that caused this issue. Perhaps it was due to the number of rows of choices that were listed?

**Comment by MartijnR** [comment]
Cannot reproduce.

**Comment by MartijnR** [comment]
Ah, it's probably analog-scale that messes it up (and not appropriate to use for select one). Will check.

**Comment by MartijnR** [comment]
Yep, that's it. Thanks!

Ideally the use of analog-scale won't affect non-numeric questions, but that isolation is not perfect for CSS styles. It would be good to fix this (across all widgets), but will be a fairly large effort - several days.

**Comment by MartijnR** [comment]
correction: it would be about 1 day of work 

* add `initialized` class to widgets
* only apply widget css to `initialized` widgets

**Comment by pbowen-oc** [comment]
@MartijnR - This sounds worthwhile. Please do this.

**Comment by MartijnR** [comment]
done, in master
