### ISSUE TITLE
longitude < -180 degrees valid?

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1033]
See flowdock issue of user that is working on international dateline

**Comment by MartijnR** [comment]
https://gis.stackexchange.com/questions/88298/what-is-the-max-latitude-and-longitude-values-possible

**Comment by MartijnR** [comment]
* [ ] do search for Taveuni to find a location to test with

**Comment by MartijnR** [comment]
Sorry, I forgot to do this one with the quickness it deserved @pmusaraj!

**Comment by pmusaraj** [comment]
This is great, thanks! Will test it tomorrow.
