### ISSUE TITLE
Can't select print settings in IE 11

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/enketo-express#1042]
Hey @MartijnR, sorry for raising an IE bug, but there's an issue with the "Select Print Settings" modal in IE 11.09600.17959: the radio buttons don't appear:
![ie11_koboprintbuttonfail](https://user-images.githubusercontent.com/2085013/41052518-f2c312d0-6986-11e8-86f9-d65bf26c18e6.JPG)

cc @darm0ck

**Comment by MartijnR** [comment]
Thanks. Will dust off the Windows VM!

**Comment by jnm** [comment]
Thanks! I forgot to mention the version of Enketo. I just reproduced it at https://enke.to/::grid, which is running 1.65.5.
![enke-dot-to-grid-ie11-print](https://user-images.githubusercontent.com/2085013/41053910-e49b737e-698a-11e8-977b-66949298c7ff.png)

**Comment by MartijnR** [comment]
Perfect. THanks
