### ISSUE TITLE
Submit button shows "Save Draft" when "Save as Draft" unchecked

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/enketo-express#1043]
To reproduce:

1. In Firefox 60 or Chrome 67, open https://enke.to/x/#widgets (Enketo version 1.65.5);
1. Scroll to the end of the survey;
1. Check "Save as Draft";
1. Click "Save Draft";
1. Click "Save & Close";
1. Once the save completes, scroll to the end of the survey again;
1. Notice that "Save as Draft" is unchecked, but the button still shows "Save Draft" instead of "Submit".

At this point, the button does behave as a submit button, and it is possible to change the label to "Submit" by toggling "Save as Draft" on and off.

![image](https://user-images.githubusercontent.com/2085013/41052816-dbb572da-6987-11e8-8088-3ef07325576f.png)
![image](https://user-images.githubusercontent.com/2085013/41052753-b18f0052-6987-11e8-8141-d1fcb79a480f.png)

cc @darm0ck

**Comment by MartijnR** [comment]
Nice one. Thanks!
