### ISSUE TITLE
 hosting my own Enketo as well, but quite new to all this. what to do after successful deployment of Enketo-express 

### ISSUE THREAD

**Issue by panditji** [kobotoolbox/enketo-express#1049]
Hi - I am interesting in hosting my own Enketo as well, but quite new to
all this.
Greetings of the day,
thanks in advance.
i'm non-technical guy what to do after successful deployment of Enketo-express on my server.
http://139.59.62.173:8005/  this is my ip address where you can see.
but i dont know further what to do next.

**Comment by MartijnR** [comment]
Congratulations!

By itself Enketo doesn't do anything, so now you need a form/data (aka an OpenRosa server). Here is some info about how they communicate: https://enketo.org/faq/#communicate

The easiest to install is ODK Aggregate, but if you would like a more full-featured Information Management system, you may want to try Ona or KoBo.

Good luck!
