### ISSUE TITLE
OC only: widget that requests ID number from OC

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1052]

**Comment by MartijnR** [comment]
1. Either get ID from OC, 

2. Let user enter and let button make validation request to OC. ONly if positive response, store value in model and trigger fieldsubmission.

**Comment by MartijnR** [comment]
Come customer want specific ID formats and OC would like to build in this flexibility into this form.

**Comment by MartijnR** [comment]
| type | name | appearance | calculate |
|----------|-------|-------------|----------|
| calculate | __id    |                       | concat('this.study', /path/to/unique/id, '.something.else') |
| text          | id-capture | oc-request-id|  |

**Comment by pbowen-oc** [comment]
@MartijnR - Our approach has changed and it doesn't look like we will need this.
