### ISSUE TITLE
read-only enketo view

### ISSUE THREAD

**Issue by willywutang** [kobotoolbox/enketo-express#1053]
Is there a read-only view supported in Enketo? 

Currently we see Enketo through Kobotoolbox when records are being edited, but it would also be ideal to use Enketo's view for read-only browsing of records.

**Comment by MartijnR** [comment]
There certainly is!

record: https://apidocs.enketo.org/v2#/post-instance-view
empty form: https://apidocs.enketo.org/v2#/post-survey-view
record as pdf: https://apidocs.enketo.org/v2#/post-instance-view-pdf
empty form as pdf: https://apidocs.enketo.org/v2#/post-survey-view-pdf

I don't think KoBoToolbox is exposing these features yet, but it will help if you provide feedback that you desire this.

**Comment by willywutang** [comment]
Thanks for the rapid reply, will do!
