### ISSUE TITLE
Signature type field, inside compact group, partially working 

### ISSUE THREAD

**Issue by fishbaugher** [kobotoolbox/enketo-express#1055]
If an element of type image with appearance = signature is placed inside a group with appearance = compact, then the signature will not work (no op) unless the browser is resized AFTER the group is expanded (I assume a refresh occurs that enables the signature image).  Tested with desktop Chrome.

An XLS is attached that demonstrates the problem.

[Signature Test.xlsx](https://github.com/kobotoolbox/enketo-express/files/2111323/Signature.Test.xlsx)

If the appearance = compact is removed from the group, then the signature element works normally.

**Comment by MartijnR** [comment]
Thanks a lot!

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/commit/17952b80bc061dbef877c627aa6c91377f99489e
