### ISSUE TITLE
geojson in API

### ISSUE THREAD

**Issue by Svensl** [kobotoolbox/enketo-express#1059]
Dear Kobotoolbox team,
If I am not mistaken, outputs of the API do not include geojson format. Would it be possible to develop that? It would be very useful for GIS integration.
Best,
Sven

**Comment by MartijnR** [comment]
I agree! Not on the Enketo side, but the export side.

@jnm In which repo would this belong?

**Comment by Svensl** [comment]
Dear Martin,

Just wrote to Emily the specs that would make it seamless for us. Am copying here:

GeoJSON specifications for an integration in MapX (https://app.mapx.org/):
- no more than one level per attribute in "properties" (allowed by the spec of GeoJSON but difficult to work with for an integration in PostgreSQL - if needed in the future) -> each question should be a key/value pair in the first level of "properties"
- should pass those tests: http://geojsonlint.com/ & ogrinfo <name of GeoJSON>
- should be usable in a GIS (e.g. QGIS)

Example of what we need (one level per attribute):

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Mr. X",
    "number": 127,
    "url": "https://media.wired.com/photos/5a970eb4927dc94e67685b0e/master/pass/matterhorn-802950172.jpg"
  }
}

Example of what to avoid (multiple levels per attribute):

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Mr. X",
    "number": {
      "year": {
        "2000": ["a", "b", "c"],
        "2001": ["a", "b", "d"]
      }
    },
    "url": "https://media.wired.com/photos/5a970eb4927dc94e67685b0e/master/pass/matterhorn-802950172.jpg"
  }
}

Best regards and keep up the good work!

**Comment by MartijnR** [comment]
Great thanks. I hope this can be done!
