### ISSUE TITLE
jr:choice-name() not working with select_one appearance = autocomplete

### ISSUE THREAD

**Issue by fishbaugher** [kobotoolbox/enketo-express#1060]
If a select_one type element uses appearance = autocomplete, then the jr:choice-name() function does not work with that element.  Attached is an XLSForm that demonstrates.  If autocomplete is removed from the appearance column of the select_one element, THEN the subsequent call to jr:choice-name() works as expected, otherwise it returns blank.

Tested with Ona and Chrome Desktop Version 67.0.3396.79 (Official Build) (64-bit)

[Label Test.xlsx](https://github.com/kobotoolbox/enketo-express/files/2115121/Label.Test.xlsx)

**Comment by MartijnR** [comment]
Excellent. Thanks! 

(this one may take a while to get fixed).

**Comment by MartijnR** [comment]
* [ ] also test fix in Safari (with JS autocomplete widget)
