### ISSUE TITLE
Markdown in label column does not work with hard line breaks

### ISSUE THREAD

**Issue by fishbaugher** [kobotoolbox/enketo-express#1062]
If a hard line break is added to a label, then the markdown (e.g. ** for bold) will not work across those line breaks.

Attached is an XLSform that demonstrates the problem.

[Markup Error with hard Line Endings.xlsx](https://github.com/kobotoolbox/enketo-express/files/2120228/Markup.Error.with.hard.Line.Endings.xlsx)

**Comment by MartijnR** [comment]
**checking in
github**

**Comment by MartijnR** [comment]
Thanks!

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-transformer#46
