### ISSUE TITLE
Printouts showing print settings window.

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1067]
> We have found some issues with form printing for Firefox, IE, and Safari.  For all of them, it seems that if a non-grid form is printed, the actual print output is covered by the pre-print settings window.

> For safari, there also seemed to be some inconsistency with whether the Show Settings flag actual worked.

> You can see screenshots in the issue we have logged:
https://jira.openclinica.com/browse/OC-9246
https://jira.openclinica.com/browse/OC-9247
https://jira.openclinica.com/browse/OC-9248

**Comment by MartijnR** [comment]
* [ ] IE11 non-grid hide dialog (dialog is only present in OC fork)
* [ ] history issue is related to timing. Need to find an intelligent way of doing this.

**Comment by MartijnR** [comment]
In Safari with Grid themes, the print script fails to call the print function at the right time. It happens many seconds after the form has switched back to regular screen view.

**Comment by MartijnR** [comment]
It looks like Safari waits for all pending actions to be completed before it actually starts showing the browser print dialog. E.g. any pending fieldsubmissions and probably any timeouts. At the moment I see no way of dealing with this. Luckily it's only Safari.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#52
