### ISSUE TITLE
OC Only: no focus on textarea in Participate (old version)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1071]

**Comment by MartijnR** [comment]
Most efficient approach is probably to disable page swipe and let OC see if that solves it.

* [ ] disable pageSwipe in enketo-core `4.13.1.pageSwipe` branch
* [ ] update Enketo Express OC with that enketo-core version and publish 1.35.1.dirty-fixes-2

**Comment by MartijnR** [comment]
OC server not on fixed branch. First check (if not already done):

0. Check last enketo commit (should have commit hash `2480b3c` and tag `1.35.1.dirty-fixes`)
1. `npm install g npm@3`
2. `rm -R node_modules`
3. `npm install`
4. `grunt`
5. restart app

If not successful, I can update the branch with page-swipe disabled.

**Comment by pbowen-oc** [comment]
This is fixed on our end.
