### ISSUE TITLE
IE11 form width varies (and becomes too narrow)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1072]
https://jira.openclinica.com/browse/OC-9287

Possibly related to pages mode. Seems like it might be reducing the width based on the questions on the page.

**Comment by MartijnR** [comment]
Something subtle going here, I think, as I cannot seem to reproduce it.

Does it happen with an empty form?

Can you share the XForm?

**Comment by pbowen-oc** [comment]
It happens with both empty forms and forms that already contain data. I will send the XForm.

**Comment by MartijnR** [comment]
Thanks. I can reproduce it with that form.
