### ISSUE TITLE
OC Only: Async Query widget

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1076]
Somewhat related to #1052

### Objective:
* bypass autocomplete limitations in Safari, IE11 (and probably Edge) of LARGE external files
* bypass general XPath query performance in IE11 of LARGE external files

### The "widget"

Have a 'widget' with a button that upon click makes an (asynchronous) request to an OC endpoint. Possible block complete form UI during request.

1. The url could be a `jr://` url that can be found in the Manifest. 
2. Enketo could pass an `xpath-query` parameter to the API request
3. Enketo could pass a `result-type` to the API request with as possible values `string` and `instance`
4. We don't mix and match asynchronous and synchronous functions in XPath.

simple string, that populates oc1:

| type | name | appearance | bind::oc:api-query | calculation
|------|------|-------------|------------|-----|
| text  | oc1    | oc-api-query  | oc-api(jr://file/abc.xml, /path/to[name=${one}]/node, 'string' ) | |
| calculate | two | | | ${oc1} + 3 |

node fragment (readonly text = note because it doesn't store a value in this node): 

| type | name | appearance | bind::oc:api-query | calculation | 
|------|------|-------------|------------|-----|
| note | oc1    | oc-api-query  | oc-api(jr://file/abc.xml, /path/to[name=${one}]/item, 'instance' ) | |
| calculate | two | | | instance("abc")/path/to/node |

An empty `<instance id="abc" oc:writeable="true" />` would have to be added to the XForm as well for the last example.
 

### Upon failed retrieval:

* user can retry.
* form may have logic that would show errors if the request never succeeds (e.g. required questions that never populate)

### Upon successful retrieval:

If the result is of type `string`, the simplest flavor of this widget would simply populate that question (i.e. that text question with an `oc-api-query` appearance) with the returned value. This seems fairly straightforward.

If the result is of type `instance`, it could populate/add/refresh (?) an instance in the form. (NOTE: requires creating support for writable instances, and triggering re-evaluation of logic when such an instance gets re-freshed).
There could be other questions that use that instance, e.g. calculations or selects that will get updated. Not sure yet about the XForm and XLSForm syntax possibilities here.

**Comment by MartijnR** [comment]
for simple string version:

* [ ] let `oc:api-query` bind attribute be passed to output
* [ ] add widget to enketo-express-oc

**Comment by MartijnR** [comment]
What we actually need to use for the instance population is XForms actions.

**Comment by MartijnR** [comment]
Does the first parameter of `oc-api` make sense? Enketo doesn't actually need to retrieve this file. OC needs to be able to find it. Maybe this should just be the OC API endpoint that Enketo should send the request to?

**Comment by pbowen-oc** [comment]
@kkrumlian - We need to provide input to go ahead with this.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#51
