### ISSUE TITLE
OC: DN hover date not padding datetime components

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1077]
> instead of seeing the time portion as "14:01" a few minutes ago, we saw it as "14:1". It seems that single digit values are not being padded with a leading zero. I'm not sure if the same is occurring now we hour values less than 10. Can you update the minutes logic and verify/update the hours logic so that they always display as 2 digits?

**Comment by pbowen-oc** [comment]
@MartijnR - Is there any chance you can make this update on top of our last branch in the next couple hours? We're hoping to push this out today.

**Comment by MartijnR** [comment]
Yes, seems my commit nearly crossed your comment (a few seconds later). It's all done! :)

**Comment by pbowen-oc** [comment]
The padding on hours and minutes looks good. We would also like padding on the days component (for example "09-July-2018" instead of "9-July-2018").

This is not critical, so it can wait until our August release.
