### ISSUE TITLE
ODK note response appears in all caps

### ISSUE THREAD

**Issue by wsteven-son** [kobotoolbox/enketo-express#1078]
When I upload my survey to ODK aggregate and view it on Enketo, the "note" label (our introductory paragraph) is in all caps. This is not how the format is when I create the xml file

**Comment by MartijnR** [comment]
Yes, this was a design decision in the Grid theme to ensure a consistent look.

However, it can be circumvented by adding `no-text-transform` to the style value (in the settings sheet). Multiple values in this field are supported with a space separation so "theme-grid no-text-transform" or "no-text-transform theme-grid" will work. Let us know if that doesn't work properly.
