### ISSUE TITLE
'File' question type stores binary blob

### ISSUE THREAD

**Issue by NeilHendrick** [kobotoolbox/enketo-express#1079]
So, we want users to be able to upload a file (like an excel or word doc) through Enketo. 
If that file type is jpg, it works fine. 
If the file type is docx, Enketo changes the file name to binaryData.docx, sends it to Aggregate. I can download it and open it fine, it's just renamed.
If the file type is excel, it is renamed binaryData.docx, sent to aggregate, when we try to open it, it is malformed and will not open.

**Comment by MartijnR** [comment]
Thanks Neil!

Did you experience this with XLSForm type=file? (which is for any file)

Note, in today's Pyxform release, the XForm syntax for type=file has changed, but I'm assuming you are using an earlier which is supposed to handle docx (too).

**Comment by NeilHendrick** [comment]
yes, using XLSForm, type = file
☞§※⌘✈☂
~Neil

**Comment by lognaturel** [comment]
You are probably running into https://github.com/opendatakit/aggregate/issues/241

**Comment by MartijnR** [comment]
Ah I see. Thanks @lognaturel. 

* [ ] I'll check in Ona, just be sure there is no Enketo issue
