### ISSUE TITLE
Add Chrome iOS support to FAQ

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/enketo-express#1081]
Chrome on iOS supports offline data collection, at least according to the green tick mark. If certain features like file attachments aren't working the [FAQ text](https://enketo.org/faq/#browsers) should specify that. 

(But according to the FAQ entry since all browsers run Safari with a different skin, shouldn't all iOS browsers be supported?)

**Comment by MartijnR** [comment]
Yes, they are. Thanks. Will update!

**Comment by MartijnR** [comment]
moved to referenced issue above
