### ISSUE TITLE
Compact and horizontal-compact appearances work differently

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/enketo-express#1084]
Using `compact` shows the choices tightly but without radio buttons: 
![image](https://user-images.githubusercontent.com/673511/43004479-e885790e-8bfd-11e8-81b1-73ee58c65fb3.png)

Using `horizontal-compact` shows the choices as expected, with radio buttons: 
![image](https://user-images.githubusercontent.com/673511/43004494-f668aa5a-8bfd-11e8-9d44-6c41c896bbf4.png)

According to the `ref-table` [documentation](http://xlsform.org/en/ref-table/) these two should have the same appearance since they are supposed to be aliases. So either they should be listed as different appearances in the table or `compact` should be fixed to work just like `horizontal-compact`.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-core#552
