### ISSUE TITLE
OC Only: Add pid to all /survey/* API endpoints as well

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1085]
as discussed with Yogi

**Comment by MartijnR** [comment]
except in previews

**Comment by MartijnR** [comment]
@pbowen-oc, @yogi-oc, should pid be required or optional for these additional views? (it is required for all instance views).

**Comment by pbowen-oc** [comment]
@MartijnR - I believe we always supply pid outside of the preview context. I don't know whether that means it should be required or not.

**Comment by pbowen-oc** [comment]
@MartijnR @yogi-oc - I found that we actually have one call where we display an existing record but we process it on our end such that we don't send PID with it and we don't want it to be displayed with the form title. So, I think PID needs to be optional.

**Comment by yogi-oc** [comment]
We are getting a 504 when we try to call this URL currently:
https://formpreview.dev.openclinica.io/preview?form=https://build.dev.openclinica.io/form-service/api/versions/5073630/artifacts/build.dev.openclinica.io:form-preview.xml&jini=true
<https://www.google.com/url?q=https://formpreview.dev.openclinica.io/preview?form%3Dhttps://build.dev.openclinica.io/form-service/api/versions/5073630/artifacts/build.dev.openclinica.io:form-preview.xml%26jini%3Dtrue&sa=D&source=hangouts&ust=1532443463578000&usg=AFQjCNFMeeGKdr7bhGWruqp-BRxLXna4fw>

**Comment by MartijnR** [comment]
ok, so 

* [ ] pid in all endpoints except preview
* [ ] pid optional on all supported API endpoints
* [ ] ecid in previews: tbc

**Comment by pbowen-oc** [comment]
This is following up on #1023
