### ISSUE TITLE
A Form pulling from an External CSV does not open as Offline Enketo Form.

### ISSUE THREAD

**Issue by dkwamboka** [kobotoolbox/enketo-express#1086]
Hi Martijn,

An error is thrown when opening an offline Enketo Form that is pulling data from an external CSV.

Server: Ona
Sample [Form](https://docs.google.com/spreadsheets/d/1Gz2r2wVnpSaqI2G_EmfXHdB4lXCXRy8sDlG97F4M_gI/edit#gid=431041519)
External [CSV](https://docs.google.com/spreadsheets/d/1aqjsDOAOnbtIZDJajS6y_AFiettgVcIkD3siqeoCAGY/edit#gid=489612392)
Webform [Link](https://enketo.ona.io/x/#cxHsKF9L)

The Below Error message is displayed:
Chrome:
<img width="563" alt="chrome" src="https://user-images.githubusercontent.com/20725261/43138619-20270d52-8f58-11e8-97e7-f9ef9e781174.png">

Firefox:
<img width="435" alt="firefox" src="https://user-images.githubusercontent.com/20725261/43138563-f4698e88-8f57-11e8-9523-f8f8377d32d1.png">

Explorer:
<img width="421" alt="explorer" src="https://user-images.githubusercontent.com/20725261/43138638-2c7d9738-8f58-11e8-95a5-2f92c9c2eb9e.png">

The form however opens fine as a live form.

**Comment by MartijnR** [comment]
Thanks a lot! I was able to reproduce and confirmed it is related to failing to store the external document in indexedDb.

**Comment by MartijnR** [comment]
http://localhost:8005/x/#54dAJPDf

**Comment by MartijnR** [comment]
probably regression caused by https://github.com/kobotoolbox/enketo-express/commit/5bf20758ca2b13244041969a4944115e6fb1ac33#diff-fc82a39d32fe16f88fc6848922ae0aa3 (directly creating XMLDoc instead of XML string)

**Comment by MartijnR** [comment]
Working on this. Quite a pain to solve without too many string <--> XML transformations

**Comment by MartijnR** [comment]
* [ ] check performance implications of storing as string and not bothering converting back

**Comment by MartijnR** [comment]
fixed in 1.69.1. Thanks a lot @dkwamboka, this revealed another even more serious issue as well!

**Comment by dkwamboka** [comment]
@MartijnR Glad I could be of help!
