### ISSUE TITLE
filter select with images not showing images 

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1089]
as reported here: https://groups.google.com/forum/#!topic/enketo-users/ychN3Y-0aQk

**Comment by MartijnR** [comment]
Definitely an enketo-core issue.

May also need work in enketo-express.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-core#551

**Comment by MartijnR** [comment]
http://localhost:8005/::8qBDPaig
