### ISSUE TITLE
OC Only: IE11 download issues

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1095]
(1)
> We're testing the IE11 file download feature and found that it behaves differently than it does in Chrome. In Chrome, clicking the download link initiates a file download. In IE11, it opens the file in the current tab, at least if it is an image file, and so takes the user away from the form. I tested with a spreadsheet and clicking the download button for that asks me if I want to download the file. Can we add anything to the link to get it to always prompt to download in IE11 or at at least open in a new tab if it does not prompt to download?

(2)
> Also, in IE11, the download link does not work in the same form session that I uploaded the file in (it does nothing). It only works when I close the form and come back to it later. Can this be updated?

**Comment by MartijnR** [comment]
![virtualbox_windows 10_02_08_2018_14_35_48](https://user-images.githubusercontent.com/627350/43609501-6d955282-9661-11e8-94bc-fa628465c009.png)

**Comment by MartijnR** [comment]
Cannot reproduce.

* [ ] once new ee version is published deploy to enke.to and ask Paul, if he can reproduce with widgets form. If he can, it is likely caused by a browser setting.

**Comment by pbowen-oc** [comment]
@MartijnR - The Widgets form initiates a download from IE11 for me. My form is still exhibiting the behavior I described previously in IE11 - Download button is not functional when the file is first uploaded and then upon reopening the form, images open directly in the current tab.  I tried my form with various themes (none, pages, pages them-grid) but that did not change the behavior.

**Comment by MartijnR** [comment]
Since I cannot reproduce this, please send an OC-hosted webform URL that I can access to inspect the DOM.

**Comment by MartijnR** [comment]
https://form.dev.openclinica.io/preview/i/::ceyNyZAm

**Comment by pbowen-oc** [comment]
This is all set on our end after fixing our build process.
