### ISSUE TITLE
OC only: new Participate view

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1102]

**Comment by MartijnR** [comment]
## non-readonly, and note-only view:

- relevant, constraint, required are hard checks, which means the value should not be stored in the model until they pass

## readonly and note-only views:
- regular logic for relevant, constraint, required

**Comment by MartijnR** [comment]
* [ ] create POST /survey/participate4 and /instance/participate4/
* [ ] create views (dedicated?)

**Comment by pbowen-oc** [comment]
@MartijnR - I think the value should be cleared and submitted back as null in that case, but the required error message should be displayed immediately (basically, I think this is how it works for required items in general now). Other hard required functionality, like blocking moving to the next page and blocking clicking the Close button, should also be in effect immediately.

I'll confirm this internally.

**Comment by MartijnR** [comment]
| constraint | bind::oc:constraint-type |
|-----------|--------------------------|
| . > 5          |                                           |

**Comment by MartijnR** [comment]
local test form: http://localhost:8005/single/fs/participant/i/::9fab8d28abfc8e0ee51b3744d21963fa?ecid=a

**Comment by pbowen-oc** [comment]
@MartijnR - We've thought about it more and decided that attempting to clear a strict required item should work in a similar way to attempting to change the value of a strict constraint item to an invalid value. 

If an item is strict required and currently has a value and then the user clears the value of that item, it should immediately revert the item to its previous value (without submitting the blank value to OC) and show a popup error message on the form.

**Comment by MartijnR** [comment]
@pbowen-oc in the common page validation feature, Enketo only requires validation for Next, not for Back. Would you want this custom hard page validation to do the same or block both Next and Back if current page fails validation?

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, we should only block advancing to the next page, not going back to the previous page. If the Go to beginning/end buttons are present, it should similarly prevent going to the end but not going back to the beginning.

**Comment by MartijnR** [comment]
This work is available for initial testing in `develop` branch.

**Comment by MartijnR** [comment]
* [ ] close button should only be on last page

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#48
