### ISSUE TITLE
Text fields don't appear in View mode if the field is empty

### ISSUE THREAD

**Issue by pbowen-oc** [kobotoolbox/enketo-express#1104]
Steps:
1. Open a form in read-only mode or review-only mode.

Expected:
All text, number, and date input areas are displayed.

Actual:
Any text, number, or date items that don't have values are not being displayed.  The labels are being displayed, but not the input areas. If any of these items have values, the input areas is being displayed.

![2018-08-20 14_17_37-openclinica](https://user-images.githubusercontent.com/25179620/44359590-55642700-a486-11e8-84c6-1bd68ecd1be4.png)
![2018-08-20 14_18_06-openclinica](https://user-images.githubusercontent.com/25179620/44359591-55642700-a486-11e8-91c8-bbed5081e971.png)
[XForm - text fields not showing in view mode.xml.txt](https://github.com/kobotoolbox/enketo-express/files/2303559/XForm.-.text.fields.not.showing.in.view.mode.xml.txt)

**Comment by MartijnR** [comment]
Thanks.

This will require making a distinction between a regular "note" in any view and a question without a value that was forced to read-only in a special read-only view.

* [ ] check if additional class can be added to normally non-readonly questions that are forced to readonly in a readonly view.

**Comment by MartijnR** [comment]
Alternatively, the readonly module, could not set the .empty class for .readonly-forced questions. That may be cleaner.

**Comment by MartijnR** [comment]
* [ ] change readonlify function in enketo-express
* [ ] change readonlify function in enketo-express-oc (fieldsubmissions views)
