### ISSUE TITLE
Pages forms loading incorrect Page 1 that only has an item label

### ISSUE THREAD

**Issue by pbowen-oc** [kobotoolbox/enketo-express#1105]
We're seeing two different types of incorrect behavior for pages forms with field-list repeating groups.

For a Pages form with only one repeating group (and no other items), the form is loading with page 1 as just the first label and no way to navigate to the next page.:
[XForm - one repeating group.xml.txt](https://github.com/kobotoolbox/enketo-express/files/2303595/XForm.-.one.repeating.group.xml.txt)
![2018-08-20 14_52_32-openclinica](https://user-images.githubusercontent.com/25179620/44360539-1f747200-a489-11e8-9380-f92c6d9e2e21.png)

For a Pages for with only two repeating groups (and no other items), the form is loading with page 1 as just the first label. There is a Next button and clicking it takes the user to correct page 1 (with no way way to navigate back to the partial page 1).
[XForm - two repeating groups.xml.txt](https://github.com/kobotoolbox/enketo-express/files/2303597/XForm.-.two.repeating.groups.xml.txt)
![2018-08-20 14_48_18-openclinica](https://user-images.githubusercontent.com/25179620/44360598-4f237a00-a489-11e8-846e-5ab81b8dfd58.png)
![2018-08-20 14_48_43-openclinica](https://user-images.githubusercontent.com/25179620/44360600-5054a700-a489-11e8-9396-70ed7f1d6fd3.png)

**Comment by MartijnR** [comment]
Seems to have to do with repeat=page and first page=repeat

**Comment by MartijnR** [comment]
* [ ] remove "current" and "contains-current" from repeat templates
* [ ] ensure that addrepeat handler in pages module, sets first repeat to current if there is only 1 page (even if repeat was added by countUpdate)
