### ISSUE TITLE
OC only: Close button issue

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#1107]
> We have noticed an issue that occurs when the All Changes Saved message appears and causes the Close button to be pushed down the page.

Steps:
1. Open a form that does not have any calculated items (i.e., there is no "All Changes Saved" message displayed upon opening the form)
2. Click into a text field and type a character. Do not click out of the field.
3. At the bottom of the form, click the Close button near the top edge of the button.

Expected:
The form closes and the text entered into the field is saved.

Actual:
The form is not closed. The All Changes Saved message appears when the text is saved and the message pushes the Close button down the page (your mouse cursor is no longer over the Close button after it is pushed down).

Note: If you click near the bottom edge of the Close button in Step 3, the form does Close with that click. The All Changes Saved Message appears and pushes the Close button down, but the mouse cursor is still over the Close button.

It looks like what we need is for an empty line (or perhaps " ") to be displayed upon opening the form prior to the first Saving/All Changes Saved/Failed to Save Changes message being displayed so that the buttons do not get displaced once those messages appear.

**Comment by pbowen-oc** [comment]
@MartijnR - I'm still seeing this issue. Please see the attached screenshots showing before and after data was entered:
![2018-08-22 18_50_22-openclinica](https://user-images.githubusercontent.com/25179620/44495110-956d0a80-a63c-11e8-99d1-1e3f509e8f89.png)
![2018-08-22 18_50_51-](https://user-images.githubusercontent.com/25179620/44495111-9605a100-a63c-11e8-9275-34e52a3cae3a.png)

**Comment by MartijnR** [comment]
Ah thanks. Sorry about that.

* [ ] let field-submission-status element be present upon load
