### ISSUE TITLE
randomize=true not working

### ISSUE THREAD

**Issue by danbjoseph** [kobotoolbox/enketo-express#1120]
user created a form on KoBoToolbox, but in the web submission option, the order of the options is not being randomized. XLSForm excerpt below. not using itext() labels (enketo/enketo-core#532).

**survey**

type | name | label | required | parameters | calculation | appearance | relevant | $given_name
-- | -- | -- | -- | -- | -- | -- | -- | --
start | start |   |   |   |   |   |   |  
end | end |   |   |   |   |   |   |  
today | today |   |   |   |   |   |   |  
begin_group | RC |   |   |   |   |   |   |  
note | heading1 | Red Cross/ Red Crescent Competencies | false |   |   |   |   |  
select_one RC1A_ans | RC1A | 1) Movement context, principles and values- (PART A) | true | randomize=true |   |   |  
select_one RC1B_ans | RC1B | 1) Movement context, principles and values- (PART B) | true | randomize=true |   |   |  
select_one RC1C_ans | RC1C | 1) Movement context, principles and values- (PART C) | true | randomize=true |   |   |  
calculate | cal_RC1 |   | false |   | ${RC1A}+${RC1B}+${RC1C} | hidden |   |  
select_one RC2A_ans | RC2A | 2) The Movement in the humanitarian sector (PART A) | true | randomize=true |   |   |  
select_one RC2B_ans | RC2B | 2) The Movement in the humanitarian sector (PART B) | true | randomize=true |   |   |  
calculate | cal_RC2 |   | false |   | ${RC2A}+${RC2B} | hidden |   |  
end_group |   |   |   |   |   |   |   |  

**choices**

list_name | name | label
-- | -- | --
RC1A_ans | 1 | Clearly describe the Movement mandates, fundamental principles &   values and relate them to own work
RC1A_ans | 10 | Explain the unique role and mandate of the Movement within the   humanitarian sector to other organisations and stakeholders and apply this to   own work
RC1A_ans | 100 | Confidently advocate the unique features of the Movement and interpret   the principles for our work, to support and guide decisions, negotiations,   ways of working and motivation
RC1A_ans | 0 | None of these statements apply to me
RC1B_ans | 1 | Demonstrate the importance of local volunteers and their role in the   emergency operation context. Coach and mentor volunteers where needed and   look out for their wellbeing as part of the overall workforce
RC1B_ans | 10 | Engage National Societies and provide support and tools to identify,   recruit, manage and motivate volunteers best suited for serving the needs of   the community
RC1B_ans | 100 | Promote and enable the  role of   volunteers. Model fair treatment of volunteers workforce. Support the   National Society to strategically manage the volunteer workforce during the   different phases of an operation
RC1B_ans | 0 | None of these statements apply to me

**settings** 

| style |
| -- |
| pages |

**Comment by MartijnR** [comment]
Thanks a lot Dan! Will check it out.

**Comment by danbjoseph** [comment]
Thank you. Let me know if you need the full XLSForm or something in order to troubleshoot.

**Comment by MartijnR** [comment]
@danbjoseph I suspect you're experiencing this only when uploading the form to KoBoToolbox and not when looking at the preview on e.g. opendatakit.org/xlsform. Is that right?

I suspect KoBo may still be behind in the pyxform version they are using, so the XForm they produce doesn't include any reference to randomization. I'm checking with them.

**Comment by MartijnR** [comment]
Yes, they are behind, so that's probably the issue.

They're close to catching up though! https://github.com/kobotoolbox/kpi/issues/2000. 

Please re-open if that's not the issue. Thanks!
