### ISSUE TITLE
Some polygons in SVG map can't be selected

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/enketo-express#1128]
When testing the demo form for the SVG question type, some US states (RI, KY, DC) can't be selected. 

![image](https://user-images.githubusercontent.com/673511/48639142-afe72380-e9a0-11e8-9df4-9e3d0ecad06a.png)

I'm guessing this is just a quirk with the SVG, but may be worth fixing so users testing this are not confused.

**Comment by MartijnR** [comment]
Yes, indeed. Thanks.

* [ ] add IDs for Kentucky, Rhode Island (assuming there aren't any)

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#74
