### ISSUE TITLE
Polyfill V2 not loading correctly as Urls and version changed to V3

### ISSUE THREAD

**Issue by janknobloch** [kobotoolbox/enketo-express#1134]
maybe related to: #1054 

Warning: Done, with errors: command "mkdir -p public/js/build && curl "https://cdn.polyfill.io/v2/polyfill.min.js?ua=ie%2F11.0.0&features=es2015%2Ces2016%2Ces2017%2Ces2018%2Cdefault-3.6%2Cfetch" -o "public/js/build/ie11-polyfill.min.js"" (target "ie11polyfill") exited with code 6. Use --force to continue.

**Comment by janknobloch** [comment]
nvm -> had some docker container issues accessing polyfill.io / however ive seen the v2 url actually dos not redirect properly to v3 so maybe this could get an issue sooner or later..

**Comment by MartijnR** [comment]
Thanks, I think this may already be addressed: https://github.com/kobotoolbox/enketo-express/blob/master/Gruntfile.js#L97
