### ISSUE TITLE
Calendar not showing with ``datetime`` question type in Enketo

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/enketo-express#1143]
Enketo does not show up calendar with ``datetime`` question type. ``datetime`` however works perfectly with collect android app (KoBoCollect or ODK Collect).  

``date`` question type displays the calendar as it should:

![image](https://user-images.githubusercontent.com/50188479/77940807-efce5280-72d8-11ea-8faf-90f0f41b951e.png)

However the ``datetime`` question type does not as it should:

![image](https://user-images.githubusercontent.com/50188479/77940869-070d4000-72d9-11ea-981a-6f1e437266ba.png)

**Reference xlsform:**

[Date & Time (Check).xlsx](https://github.com/kobotoolbox/enketo-express/files/4404317/Date.Time.Check.xlsx)

**Flowdock:** https://www.flowdock.com/app/kobotoolbox/support/threads/zPF7Ud-CyqXA979Bn3Xtz0qFmST

**Community forum:** 
https://community.kobotoolbox.org/t/datetime-type-question-not-working-in-enekto/8456

**Comment by MartijnR** [comment]
Hi Kalyan,

Best to report to keep issues centrally in enketo/enketo-express.

This looks like an issue with how Enketo Express is configured. See e.g. http://opendatakit.org/xlsform/ or https://enke.to/widgets.
