### ISSUE TITLE
Submission success message not positioned correctly

### ISSUE THREAD

**Issue by ccollins0601** [kobotoolbox/enketo-express#116]
Upon submit of data, the modal overlay of the 'Submission Successful!' message does not show up on the screen. Basically, when you hit submit button you get jumped to the top of the page, but the overlay appears at the bottom where you were prior to submit. So the result is user only sees a greyed-out form unless they know to scroll back down to see the overlay.

![modal problem 2](https://cloud.githubusercontent.com/assets/5496880/5458027/2db64ab2-851d-11e4-8b3f-32913e769a68.png)
![modal problem 1](https://cloud.githubusercontent.com/assets/5496880/5458026/2db09932-851d-11e4-859a-8982df3dc1fc.png)

Observed on FF, Chrome, and Chromium on Mac and Linux. Enketo express code from Dec 5. This was not occurring in earlier builds prior.

**Comment by ccollins0601** [comment]
Confirmed fixed (finally), works great. Now the overlay appears when you submit, then the browser jumps you up to the top of the form but the overlay moves up along with you. Tested in FF35 and Chromium 37.

**Comment by MartijnR** [comment]
Great! I've actually switched to a new Dialog library in the offline-records-forms branch. There were additional problems with the old dialogs.
