### ISSUE TITLE
Desktop: Calendar field locks up if Widget is dismissed with Esc [2]

### ISSUE THREAD

**Issue by hhonshuku** [kobotoolbox/enketo-express#122]
If user used [Esc] key to dismiss the opened calendar widget, user is no longer able to reopen the widget by clicking the field until reloading or [TAB] to one before/after field then back to the target date field.

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/issues/351

**Comment by MartijnR** [comment]
still the case

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#75
