### ISSUE TITLE
Desktop/FireFox30: Calendar Widget position issue

### ISSUE THREAD

**Issue by hhonshuku** [kobotoolbox/enketo-express#123]
FireFox30/OSX10.10.1
Calendar Widget is popping up to a distant above position.  When the date field is down below, user probably will not notice the widget was opened at the beginning of the page.  This does not happen with Chrome.  Please see attached screenshot.

![mozilla-firefox](https://cloud.githubusercontent.com/assets/8268231/5507388/96d235d8-8770-11e4-8982-0c88185eca3e.png)

**Comment by hhonshuku** [comment]
Hi,

We updated supporting FF version to 34.0.5, and this issue became a non issue.  Best regards.

**Comment by MartijnR** [comment]
Great. Thanks!
