### ISSUE TITLE
Entered Real val turns into Int if arrow key is accidentaly pressed [2]

### ISSUE THREAD

**Issue by hhonshuku** [kobotoolbox/enketo-express#124]
This is a usability issue, while it is a minor functionality bug.
- If you enter 1.14568293402 into a Real Number field, and
- If you touch up arrow key accidentally, the value turns into 2
  - The correct behavior should be 1.14568293403 instead of 2
- If you touched down arrow key accidentally, the value turns into 1
  - The correct behavior should be 1.14568293401 instead of 1

At this point, you must re-type the value. I personally do not wish arrow keys to be linked with increment/decrement.  More often than not, I try to jump cursor top by up arrow or home key, and jump cursor end by down arrow or end key.  The current numeric field widget does not provide the way to go to the beginning/ending of the string, unless I am missing something.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#76
