### ISSUE TITLE
Select with appearance=minimal show selected value instead of '1 selected' [1]

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#136]
from @tinok 

> UI improvement suggestion for appearance=minimal: When a user selects an option that's longer than a few characters it shows '1 selected' rather than the actual value. I'd recommend that this always displays the entire label if it's just one option selected, make the field wider to display any value up to 100% of the width available, and truncate the displayed text in case it's longer than this width

**Comment by gessel** [comment]
Very much agree - the "1 selected" result can easily be confusing, suggesting to the user that they accidentally selected the choice "1 selected" rather than what they want.

**Comment by tinok** [comment]
I also suggest that we make the default dropdown wider - maybe 50%?

**Comment by MartijnR** [comment]
* [ ] check FF
* [ ] check IE
* [ ] check Safari
* [ ] improve vertical-align of all checkboxes and radiobuttons
* [ ] right-align caret
