### ISSUE TITLE
User is taken to top of Page when adding another instance of a repeating group

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#138]
When a User clicks the "+" button on the newest Repeating Group, he is taken to the top of the page as opposed to remaining at the top of the the newly created group; observed in Desktop FF + Chrome and FF and Chrome on Android.

**Comment by jbonica** [comment]
Sorry for the delay in follow-up. I tried a single page XForm with a Repeating Group and that works fine. When I added a second page, that is when the error showed up.

**Comment by MartijnR** [comment]
I believe this was fixed. Please re-open when necessary.
