### ISSUE TITLE
Operation of "+" and "-" buttons in Repeating Groups is inconsistent [1]

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#139]
When there are three or more Repeating Groups, only the "+" button on the newest group is active, however the "-" button is active on all groups except the first; observed in Desktop FF + Chrome and Android FF + Chrome.

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/issues/402

**Comment by MartijnR** [comment]
Addressed by above enketo core issue
