### ISSUE TITLE
Missing translations[1]

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#142]
Most of these are in Enketo-core. To support translations for enketo-core strings, we could create a fake translator.js that simply returns the english strings. In enketo-express the fake translator would be replaced with the real one:

* [x] geo widget: latitude, longitude, altitude, accuracy, points, kml
* [ ] filepicker button (if we add this)
* [x] selectpicker 'x selected'
* [x] print dialog title (Grid theme) - ALREADY DONE IN EE

The gulp config for the translator may have to be updated to look inside the enketo-core folder.

**Comment by MartijnR** [comment]
if implemented: 

* [ ] add-new-repeat question

**Comment by MartijnR** [comment]
* [ ] default constraint msg: Value not allowed
* [ ] default required msg: This field is required

**Comment by MartijnR** [comment]
This would a simpler approach actually: https://github.com/enketo/enketo-xslt/commit/c4b804632f8c76da139c63890fd546558a2c275c#diff-5effe98417fff7626de0c38427edbaacR956

**Comment by MartijnR** [comment]
* [ ] do XLST strings in EE by adding a localize() function that searches for span[data-i18n] or something

**Comment by hossein** [comment]
There is a small lonely `<span class="required-subtle">Required</span>` in enketo-core/src/js/Form.js which also needs translating. Please take a look.

**Comment by MartijnR** [comment]
Aha! Good one. Thanks!
