### ISSUE TITLE
Control Character validation failure

### ISSUE THREAD

**Issue by hhonshuku** [kobotoolbox/enketo-express#148]
Text field should be rejecting a control character.

If a user copy/paste a string from MSWord running on Windows, sometimes an invisible control character is included.  When it happens, Enketo [Submit] invokes endless "Submitting...." window and freezes.  The data is not reaching to the back end (which is a good thing!).

A control character should be either escaped or rejected.

One of the control characters we often observe from our user is 0x03, which is an End of Text marker.  Some time we see 0x00, which is a null char.  Not sure why Windows MSWord does this.

**Comment by MartijnR** [comment]
Nice one! Thanks.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#78
