### ISSUE TITLE
Offline media upload

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#176]
This is more of a question: Does offline capability (I know it's still experimental) support media upload at the moment?I did a self-install and created a form that included a photo and audio data types. My submissions uploaded ok but without the media attachments.

**Comment by MartijnR** [comment]
Thanks for posting this! What browser are you using? Latest version?

**Comment by ivermac** [comment]
I am using google chrome version 41.0.2272.101 (64-bit) on mac yosemite

**Comment by MartijnR** [comment]
https://github.com/kobotoolbox/enketo-express/commit/d159079119ec6c24f53b631d2f873bbff9054466

Should be fixed now (v1.8.2). Am glad you found this.
