### ISSUE TITLE
protocol in API response incorrect when reverse proxy used

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#182]
This is more of a question than an issue. We are hosting enketo express which can be accessed via a url whose protocol is `https`. The server url also has a `https` protocol. I tried generating a preview url based on [enketo api docs] (http://apidocs.enketo.org/#/get-preview-survey) and I was able to generate the preview url but the protocol of the preview url was `http` instead of `https`. The quick fix we used was to replace [this line] (https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/api-v2-controller.js#L280) with the snippet below?
```javascsript
...
        protocol = (req.app.get( 'linked form and data server' ).authentication[ 'allow insecure transport' ]) ? req.protocol : "https",
        baseUrl = protocol + '://' + req.headers.host + '/',
```
Does this make sense or might it be something we are doing wrong on our end?

**Comment by MartijnR** [comment]
Hi Mark,

I am assuming you are using e.g. Nginx or Apache in front of Enketo Express (which is great). I think the code change should be something like  `protocol = req.headers['x-forwarded-proto'] || req.protocol`. A somewhat similar change  needs to be made in the authentication controller (#174). It's on my list, but a PR would be very welcome.

**Comment by ivermac** [comment]
Thanks @MartijnR for the response. Yes we are using Nginx in front of Enketo Express. I will make a pull request when am back in the office tomorrow morning

**Comment by MartijnR** [comment]
@ivermac I had to set a https production server, so fixed the https reverse-proxy issues. Let me know if it's still a problem.

Fyi this is the NGINX config I used: https://gist.github.com/MartijnR/2e03a7938d74dd884136.

**Comment by MartijnR** [comment]
and thanks for reporting this bug!
