### ISSUE TITLE
If geo widget is hidden upon load it shows only partial tile (pages mode & relevant) [2]

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#188]
resizing the window shows all tiles, or hide/show input button to resize the map

**Comment by MartijnR** [comment]
https://github.com/Leaflet/Leaflet/issues/694

**Comment by MartijnR** [comment]
The same issue occurs in pages mode and when revealing irrelevant geo widgets.

**Comment by MartijnR** [comment]
This is a workaround for what is probably a leaflet bug. Leaving this issue open to see if the workaround can be removed in the future.

**Comment by JPustkuchen** [comment]
I can confirm this problem still exists in Leaflet 1.0.0-rc1

**Comment by MartijnR** [comment]
Thanks!

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-core#558
