### ISSUE TITLE
Enketo won't work under pm2, works under grunt develop

### ISSUE THREAD

**Issue by ccollins0601** [kobotoolbox/enketo-express#195]
Hi Martijn, 
Running into a problem using your latest code with ODK Aggregate that Steve and I think might be a bug. Everything works ok running 'grunt develop' but when we run using pm2 I get an error when trying to load a form (http://45.55.155.245/::YYYo). The browser just shows the spinner and the browser console has the error below. Any ideas what may be happening? I tried in multple browsers, error always seems to occur when using pm2. Server is Ubuntu 14.04.2 LTS

This is for a staging server, so Aggregate and enketo are running http using IPs rather than domains.

Uncaught Error: Mismatched anonymous define() module: function (){return k}
http://requirejs.org/docs/errors.html#mismatch 
webform-combined.min.js:1

Thanks,
Cal

PS - Beginning of config.json (everything else is default):

    "app name": "MySafeCare Staging",
    "port": "80",
    "offline enabled": false,
    "linked form and data server": {
        "name": "MySafeCare",
        "server url": "http://45.55.155.245:8081/",
        "api key": "mysafecare",
        "authentication": {
            "managed by enketo": true,
            "allow insecure transport": true,
            "external login url that sets cookie": "http://example.com/login?return={RETURNURL}"
        }
    },

**Comment by MartijnR** [comment]
Thanks. I think the build must have also failed (`grunt`).

I neglected to add a warning to the changelog that one widget has been removed. Leaving that widget in config.json would show an error like that. (Another widget has been added as well).

I have updated the changelog. Let me know if that fixed it.

**Comment by esmail** [comment]
I'm still seeing this behaviour today when previewing. On the other hand, the survey entry page (at least the offline one) appears to be loading fine.

**Comment by MartijnR** [comment]
When trying to reproduce this in the vagrant vm, I see pm2 is acting weird. The app is running but `pm2 list` shows nothing and the app still runs after `pm2 kill` . I'm starting to develop a dislike for pm2..

@ccollins0601 @esmail Did you both experience this issue in a VM?

**Comment by ccollins0601** [comment]
I was running on a digital ocean VM via vagrant.

Yes, I believe the same thing happened to me at least once needing to kill
the process itself because pm2 was being so unpredictable.

We had a deadline and I ended up going back to an earlier enketo build so
haven't had a chance to try it again yet with your fixes. I will give it a
shot this week.

Cal



------------------------------------------------------------------

Cal Collins
OpenClinica LLC
ccollins@openclinica.com

Join us at OC15 <https://community.openclinica.com/conference>!
May 31 - June 1, Amsterdam, The Netherlands

**Comment by esmail** [comment]
Yes; I'm encountering the issue in our KoBo VM (using your `bootstrap.sh` script for EE installation).

**Comment by MartijnR** [comment]
This turned out the be the issue, unrelated to pm2: https://github.com/mholt/PapaParse/issues/209.

**Comment by esmail** [comment]
Thanks!
