### ISSUE TITLE
Export button is disabled

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#219]
Hi @MartijnR, this is a question. We noticed the export button, as seen below on the screenshot, is disabled. We wanted to ask if there are any reasons why it's disabled. Thanks.
![image](https://cloud.githubusercontent.com/assets/1128227/8029534/12aa3688-0dc7-11e5-9775-f02233c2f5cf.png)

**Comment by MartijnR** [comment]
Hi Mark, 

Yes, definitely, but it is not funded yet. I would like to implement 'import' at the same time, which makes it a fairly big (expensive) project. Maybe something for Ona to find funding for ;)?

cc: @mberg

**Comment by ivermac** [comment]
Thanks for the response Martin
