### ISSUE TITLE
Form in pages mode is not reset properly

### ISSUE THREAD

**Issue by LG7119** [kobotoolbox/enketo-express#220]
Hi Martijn,

We've found three issues regarding the new offline-enabled form.

1. When the wireless network connection is available, the form data could not be immediately uploaded onto the web server after the "submit" button was clicked. There was about 5 minutes delay in data transmission. 

2. "Upload" button and "Export" button are disabled.
![image](https://cloud.githubusercontent.com/assets/12621461/8051551/36be5572-0ec1-11e5-8f7b-3d37d7a3ca18.png)

3. Form has to be refreshed for the next data entry. Otherwise, it could not be rendered properly. For example, we have designed a one-question-per-page survey for prostate cancer patients. All the questions are compulsory to be answered. The first patient happened to skip question 7 and completed the rest questions. After the "submit" button was clicked, an alert message was displayed and question 7 was brought back to the screen. The patient re-answered question 7 and then successfully submitted the data.  When the second patient did this survey, if he hit "back" button to review the questions which he had completed, two or more questions rather than one were present. However, this problem would not occur if the form was re-loaded (refreshed) before entering data for the next patient. 
![image](https://cloud.githubusercontent.com/assets/12621461/8052059/b1b79040-0ec6-11e5-86a3-279b323943f4.png)

![image](https://cloud.githubusercontent.com/assets/12621461/8052063/bc558a84-0ec6-11e5-9a3e-8f3e7557a5c0.png)

Would you please provide any suggestion to solve these problems?

Many thanks
Lesley

**Comment by MartijnR** [comment]
Hi Lesley, 

Thanks for this. In the future please create 3 separate issues.

1. This is by design. We may tweak that. Clicking the upload button should work to force an upload. If not, please try to find a way to help me reproduce it and create a new issue. Also curious if you see any errors.

2. Thanks. I'll remove the export button. This is for future functionality. The upload button is only functional if there are 'Final' records in the queue, by design. If you're seeing a different behaviour. Please create a new issue (can you reproduce the issue on http://enk.to/_/#widgets?)

3. This sounds serious. I'll rename the title of this github issue to reflect just this issue. Please help me to reproduce this by sending a link to your form e.g. on Google Docs (or email it).

**Comment by LG7119** [comment]
Hi Martijn,
Thanks very much for your reply. I am attaching the form for your investigating the problem.
Kind regardsLesley

Date: Tue, 9 Jun 2015 08:35:09 -0700

**Comment by MartijnR** [comment]
Attaching doesn't work for GitHub issues unfortunately. If you don't use Google Docs, you could send it by email to martijn @ enketo.org

**Comment by MartijnR** [comment]
Thanks a lot for sending the form! I tried to reproduce the issue, but did not succeed. Could you perhaps elaborate, preferably step by step, how I can reproduce the issue? To make sure your enketo-express installation is working correctly you can also upload your XLSform [here](http://opendatakit.org/xiframe/) and click _Preview in Enketo_. Steps e.g.:

1. Load form
2. fill in data in all fields expect question 7
3. hit submit button
4. fill in missing question 7
5. submit successfully
6. ?
7. ?
8. issue: what do you see and what were you expecting to see?

**Comment by LG7119** [comment]
Hi Martijn,
Thanks very much for your prompt response. I've re-tested "upload" button to force the data submission. It was working but there was a few minutes delay (due to slow wireless network???). Anyway, after the web server had received the data, the record was still kept in the queue for a while. This might cause a little bit confusion.

**Comment by LG7119** [comment]
Hi Martijn,
I uploaded my XLSform to "http://opendatakit.org/xiframe/" as per your instruction, filled in all the fields except question 7 and got the following screenshots:
 
![image](https://cloud.githubusercontent.com/assets/12621461/8151631/98a8e5c6-1354-11e5-867b-6fac0411a22d.png)

![image](https://cloud.githubusercontent.com/assets/12621461/8151640/adca1bbe-1354-11e5-9782-f32ea8f59054.png)

![image](https://cloud.githubusercontent.com/assets/12621461/8151645/d55788e2-1354-11e5-8a6b-c3b001209685.png)

The last screenshot shows that the client-side form data is valid (by clicking "validate" button) but not submitted to the browser (localhost or other web server) to save. If the "validate" button is replaced with "Submit" button (provided by the installation of Enketo- Express), the issue I mentioned before will occur.  This is the process of testing XLSform in my workstation (another workstation is used as the web server):

1. The first patient missed out question 7 and completed the rest questions. After clicking "Submit" button:

![image](https://cloud.githubusercontent.com/assets/12621461/8151785/08a19236-1357-11e5-8918-509f30d25adf.png)

2. Filled in question 7
![image](https://cloud.githubusercontent.com/assets/12621461/8151902/4f9057d4-1359-11e5-9425-449e874b4828.png)

3. Submitted. (Then, the first web page for entering patient demographics was displayed.)

4. The second patient has completed all the questions. He hit "Back" to review his answers before submitting the data.

![image](https://cloud.githubusercontent.com/assets/12621461/8152007/0404cf00-135b-11e5-9882-f2f6f1a88fba.png)

![image](https://cloud.githubusercontent.com/assets/12621461/8151966/4b3e1170-135a-11e5-93fd-880f1b0366b7.png)

 (By the form definition, it is expected that one question is displayed on each page.)

This issue will occur if the previous patient has missed out any question and corrected it later. However, if refreshing the web browser before the next patient fills in the data, everything works fine. That is, when clicking "Back" to review all the answers before submitting the data, one question is displayed on each question page.  

What I am thinking is that the event associated with "Submit" button only forwards the form data to the browser but does not clean up all the "cookies" for the next data entry. As a result, the browser still "memorizes" what was wrong with the last data entry and thus behaves incorrectly. If this is the right reason causing the issue, then we can explain why manually refreshing the browser helps solve the problem because it deletes the "cookies" generated by the last data entry.

Please correct me if you have different thought.

Many thanks
Lesley

**Comment by MartijnR** [comment]
Thanks so much for your time Lesley. I reproduced this now. Sorry for not seeing this before. Will fix it!

**Comment by MartijnR** [comment]
As a sidenote your form is a good example of what [this proposed new feature](https://github.com/kobotoolbox/enketo-express/issues/224) would be perfect for.

**Comment by LG7119** [comment]
Thanks very much for your time to fix this issue. 

Lesley

**Comment by MartijnR** [comment]
Please don't close. I might forget to fix this :).

**Comment by MartijnR** [comment]
Fixed!

**Comment by LG7119** [comment]
Thanks so much for your kind help, Martijn. Should I re-install Enketo-express and re-configure Kobo Toolbox?

Lesley

**Comment by MartijnR** [comment]
Thank you for reporting this.

Just a regular update of Enketo Express will do fine: https://github.com/kobotoolbox/enketo-express#how-to-update.

**Comment by LG7119** [comment]
Thanks a lot.
