### ISSUE TITLE
Submitting status in form editing take a lot of time

### ISSUE THREAD

**Issue by mraminemx** [kobotoolbox/enketo-express#231]
after changing information in editing form interface, the Submitting... status popup take a lot of time, although in reality the submition is done when you check data in other page

**Comment by MartijnR** [comment]
Thanks. Enketo will wait for the 201 or 202 server response from the data server. Is it possible to check if that response comes through very late?

**Comment by MartijnR** [comment]
After some testing, I think this is caused by the server that you are submitting to. Re-open if you find out a different cause.

**Comment by mraminemx** [comment]
so, what is the solution of this problem ?

**Comment by MartijnR** [comment]
I don't know. I only deal with Enketo. Investigate the response times of the form/data server you are using.
