### ISSUE TITLE
Error message incorrect when editing previously-submitted record with image input.

### ISSUE THREAD

**Issue by mraminemx** [kobotoolbox/enketo-express#232]
error : Cannot read property 'files' of undefined
![tmp](https://cloud.githubusercontent.com/assets/7932387/8252881/6262a4ca-1679-11e5-92d5-759287d7cd20.png)

**Comment by MartijnR** [comment]
thanks!

**Comment by MartijnR** [comment]
That error message is incorrect. It should show a different error message (previews cannot be shown when editing a submitted record - until new feature #50 is completed in both KoBoCAT and Enketo).

**Comment by mraminemx** [comment]
I note also that the error change from one browser to an other 
chorme error : 1st image
firefox error : 2nd image
![sans titre](https://cloud.githubusercontent.com/assets/7932387/8256778/bc71986c-1698-11e5-80b5-cf5926af1657.png)

**Comment by MartijnR** [comment]
Thanks, it should show the correct error message now.

**Comment by mraminemx** [comment]
the message was changed to : "File "PocketGIF_T_FR.gif" could not be found (leave unchanged if already submitted and you want to preserve it)." 
it's good the message is more interesting but we still have the problem that the image is not shown! why ? what is the real problem ?

**Comment by MartijnR** [comment]
lack of feature, see https://github.com/kobotoolbox/enketo-express/issues/50
