### ISSUE TITLE
Authentication check fails with formhub

### ISSUE THREAD

**Issue by longhotsummer** [kobotoolbox/enketo-express#238]
Commit a45334c49ba4d376833be0d0e51a8ce861cecd2d regressed to re-create the bug that a844a7f037ccedf464a7a47a6f894bf0aa62def1 fixed.

Namely, calling HEAD on a formhub instance returns 405 METHOD NOT ALLOWED.

To avoid calling GET and listing all the forms (for performance), perhaps call GET on a URL which returns a simple value? I don't know enough about the formhub API to suggest one.

**Comment by MartijnR** [comment]
That's very silly of me! Thanks a lot for investigating this.

**Comment by MartijnR** [comment]
Yes the idea to use e.g. the submission URL is good, but I know I did this before. Just not sure what the reason was to change this.

**Comment by MartijnR** [comment]
also seem broken in KoBoCAT

**Comment by MartijnR** [comment]
KoBoCAT issue might be different, related to xformsManifest: https://www.flowdock.com/app/kobotoolbox/kobo/threads/6urhMdYpEYFYbd8wz41l1MBIXyp

**Comment by MartijnR** [comment]
FWIW, I'm not happy with this solution, but it's the best I could come up with.

**Comment by pld** [comment]
yeah, but given your constraints this seems reasonable, supporting legacy is always a pain

**Comment by longhotsummer** [comment]
Thanks. What do you recommend as a self-hosted formhub replacement?

**Comment by MartijnR** [comment]
I recommend both KoBoCAT and Ona. Both ported formhub and both are very actively moving it forward (now in different directions). Ona spun off from SEL. Both have an online service as well to try out first. I am not sure which is the most self-install-friendly.
