### ISSUE TITLE
Getting 'Forbidden. Enketo needs to use https' when accessing some web forms

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#239]
Am getting the error in the screenshot below when I try to access a webform using enketo express. Interestingly, this only happens with a couple of forms in certain accounts on ona; with other accounts, I can see the forms.
![screen shot 2015-06-26 at 2 22 39 pm](https://cloud.githubusercontent.com/assets/1128227/8403660/2da8dc94-1e4f-11e5-8378-aea5fa489ef6.png)
Also, I noticed that before this error is shown, the form tries to load with the correct url (like `https://enketo-stage.ona.io/::YYp0`) for about a second or two then renders the error page. In our config.json file, we have `managed by enketo` set to `true` as seen on the screenshot below.
![screen shot 2015-06-29 at 11 22 23 am](https://cloud.githubusercontent.com/assets/1128227/8403833/b45ee67e-1e50-11e5-8e13-1392e7f259f1.png)
It seems none of the conditions in [this line](https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/authentication-controller.js#L42) are met yet the request's protocol is `https`. We are using nginx to serve enketo express. Might there be something am missing or not doing right?

**Comment by MartijnR** [comment]
I think you may not have this line in your nginx config perhaps:

```
proxy_set_header X-Forwarded-Proto https ;
```

See http://blog.enketo.org/install-enketo-production-ubuntu/ for the nginx configuration I'm using.

**Comment by pld** [comment]
@MartijnR yep that was it, thanks for the prompt reply, please close

**Comment by ivermac** [comment]
Thanks @MartijnR

**Comment by MartijnR** [comment]
glad that was it
