### ISSUE TITLE
Unable to load media for protected forms on ODK Aggregate

### ISSUE THREAD

**Issue by bowenli37** [kobotoolbox/enketo-express#240]
When anonymous user is disabled in ODK aggregate, meaning "Data collector", "Data viewer", and the rest all unchecked in site admin, images cannot be loaded.

**Comment by MartijnR** [comment]
Thanks. I was able to reproduce this. It will be fixed.

**Comment by MartijnR** [comment]
Returns 200 responses. odd.

**Comment by MartijnR** [comment]
It's the openrosa header. Will sneak this into a larger issue resolution dealing with communication.
