### ISSUE TITLE
Does Enketo Express support the pulldata function?

### ISSUE THREAD

**Issue by pld** [kobotoolbox/enketo-express#250]
I'm seeing the below failure on enketo express but not on hosted enketo. Is pulldata supported in enketo express?

<img width="499" alt="screen shot 2015-07-07 at 6 18 32 pm" src="https://cloud.githubusercontent.com/assets/50706/8561078/a14cbfae-24d4-11e5-97e1-80e7c9a00f2b.png">

**Comment by MartijnR** [comment]
No, it's not. I don't think there is no need for this function with Enketo's external data (which is not compatible with ODK Collect - see https://github.com/XLSForm/pyxform/issues/30).

The two ways of adding external data in ODK Collect make no sense when looking at XForm syntax. There were designed to avoid having to touch javarosa code.

With Enketo Express we can just use a choice_filter exactly like we do with _internal_ data.

**Comment by mberg** [comment]
Martijn,

The challenge is this creates a huge compatibility issue.  If you use what ODK collect does you get errors like Peter posted above.  

I realize your approach is better but is there any way we can support both?  Or do you have ideas on how we can do a work around?  

It's not feasible to publish a form with two different formats.  Ie) you just want it support ODK or Enketo

**Comment by mberg** [comment]
@MartijnR can you also confirm if pulldata is supported in the old enketo?

**Comment by MartijnR** [comment]
Apologies @pld @mberg, I misunderstood pulldata so maybe it's slightly less serious...

There is indeed no way for Enketo to support ODK Collect's two methods for external data (at least not by me). I don't see a way out, hence my (failed) attempt to rectify this: https://groups.google.com/forum/#!topic/opendatakit-developers/9_VZoe7crVY. 

However, **just the pulldata function** could probably be supported in Enketo if Pyxform is tweaked to add a reference to the external instance (basically to correct the syntax to comply with Enketo/CommCare's external data) as described in XLSForm/pyxform#30. Of course this means that you'll have to reconvert existing XLSForms that contain pulldata(). 

In enketo pulldata('myid', 'fielda', 'fieldb', 'somevalue') would then be handled as a shortcut for the equivalent XPath: `instance('myid')/root/item[fieldb=somevalue]/fielda`.

There is no external data supported at all in Enketo Legacy.

**Comment by pld** [comment]
About Enketo Legacy support, the screenshot I posted is of an errors that's popped on Enketo Express but is not popped on Enketo Legacy.

Perhaps it's just quieter with the error?

**Comment by MartijnR** [comment]
hmm, that's very weird. It definitely should so it sounds like a bug. Maybe an exception occurs and the form doesn't load properly. Do you have a link to a webform?

**Comment by pld** [comment]
Yep, that's exactly what's going on. No bug. @MartijnR thanks for providing clarity on this issue.

**Comment by MartijnR** [comment]
Ah that's good. I was afraid to have to touch enketo-legacy again. :weary:

**Comment by MartijnR** [comment]
@mberg, @pld. I added this as an issue: https://github.com/XLSForm/pyxform/issues/43. It seems worthwhile to implement this in pyxform so that pulldata() could at least be supported in Enketo in newly converted XLSForms. 

Maybe something for Ona to implement?

**Comment by mberg** [comment]
Hi Martijn,

Does this mean pull data would work with enketo express already or do you
need to implement it.  If so, it would be really awesome.

@ukanga is this a heavy lift?  It would help address some big requests for
Andrew

Thanks Martijn

Matt

**Comment by MartijnR** [comment]
I would still need to implement it in Enketo, but it will be a pretty small job I think. For Enketo is just means converting pulldata(a,b,c,d) to /path/to/filterby[with=predicate]/node.

**Comment by MartijnR** [comment]
Just to close this thread: pulldata() is supported in Enketo now if used in conjunction with recent pyxform version

**Comment by overnin** [comment]
Can you be more specific on "recent pyxform version"? 

I'm having some trouble (see screenshot) with an .xls processed with a ONA's pyxform fork https://github.com/onaio/pyxform , would switching to https://github.com/XLSForm/pyxform help?

<img width="943" alt="screen shot 2016-03-30 at 15 46 24" src="https://cloud.githubusercontent.com/assets/896138/14170958/a6db5546-f730-11e5-975e-8fdb4b6eada6.png">

**Comment by MartijnR** [comment]
Specifically, it's this commit: https://github.com/XLSForm/pyxform/commit/9512ba955d291f5e04d7abfa53f5f7453582005f

The XForm should show an `<instance>` with a `src` attribute.

**Comment by overnin** [comment]
Thanks for the quick answer.
