### ISSUE TITLE
Upgrade i18next and simplify directionality determination (in config/express.js) [2]

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#266]
Once https://github.com/i18next/i18next/pull/413 is merged and available in node-i18next

**Comment by MartijnR** [comment]
Gee. Upgrading to 2.x.x is quite a project. It seems the .lng() function is missing. May be better to wait for i18next to stabilize.

**Comment by MartijnR** [comment]
https://github.com/i18next/i18next/issues/489

**Comment by MartijnR** [comment]
Also remove async: false from translation loader. I think we can let translator.js use a `loaded` promise for this and only when the promise has been fulfilled show the modal dialog.

Since this would need to be done in several places (main-webform.js, main-webform-edit.js, controller-webform.js) it might be better to centrally add this to all alert(), confirm() in gui.js.

```js
translator.loaded(then(function(t){{
 t('mykey');
});
```

**Comment by jamuhl** [comment]
sorry for the pain the migration put on you. i tried hard to make it as seemless as possible by introducing a migration option, where most of the old api gets added (http://i18next.com/docs/migration/#v1-11-x--v2-0-0-comp). 

spreaded documentation is a result of changing i18next to be more a core framework with limitless extendability (so no more i18next-node wrapping is needed, just a small middleware).

sync loading had to go but simple to change that in a own backend implementation: https://github.com/i18next/i18next/issues/488

**Comment by jamuhl** [comment]
would you mind when i place enketo logo on i18next.com under a new section 'projects using i18next'?

**Comment by MartijnR** [comment]
Thank you! 

Don't mind my grumbling. :) (It was related to thinking this particular github issue was going to be 1 hour of work).   I can definitely see the logic and improvement in what you have done. Looks like it was a major undertaking! Your project is super useful. Yes, would be great to add the logo. Here is one: https://enketo.org/private_media/images/logo-black.png

**Comment by jamuhl** [comment]
Link added http://i18next.com/ at bottom...thank you

**Comment by MartijnR** [comment]
That's very cool. Thanks!

**Comment by MartijnR** [comment]
* [ ] test translated 404 page by going to non-existent static page
