### ISSUE TITLE
When form is in iframe it is no longer responsive (on iOS?)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#273]
Asked OC for html file to help reproduce this, to make sure that the size of the iframe and any css in the parent document doesn't influence the responsiveness of the enketo form.

cc @kkrumlian, @sdibona

**Comment by MartijnR** [comment]
from discussion the following might resolve it:
```css
.main{
    width: 100%;
}
```
After reproducing, check if the fix works and if it causes a regression of an earlier (overflow) issue.

**Comment by MartijnR** [comment]
@sdibona, @kkrumlian a link to an OpenClinica Participate webform would help too

**Comment by ccollins0601** [comment]
Try
http://ocwebinar.openclinica.info:8082/#/event/SS_101013/dashboard?access_code=20467079&auto_login=true
then click 'let's go'

**Comment by MartijnR** [comment]
Thanks Cal. This page is protected for me. Is it possible to send me the credentials?

**Comment by MartijnR** [comment]
can be reproduced here: http://martijnr.github.io/enketo-iframe-demo/ on safari on iOS (ipod touch)

**Comment by MartijnR** [comment]
relevant commits:

https://github.com/enketo/enketo-core/commit/c67d9c8f2424dd702fee45b8f8ff2d7adaee6f42#diff-deeb6921bc529820dd0312a19d9977ad

https://github.com/enketo/enketo-core/commit/8495cfb99c8f242aef968a51fb614dcf45ea5898#diff-deeb6921bc529820dd0312a19d9977ad

https://github.com/enketo/enketo-core/commit/cc85b12e1f958846badeeddef4cc42be50bb6cd4#diff-deeb6921bc529820dd0312a19d9977ad (this one removed width: 100%)

**Comment by MartijnR** [comment]
I'm still seeing quirky behaviour on http://martijnr.github.io/enketo-iframe-demo/ on Safari on a small iOS ipod touch:

* initial zoom, slightly too much - need to zoom out a bit after loading
* font size for some questions too large, to be resolved by turning to landscape and then back to portrait so not a css issue.

**Comment by MartijnR** [comment]
first issue solved
