### ISSUE TITLE
Improve performance of theme-switching 

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#277]
Theme determination and stylesheet switching was implemented on the client for the future mobile app, but it causes too much screen flickering in the online-only views.

Since the API-set value always wins, we could at least serve the correct api-set stylesheet.

Ideally we would also store the form-defined style in the database (thereby duplicating the theme-determination logic on the client).

**Comment by MartijnR** [comment]
This wouldn't work in the offline view, because the html served should be constant.

**Comment by MartijnR** [comment]
also can't really work for previews.

Alternatively, we could load all theme stylesheets in preview and remove the applicable themes after theme determination on the client.

**Comment by MartijnR** [comment]
The first thing we can do is check if the theme is already loaded. Even swapping with same theme seems to cause flickering!

**Comment by MartijnR** [comment]
flickering to be addressed by https://github.com/kobotoolbox/enketo-express/issues/981.

This issue will be changed into improving theme-switching performance.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#53
