### ISSUE TITLE
Referring to previous repeat: calculations not triggered

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#278]
https://docs.google.com/spreadsheets/d/13tMk8fNhTdAaarBxHotAaKLT7dqw-60gODjiExOlgts/edit?usp=sharing

**Comment by MartijnR** [comment]
two issues:

1. repeat-position injection (due to unfortunate historic javarosa mistake), messes up the expression: `/path/to/repeat[2][position()=2]`
2. references from one repeat to another repeat do not not trigger calculation updates (they haven't for a long time).

**Comment by MartijnR** [comment]
One part of this bug (incorrect calculation) is fixed: https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/tmp/tmpapc1k0/indexed_repeat.xml. However, updating the calculation when the dependent node (in another repeat) updates might not be possible. Will think about a solution.

If no solution can be found that does not severely degrade performance, I think we should discourage referring to a question inside a repeat from another question inside another repeat

**Comment by MartijnR** [comment]
I think this is resolved. Check this.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-core#545
