### ISSUE TITLE
Support ability to annotate form fields with discrepancy notes

### ISSUE THREAD

**Issue by ccollins0601** [kobotoolbox/enketo-express#295]
Support the ability to annotate form fields with notes and flags related to data quality and status of review. Called 'queries' or 'discrepancy notes' in clinical research and used by research teams to request changes to data by the original collectors, have a conversation about a confusing/uncertain piece of data, or to mark a field as having been reviewed/verified. Requirements include:

- Create a Discrepancy Note (DN)
- Visually flag when one or more DNs exists on an existing form, perhaps also showing type and status
- Easily review the existing thread of dns on the item
- Add to the existing dn thread on the item
        - including update status, assign to another user/role, and email user (question: are all of these essential?)
- Review the audit trail on the item 
- Associate a 'soft' edit check with requiring a DN
- Associate a 'soft' edit check with auto-populating a DN
- Associate a 'soft' edit check with providing a predefined list of choices for a DN, or user can enter their own (nice to have)
- Auto-close a DN when soft edit check conditions are later met (nice to have)
- Let designer create custom DN types/statuses (nice to have)
- Show other statuses (like SDV)
- Allow inclusion of item value and other item values when auto-populating DN (nice to have)
- Open DN interface 'inline' with form rather than another window
- Create/update DNs even when not updating/saving form data
- Support DNs on the 'page' level (nice to have)
- Associate any change to existing, saved (completed?) data with requiring a 'Reason for Change' (RFC) DN
- if another type of DN (new or update) is entered simultaneous with the change, consider that as the RFC and dont require a separate RFC
- Let designer populate RFC with common options for selection by user (such as 'self evident correction') (nice to have)
- Apply RFC to a single field, row in a repeating group, or entire form (nice to have)
- Enforce RFC if a repeating group is removed after initial save

While some of these requirements could be handled by the backend server, most of them I believe will need a front-end component. Implementation strategies for enketo might include: 

- Create a custom widget (https://github.com/enketo/enketo-core#how-to-create-or-extend-widgets, https://gist.github.com/MartijnR/6943281) of type 'flag' or 'DN'. Then inject an item of this widget type at form design time adjacent to every 'real' item
- Incorporate this functionality into a custom theme somehow (https://github.com/enketo/enketo-core#notes-for-css-developers) or as part of an 'appearance' on existing widgets
- Add support for the external applications' spec 'http://dimagi.github.io/xform-spec/#external-applications) and interface with a separate app to handle DNs
- handle DNs outside enketo via messaging to a parent iframe using an advanced version of postmessage (https://github.com/enketo/enketo-express/blob/master/APIv2.md#postmessage)

**Comment by MartijnR** [comment]
The above 4 (excellent) suggestions leave most of the functionality outside of Enketo.

Another way of doing this would be by incorporating all this functionality inside Enketo, i.e. receive DN and submit DN within the app. Storing DNs inside the model. The latter would be very complex and deeply change Enketo Express. 

It is probably best to pick one of the 4 suggestions above.

1 & 2 could be combined by triggering the DN widget when a question has a 'dn' appearance. 3 (External applications functionality) might not be the most appropriate since I believe this is used to obtain a value (string) from outside. So that would leave:

a. widget triggered by appearance on any question type or any other widget. The DN widget could be shown next to (or underneath) the question widget.
b. use an iframe and postMessage

Essentially, I think the difference between a and b is that b allows for more separation between Enketo, and the DN functionality.

However, option a would seem to offer better possibility to visually integrate the form UI with the DN UI.

For both options, a and b, there is the issue of bypassing validation if a DN is present for a question. The solution discussed is to add logic to a custom enketo-core as follows:

if question value is invalid (required or constraint) 
   make async bypass call to DN web api and wait for response
   if response is true let enketo-core pass validation

**Comment by MartijnR** [comment]
API:

GET /dn (params: instance_id, question_path)
   response format:

POST /dn (params: instanceID, question_path)
  request format:
  response format: (the whole DN as returned by GET?)

question_path to include position if not 0, e.g. `/path/to/repeat[2]/node`

security: widget establishes secure communication with e.g. jwt query param?

**Comment by MartijnR** [comment]
Design:

?

Questions:
- small screen support required?
- grid theme support required? (this would probably be significantly harder, depending on design)

**Comment by MartijnR** [comment]
Current thinking is to implement a general note functionality (in Enketo-core): https://github.com/kobotoolbox/enketo-express/issues/478

Then create a complex custom widget for OC that parses their complex data model for DNs and shows the required UI.

**Comment by MartijnR** [comment]
If choosing option #4 for the [general comment feature](https://github.com/kobotoolbox/enketo-express/issues/478#issuecomment-212067949) (**Read that comment first!**), we could extend this as follows:

### XForm:
```xml
...
<instance id="myform">
    <data>
        <nodeA/>
        <nodeB/>
        <nodeC/>
        <!-- The group where comments are stored. Not required to be present, and the naming is free. -->
        <dns>
            <!-- This indicates to the client what the structure of a comment is. -->
            <!-- It is just a simple single node in this example. -->
            <!-- Node name(s) can be freely chosen. --> 
            <dn>
                <thread status="">
                      <note>
                           <value/>
                           <user/>
                      </note>
                </thread>
            </dn>
        </dns>
    </data>
</instance>
.....
<!-- This indicates to the client where to store comments of a particular type. -->
<!-- The presence of this binding could serve as the trigger for adding comment functionality to a form. -->
<bind nodeset="/dns/dn" type="oc:dn"/>
....
<h:body>
  <!-- nothing in the body, which is the weakness of this feature, the UI is "magical" -->
  <!-- This is why it remains a hack... -->
</h:body>
```

Clients that do not support this feature, should still be able to run the form (without showing the comment feature). 

### Submission:
```xml
<data>
   <!-- The comment attribute points to the comment. -->
   <nodeA oc:dn="/dns/dn[@id='abc']">value</nodeA>
   <nodeB oc:dn="/dns/dn[@id='bcd']">3</nodeB>
   <nodeC/>
      <dns>
        <dn id="abc">
                <thread status="open">
                      <note>
                           <value>this is a comment</value>
                           <user>johndoe</user>
                      </note>
                      <note>
                           <value>this is a another comment</value>
                           <user>janedoe</user>
                      </note>
                </thread>
          </dn>
         <dn id="bcd">
               <thread> 
                      ......
               </thread>
         </dn>
   </comments>
</data>
```

**Comment by MartijnR** [comment]
5th option. See [this basic version first](https://github.com/kobotoolbox/enketo-express/issues/478#issuecomment-212529007).

**Comment by MartijnR** [comment]
To check whether initial state of record changed:

1. create calculated item `/data/initial-data` for initial data nodes: `calculate="once(concat(/data/a, /data/b/, /data/c))"`
2. create calculated item `/data/initial-dn` for initial dn nodes: `calculate="once(concat(/data/a_dn, /data/b_dn, /data/c_dn))"`
3. create calculated item `/data/current-data` for current data nodes: `calculate="concat(/data/a, /data/b/, /data/c)"`
4. create calculated item `/data/current-dn` for current dn nodes: `calculate="concat(/data/a_dn, /data/b_dn, /data/c_dn)"`
5. create 'Reason for Change' question with: `required="/data/initial-data != /data/current-data and /data/initial-dn != /data/current-dn)`

**Comment by MartijnR** [comment]
* [ ] handle datachange event that will add an audit item
* [ ] figure out auto-resetting of comment field
* [ ] populate users list

**Comment by MartijnR** [comment]
Current users document expected (but can be easily adjusted):

```xml
<root>
    <item>
        <user_name>esummer</user_name>
        <first_name>Esther</first_name>
        <last_name>Summerson</last_name>
    </item>
    <item>
        <user_name>honoria</user_name>
        <first_name>Honoria</first_name>
        <last_name>Dedlock</last_name>
    </item>
</root>
```

In the XForm include a primary instance with id `users` is added that refers to this document e.g.:

```xml
<instance id="users" src="jr://file/users.xml"/>
```

(A CSV file is also an option, but I didn't elaborate on this, because XML is better).

**Comment by MartijnR** [comment]
https://groups.google.com/forum/#!topic/opendatakit-developers/SaNMPr9eSyQ

**Comment by jgosselin** [comment]
Is it possible to do the following:

- When the query widget opens, have the cursor appear in the comment text area by default?

- Hitting the enter key submits or updates the query. Note: Will still need to manually select 'Close'.

- Can a pointer be displayed on mouse over of the query icon? Similar to what you see when you go to click the 'Next', 'Submit', or 'Validate' button.

- By default, can the assignee list display the user that last performed any event (comment OR audit)? I think that it currently only captures the last user that submitted a comment, is this correct? If there are no events (comment or audit), then the assignee list will be blank by default (which it currently does do).

**Comment by jgosselin** [comment]
One additional request w/r/t required items:

The asterisk indicating an item is required should be down under both of the following scenarios:
 - If the item is conditionally required
- If the item is statically required (current behavior)

If the required column is blank for the item, the asterisk is not displayed (current behavior).

**Comment by MartijnR** [comment]
When implementing the Submit-upon-Enter functionality I realized that in the textarea (multiline) input, the Enter key creates a new line. So that means the new Submit/Update feature cannot be implemented in a textarea. 

If you're using a mix of both single-input and multiline inputs, you may not like this inconsistency.
