### ISSUE TITLE
Pages mode: navigation menu

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#300]
Validation upon 'Next' button click and swipe forward.

Some outstanding questions:
- still allow Go To End?

**Comment by tinok** [comment]
+1 for including constraint validation at this step as well. If a response is invalidated later on the user would still be prompted upon trying to submit to correct the input, but at least at the time of entering data the response would be considered valid with this approach. (This is how Collect handles it as well.)

**Comment by MartijnR** [comment]
See some ideas for UI improvements here: https://github.com/enketo/enketo-core/issues/326

**Comment by MartijnR** [comment]
ideas discussed with @tinok for ToC navigation:

* if page is group with label, show group label text, otherwise page number
* or, require form designer to explicitly add 'toc' (or similar) appearance to a group label (only) to explicitly add it to the navigation. No guesses by Enketo. Will not be compatible with ODK Collect (but not break it either).

**Comment by MartijnR** [comment]
replaced by #887
