### ISSUE TITLE
HTML5 number input changes value when scrolling while mouse over the element.

### ISSUE THREAD

**Issue by piqoni** [kobotoolbox/enketo-express#307]
In Chrome (Edge & Firefox 39.0.3 not an issue [at the moment]), scrolling while mouse is on top of an input element of type number will change its actual value (HTML5 feature).

In Enketo, this might have serious repercussions because the user scrolls the form quite often and might not notice that the value entered was actually changed.

**Comment by MartijnR** [comment]
Thanks. I agree. Remains to be seen whether this default number input behaviour can be overridden in a safe manner, though there is this:

http://stackoverflow.com/questions/9712295/disable-scrolling-on-input-type-number

**Comment by MartijnR** [comment]
looks like this was fixed in Chrome
