### ISSUE TITLE
Edit submission styling seems broken

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#310]
The styling for adding a new submission seems okay but when one tries to edit a submission, the styling of the submission CSS seems broken. I have tried this with 2 different forms and I have been able to replicate the problme. Checkout the screenshot below:
**Add submission page**
<img width="1280" alt="screen shot 2015-09-09 at 15 24 16" src="https://cloud.githubusercontent.com/assets/1128227/9761924/7f93511e-5708-11e5-909f-9edf750e9f97.png">

**Edit submission page**
<img width="1279" alt="screen shot 2015-09-09 at 15 24 25" src="https://cloud.githubusercontent.com/assets/1128227/9761931/904b21ee-5708-11e5-9ee3-16bb81dc3cea.png">

Are you experiencing the same?

**Comment by MartijnR** [comment]
Thanks Mark!

**Comment by MartijnR** [comment]
This one I cannot reproduce with the latest enketo express. I have seen it before though. It might be a different issue. It could be #312 (DOM messed up).

Something might be wrong when building stylesheets as well.

**Comment by MartijnR** [comment]
no, probably not related to stylesheet building

**Comment by MartijnR** [comment]
Reproduced on stage.ona.io and confirmed that issue #312 occurs in that case.

**Comment by ivermac** [comment]
Thanks, for confirming this. After deleting node_modules and running npm install and grunt again, the issue seems to be fixed.
