### ISSUE TITLE
allow for dynamic condition in 'required' field [5]

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/enketo-express#314]
A user should be able to specify a dynamic condition for a question's `required` setting, e.g. `${previousquestion} = '1'`. If it evaluates to true(), question is required. 

(already possible in Collect)

**Comment by MartijnR** [comment]
@tinok, not discussed recently but should probably be added to KoBoWork milestone right?

**Comment by MartijnR** [comment]
* [ ] figure out how to deal with required *, updating these dynamically might cause too much performance degradation

**Comment by tinok** [comment]
Yeah that would be great.

**Comment by MartijnR** [comment]
* [ ] fix failing browser tests in enketo-core
