### ISSUE TITLE
buttons and links focus

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#316]
for accessibility it needs to visible when the button/link has focus so a user can navigate with tabs keys to a button.

The current default browser outline is sometimes left in place, sometimes disabled. We need to make a consistent visually-distinct and nice-looking focus state for all buttons (including the icon-only buttons).

**Comment by MartijnR** [comment]
I think this is resolved. Check it.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#54
