### ISSUE TITLE
npm install causes server to be shunned

### ISSUE THREAD

**Issue by Jonathan727** [kobotoolbox/enketo-express#318]
I've been trying to build enketo expess on a production server I set up.

I'm using `bootstrap.sh` and I've discovered that something about running this script causes my server to be *shunned* (router blocks my mac address). Basically I can't communicate with the internet for 30 minutes or so after I run the setup script.

The router has a terrible interface and doesn't actually tell me why I was shunned.

The only other time I've ever been shunned is when I tried to download ubuntu with a bittorrent client.

By running the commands in `bootstrap.sh` one at a time, I've determined that `npm install` on line 60 is the cause.

What happens when I run `npm install` and why might a secure network not like it?

**Comment by MartijnR** [comment]
hmm. no idea. You are using node 0.10.x, right?

**Comment by MartijnR** [comment]
For a production server I wouldn't look at bootstrap.sh at all. Use http://blog.enketo.org/install-enketo-production-ubuntu/. It's a pretty well-tested tutorial now.

**Comment by MartijnR** [comment]
please re-open when necessary (if it has to do with Enketo Express)
