### ISSUE TITLE
Time lag in appearance of refresh form banner in Enketo Express

### ISSUE THREAD

**Issue by cagulas** [kobotoolbox/enketo-express#323]
In the new Enketo Express we have deployed, the appearance of the banner that alerts the user to refresh the form is seriously delayed.  Users are accustomed to seeing this within a few seconds of opening the form, but in this case, it was more like a few minutes after I opened the form.  If the user refreshes the page, they would lose any data they already entered.  I've been having to force a refresh by clearing my browser cache, which is a nuisance, as it logs me out of everything.

![screen shot 2015-09-11 at 11 38 17 am](https://cloud.githubusercontent.com/assets/3488986/9828911/e61674e6-58c2-11e5-8a02-dfc72e57e116.png)

**Comment by MartijnR** [comment]
Thanks! duplicate of #156

**Comment by cagulas** [comment]
Ok, Thanks.  Sorry I missed the other one.
