### ISSUE TITLE
Video in XForm in online-only view in Chrome not playing

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#326]
There are two repeatable issues with embedded video (MP4) in Enketo XForm:

Viewing video in mobile Chrome breaks the form. 

After trying, unsuccessfully, to play a video in my Enketo Form in mobile Chrome, I am no longer able to open it any other browser. The form seems stuck on the loading animation.

Video does not work in Chrome desktop.

A video player displays in Chrome Desktop for embedded video in Enketo. However, nothing is displayed when the user clicks play. Trying to play it in Desktop Chrome does not break the preview of the form in other browsers.

**Comment by jbonica** [comment]
Hi Martijn,
I'm following up to check if you've experienced issues with embedded movies in browsers other than Firefox. Thanks!

Jim B.

**Comment by MartijnR** [comment]
Thanks Jim, 

Sorry, I forgot to respond. I'm not aware of the issue. I will check if I can reproduce with an mp4 video.

**Comment by MartijnR** [comment]
Yes, am able to reproduce in online-only webform (works in offline-capable webform) in Chrome only (not FF) served by ODK Aggregate.

https://enke.to/::YYYh

**Comment by MartijnR** [comment]
Same file is downloaded 4 times in Chrome. Last 2 attempts result in 0 bytes. 
<img width="1207" alt="screen shot 2015-11-03 at 3 19 00 pm" src="https://cloud.githubusercontent.com/assets/627350/10923516/b2dd1008-823e-11e5-9082-badd820bc615.png">

**Comment by MartijnR** [comment]
http://codepen.io/MartijnR/pen/avjXvZ

**Comment by MartijnR** [comment]
@jbonica, it seems to have something to do with how the file is served. See the two `src` attributes in the codepens above. They serve the same file. When looking at the headers:

working:
```
content-disposition:inline; filename="enketoHQ.mp4"; filename*=UTF-8''enketoHQ.mp4
content-type:video/mp4
```

not working:
```
content-disposition:attachment; filename="enketoHQ.mp4"
content-type:video/mp4
```

My guess is that the `content-disposition: inline` makes it work. This would be outside of Enketo. Could you try this? Not sure if this breaks ODK Collect.

**Comment by MartijnR** [comment]
(Note that Ona and KoBoToolbox do not offer the ability to upload mp4 files at the moment.)
