### ISSUE TITLE
Refresh banner keeps appearing after refresh duration

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#339]
Hi, this is more of an inquiry than an issue. I know there is an [issue](https://github.com/kobotoolbox/enketo-express/issues/156) about making form updates propagate quicker in offline mode. I went ahead and tried to improve the speed loading speed by reducing the refresh time from 20 min to 30 seconds. [This is the line number I changed](https://github.com/kobotoolbox/enketo-express/blob/master/public/js/src/module/form-cache.js#L55). I tried this locally and it worked - the forms I used got updated after approximately 30sec. One thing I noticed is that the banner with the text ('A new version of this form...') kept appearing after every 30 seconds. I have a feeling it's got to do with [this section](https://github.com/kobotoolbox/enketo-express/blob/master/public/js/src/module/form-cache.js#L198-L214) but am not certain. Do you have any suggestions that I can try out to fix the banner issue? Thanks

**Comment by MartijnR** [comment]
I'm not sure. It could be a bug.

Is it related to changing the interval value?

If you run the survey with ?debug=true, do you see that debug message "Form has updated ...etc" ?

Do you notice anything weird about the hashes? Do they indeed keep changing to a new value?

Any error messages in the console? (e.g. not saving the updated form correctly in indexedDb).

**Comment by ivermac** [comment]
Yes it is related to changing the interval value. I hadn't run it with `?debug=true` so let me check that out

**Comment by ivermac** [comment]
So after using `?debug=true`, I noticed that the problem was difference in hashes. I kept getting
`
Cached survey is outdated! old: md5:7a0bccc96b6c296460c668ddb0b3e65b-null-feca12d975e37a828b3730d3e73d7398- new: md5:7a0bccc96b6c296460c668ddb0b3e65b-null-feca12d975e37a828b3730d3e73d7398-undefined
`
You'll notice the new hash value has a trailing `undefined`. The `theme` property in [this line](https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/transformation-controller.js#L199) is set to undefined. A fix that I have been using locally is the following just before assigning `survey.them` to the response theme property.
```javascript
if (typeof(survey.theme) === 'undefined') {
    survey.theme = '';
}
```

**Comment by MartijnR** [comment]
Yes! Glad you found this. I'll also have a look at where would be the best place to fix this.

It's quite interesting the interval has anything to do with this.

**Comment by MartijnR** [comment]
another related issue is that /transform/xform/hash seems to time out (for me)

**Comment by MartijnR** [comment]
removed my comment. false alarm

**Comment by MartijnR** [comment]
let me know if this didn't resolve it please

**Comment by ivermac** [comment]
Sorry I'm replying this a bit late. That seems to have fixed it, thanks!

**Comment by MartijnR** [comment]
Great. Thank you!
