### ISSUE TITLE
Max-size determination and storage algorithm to be hardened.

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#341]
Needs to check regularly for the max-size that is supported by the server, and especially if the maxSize value stored in indexedDb is `null` for any reason.

It might be good to not store the default size in the db (if this is done currently - it might not be).

Investigate why max-size retrieval often fails (or maybe for certain OpenRosa servers?)

**Comment by MartijnR** [comment]
Also check if HEAD request to /submission passes credentials (Enketo Legacy doesn't).

**Comment by MartijnR** [comment]
That bug is not present in Enketo Express

**Comment by MartijnR** [comment]
#370

**Comment by ukanga** [comment]
Is this related to `X-OpenRosa-Accept-Content-Length`? ODK Collect usually checks this and sends the submission with attachments in batches, each batch is of a size less than the specified content length. 
`X-OpenRosa-Accept-Content-Length` should be available in the head request of pretty much any OpenRosa FormSubmissionAPI.

**Comment by MartijnR** [comment]
Yes. Enketo checks this too.
On Jan 20, 2016 2:56 AM, "ukanga" <notifications@github.com> wrote:

> Is this related to X-OpenRosa-Accept-Content-Length? ODK Collect usually
> checks this and sends the submission with attachments in batches, each
> batch is of a size less than the specified content length.
> X-OpenRosa-Accept-Content-Length should be available in the head request
> of pretty much any OpenRosa FormSubmissionAPI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/341#issuecomment-173133576>
> .
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by ukanga** [comment]
Does enketo do the upload in batches?

**Comment by MartijnR** [comment]
Yes
On Jan 20, 2016 10:58 AM, "ukanga" <notifications@github.com> wrote:

> Does enketo do the upload in batches?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/341#issuecomment-173272761>
> .
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by MartijnR** [comment]
issues found:
- maxSize is stored in indexedDb, but nothing seems to be done with this -> remove from db
- the logic for previews to avoid requesting maxSize is weird and wrong -> make this smarter, e.g. determine `type` of view (if settings.type === 'preview')
- at least log an error to the console, if a response was received from Enketo server (= online) && Ona/KoBo did not include header or did not return a response.

**Comment by MartijnR** [comment]
The only 'bug' was the fact that under certain very rare circumstances the default max submission size gets stored in db and won't update until the form changes.

That rare circumstance is: the OpenRosa server does not serve the X-OpenRosa-Accept-Content-Length header (or does not return a response to HEAD /submission) at exactly the moment the form is cached (or re-cached).
