### ISSUE TITLE
Getting a loading error on IE 11

### ISSUE THREAD

**Issue by okal** [kobotoolbox/enketo-express#352]
*To reproduce*
- Open a webform in IE.
- Fill it and save as a draft.
- Open the draft from the sidebar.

*Message*

```
Loading Error

Error occured during the loading of this form. It is recommended not to edit this record until this is resolved.

Please contact supoprt@enketo.org with the link to this page and the error message below:
 Error trying to parse XML record. No such interface supported.
```

*Environment*

IE 11 on Windows 7 with Service Pack 1.
Webform URL: https://uibgw.enketo.org/webform

**Comment by MartijnR** [comment]
Thanks Okal,

This is not the Enketo app you are using. I moved it here: https://github.com/enketo/enketo-legacy/issues/341.

**Comment by MartijnR** [comment]
It also occurs in Enketo Express, but since the styling is completely broken in IE11 (and probably won't be fixed - before Microsoft gets most IE users to upgrade), I'm adding it here: #337
