### ISSUE TITLE
No cookies in pull csv request

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#364]
Hey, we have set `managed by enketo` to `false` and we are using an external url to set the auth cookie which works fine. The problem occurs when we try to retrieve a form with pull csv data and we get 401 on ona mainly because cookies are not part of that request. We believe [this bit](https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/media-controller.js#L25-L28) of code is responsible for retrieving the csv but headers are not set therefore cookies won't be available. Our fix was to add `headers: {'cookie': req.headers.cookie}` to be part of the options object param in `getUpdatedRequestOptions` function. Is this a valid fix? Thanks

**Comment by MartijnR** [comment]
Ah glad you found this! Seems like a good fix. Same as what's happening here it seems: https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/transformation-controller.js#L43-L46

Please send a PR.

**Comment by MartijnR** [comment]
If you'd rather I make the change that's fine too. I just wanted to not take credit for the fix.

**Comment by ivermac** [comment]
Cool, I have added PR - https://github.com/kobotoolbox/enketo-express/pull/365

**Comment by MartijnR** [comment]
@ivermac 

I'm just looking into the submission code for another issue and notice we don't add the cookie there either. 

From the way it looks, Ona's /submission API endpoint should **not** allow submissions if authentication is required. Does it? If so, it could be an Ona bug.

I'll add the cookie.

**Comment by ivermac** [comment]
@MartijnR 
An unauthenticated user cannot make submissions to Ona's /submission API endpoint if authentication is required.

**Comment by MartijnR** [comment]
Ok great. From the [code](https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/submission-controller.js#L62-L86) it seemed to me that authenticated users are also not able to do this with 'external authentication'.  But maybe cookies are passed after all.

**Comment by ivermac** [comment]
Aah I see what you mean. We have been using the submit button on the left toggle panel to make submissions. When you click that button, I believe [this code](https://github.com/kobotoolbox/enketo-express/blob/master/public/js/src/module/connection.js#L108-L120) is responsible for making the submissions from the client side and it adds the cookies.

**Comment by MartijnR** [comment]
That actually goes via the submission-controller (basically a proxy). I thought that I was overriding the headers there. However, I probably misunderstood. It seems the "request" library doesn't override the cookie. (I haven't checked myself).
