### ISSUE TITLE
Low memory error in Chrome for Android

### ISSUE THREAD

**Issue by okal** [kobotoolbox/enketo-express#373]
This happens when I attempt to upload an image.

Here's the webform in question: https://enketo.ona.io/_/#YUPW

**Comment by MartijnR** [comment]
Thanks for this. I'm hoping Ona can help figure this one out!

It's a basic Android device, I presume. How much RAM does it have?

**Comment by okal** [comment]
It's not particularly low end. It's a Samsung A3 with 1.5GB RAM.

**Comment by MartijnR** [comment]
Are you sure it is a low memory error? Are you by any chance seeing "Data is too large" instead?

**Comment by okal** [comment]
That's what it said, yeah.

![image](https://cloud.githubusercontent.com/assets/449209/11984740/fe0a8ecc-a9ce-11e5-947d-6be3d2763f04.png)


Perhaps it's a question of the image size? I took a full quality 8 MP image.

**Comment by MartijnR** [comment]
Ah that's too bad. (I tried to reproduce it and noticed Ona's enketo server responded with a 302 Data Too Large because of an NGINX setting - but that's something else).

I cannot reproduce (on a Nexus 5x) unfortunately.

**Comment by okal** [comment]
Odd. I'll have a closer look after the holidays. Can't give this the time it deserves now.

**Comment by MartijnR** [comment]
re-open when more more info
