### ISSUE TITLE
Not caching offline forms

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#377]
Happy new year @MartijnR. I hope all's well. I wanted to ask if offline form caching is working for you. We are getting the following error after we bookmark the url, disable internet and trying to access the url again.
<img width="1280" alt="screen shot 2016-01-04 at 17 34 55" src="https://cloud.githubusercontent.com/assets/1128227/12092061/e37e38ce-b30b-11e5-83d8-6635b404def5.png">

And we get the following for users with require auth set to true who try to access a bookmarked url when internet is disabled.
<img width="1278" alt="screen shot 2016-01-04 at 17 35 14" src="https://cloud.githubusercontent.com/assets/1128227/12092084/03c21704-b30c-11e5-8636-cc111209e752.png">

We are using tag 1.20.0 but I have also tested with the latest tag, which I believe should be 1.22.0, locally and I get the following.
<img width="1272" alt="screen shot 2016-01-04 at 17 30 54" src="https://cloud.githubusercontent.com/assets/1128227/12092148/677a816e-b30c-11e5-9da0-6cd7ea2fec38.png">

Any advice or ideas? Thanks

**Comment by MartijnR** [comment]
I can't seem to be able to reproduce this. Could you perhaps try https://enke.to/_/#YYYW? 

(credentials martijnr, martijnr)

This using the default authentication.

**Comment by ivermac** [comment]
https://enke.to/_/#YYYW works as expected. I think the problem might be on our side. Let me investigate further. Thanks again

**Comment by MartijnR** [comment]
Ok. I think for the 1st and 3rd screenshot situation to occur the applicationCache must not have populated for some reason.

If you discover a bug please re-open.

**Comment by ivermac** [comment]
You are right, applicationCache was not populating because of custom code I had added. The custom code is used to check if there was a new version of a survey after 1 second - intention is to solve [this](https://github.com/kobotoolbox/enketo-express/issues/156) issue. We opted for option **b** from what you suggested and i'll be making a PR hopefully before end of this week. Thanks
