### ISSUE TITLE
Editing problem - Namespace Incompatibility

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#384]
Hi @MartijnR , there's an interesting error I'm getting. There was a form I created a while back and I had 1 submission for it. I tried editing the submission today and I get the following error but when I add a new submission, I can edit the new submission without any problem. Have you ever encountered it or have any pointers on what I can do? Thanks
<img width="1280" alt="screen shot 2016-01-12 at 17 48 40" src="https://cloud.githubusercontent.com/assets/1128227/12266612/2424d2da-b955-11e5-92f2-9bdfe18aaa2a.png">

**Comment by MartijnR** [comment]
Interesting indeed! I think it may be an issue with the instance submitted for editing (or something with the XForm) but I have never seen this before. 

Can you also reproduce the issue by locally saving a draft record and then loading it for editing? 

If not, can you share both the XForm and an a complete problematic XML instance submitted for editing?

P.S. I probably won't be able to look at this before going on (a real) holiday, so it may take a while.

**Comment by ivermac** [comment]
The following is the xml of my instance.
```xml
<sample_accent id="sample_accent" instanceID="uuid:f0131f83-c5a1-4bfe-ae71-5b0fe84d7913" submissionDate="2015-08-31T11:40:20.948317+00:00" version="201508311137" xmlns="http://opendatakit.org/submissions">
    <formhub>
        <uuid>a28342834c9c47b3b1a458184eed3e26</uuid>
    </formhub>
    <words_with_accents>p&#232;re t&#233; t&#234;te</words_with_accents>
    <meta>
        <instanceID>uuid:f0131f83-c5a1-4bfe-ae71-5b0fe84d7913</instanceID>
    </meta>
</sample_accent>
```
Removing the `xmlns="http://opendatakit.org/submissions` attribute in `sample_accent` tag seems to fix the problem. Was there anything that changed in enketo on how to handle instance xml sometime back?
Also, don't worry too much enjoy your holiday :-)

**Comment by MartijnR** [comment]
Aha! No, nothing was changed in Enketo in this respect. I think it may have been a change in ODK Collect to add this namespace. In my opinion it is actually not correct because I think the model in the XForm should have the same namespace as the submission. We will need to clarify this with them (:sigh:).

**Comment by MartijnR** [comment]
However, any default namespace (even if it was the correct one) in the instance would probably fail in Enketo. Fix should not be too hard. https://github.com/enketo/enketo-core/issues/354

**Comment by MartijnR** [comment]
Glad you found this. I think it's fixed in latest master. However, note that the latest master is not stable. I think there is a regression caused by a jquery update. https://github.com/kobotoolbox/enketo-express/issues/388

**Comment by ivermac** [comment]
cool, thanks
