### ISSUE TITLE
check if submission parameter can be passed to offline-capable view

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#386]
and returned in submission.

Will appCache still work properly across browsers?

**Comment by MartijnR** [comment]
In chrome on OSX: every time that the querystring changes (e.g. just the value) the page, and all its resources are obtained from the network, not the applicationCache. A subsequent load does load everything from the cache.

**Comment by MartijnR** [comment]
This is actually rather interesting. Since master entries (the landing page) are cached implicitly, Chrome stores a copy of each master page with a particular querystring in the applicationCache. If this is done consistently, it may not be necessary to avoid querystrings in offline-capable webforms.

<img width="539" alt="screen shot 2016-02-03 at 2 46 02 pm" src="https://cloud.githubusercontent.com/assets/627350/12798152/1b1773c8-ca85-11e5-85ff-4e520b7f3863.png">

**Comment by MartijnR** [comment]
Considering the problem in Edge, this approach should probably be abandoned. I haven't check the other outstanding questions for that reason.

Scenario:

User has several **cached** forms e.g. (different forms and/or different query parameters):
1. enketo.oc.com/_/?ocid=a#abcd
2. enketo.oc.com/_/?ocid=b#abcd
3. enketo.oc.com/_/?ocid=1#ffff
4. enketo.oc.com/_/?ocid=2#aaa

Just before going out in the wild offline world, the user has form #1 open in the browser and receives an updated version of the app. The user does not the open the other 3 forms it has cached, because why would she/he? They have already been cached.

When in the offline word the user finds out that only form #1 is available offline because the cache update for form #1 has busted the cache entries for the other 3 forms (in Edge).

**Comment by MartijnR** [comment]
Can the same user get a different id for the same form or for different forms?

If so, it looks like there is no good way to pass the value to an offline-capable form. (It would become possible after switching from applicationCache to service workers (#401), but it's too early for that.

The only hack I can think of would be to add the parameter to the fragment identifier in the url :-1: :

https://enketo.oc.com/_/#abcd-someid

**Comment by MartijnR** [comment]
@pld @ivermac Just FYI, I noticed you're using a query string for the **iframed** offline-capable webform. You may run the risk of breaking the regular offline-capable webform, at least in IE. Solution could be to use a regular online-only webform in your iframe page (seems better for UI reasons too, because the parentWindow is not offline-capable).

**Comment by pld** [comment]
Thanks Martijn, we've noticed this before and are in there process of QAing
a change to remove the iframe.

**Comment by MartijnR** [comment]
to discuss with OC:

1. `oc.enketo.org/_/?ecid=abc#1234`
2. store ecid, redirect to `oc.enketo.org/_/#1234`
3. ecid value stored **can only be overwritten, not emptied (except by visiting `oc.enketo.org/_/?ecid=#1234`)

**Comment by MartijnR** [comment]
* [ ] store value 
* [ ] explicitly add /_/ to manifest?
* [ ] history.replaceState
