### ISSUE TITLE
sass:compile file to import not found or unreadable bootstrap-datepicker

### ISSUE THREAD

**Issue by maelfosso** [kobotoolbox/enketo-express#391]
Hi everybody,

Please I have an error when typing `grunt` command
```
Running "sass:compile" (sass) task
>> File to import not found or unreadable: ../../../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker
>> Parent style sheet: /home/maelfosso/www/enketo-express-old/node_modules/enketo-core/src/widget/date/datepicker-extended.scss
>>   Line 1  Column 1  node_modules/enketo-core/src/widget/date/datepicker-extended.scss
Warning:  Use --force to continue.

Aborted due to warnings.


Execution Time (2016-01-18 11:38:20 UTC)
loading tasks   8.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 96%
sass:compile   378ms  ▇▇▇▇▇▇▇▇ 4%
Total 9.3s
```
Because of this error, the form is like without css file. Enketo display the form without any design.
How to solve it please ?
Thanks.

**Comment by MartijnR** [comment]
Thanks. Will check in February when back from holiday. If npm version is
3.x.x, downgrade npm to 2.x.x. Trying latest published enketo version will
probably solve your issue.
On Jan 18, 2016 6:32 AM, "Mael Elvis FOSSO" <notifications@github.com>
wrote:

> Hi everybody,
>
> Please I have an error when typing grunt command
>
> Running "sass:compile" (sass) task
> >> File to import not found or unreadable: ///node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker
> >> Parent style sheet: /home/maelfosso/www/enketo-express-old/node_modules/enketo-core/src/widget/date/datepicker-extendedscss
> >>   Line 1  Column 1  node_modules/enketo-core/src/widget/date/datepicker-extendedscss
> Warning:  Use --force to continue
>
> Aborted due to warnings
>
>
> Execution Time (2016-01-18 11:38:20 UTC)
> loading tasks   89s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 96%
> sass:compile   378ms  ▇▇▇▇▇▇▇▇ 4%
> Total 93s
>
> Because of this error, the form is like without css file Enketo display
> the form without any design
> How to solve it please ?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/391>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by MartijnR** [comment]
I cannot reproduce this issue. I think you need to re-run `npm install`. It is recommend to first remove the `node_modules` folder.
