### ISSUE TITLE
Error when loading webform

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#392]
The screenshot below shows an error that one of our users got when he tried to open an enketo link using an iphone but I'm not sure which browser he was using. Has anyone experienced this before?
![error-msg](https://cloud.githubusercontent.com/assets/1128227/12606045/4a2dbc8a-c4db-11e5-81c7-deea2e047603.png)

**Comment by MartijnR** [comment]
I've seen it temporarily during development with file input fields, but that was resolved before pushing the commit that caused this.

Can you find out more, so we can reproduce it?

**Comment by MartijnR** [comment]
Will re-open when we can reproduce. If it is specific to an old iOS version, we should try to detect the missing feature for a more helpful error message.
