### ISSUE TITLE
iOS safari crashes on photo input

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#398]
Reported by iofteam (experienced on enke.to):

> The iPhone 4s  Safari Browser is crashing when pictures are “accepted” , Safari says “ an error occurred on this page and will now close”

Check if this can be reproduced in iPad/iPod touch with latest iOS.

**Comment by MartijnR** [comment]
Have not been able to reproduce a crash or error message but am seeing that Safari on iPod touch won't save a record with 3 9Mb photos.

**Comment by MartijnR** [comment]
Another (related?) report by OpenClinica says the page refreshes sometimes when trying to input a photo, but not reproducable so far.

**Comment by MartijnR** [comment]
OC sent video demonstrating. Likely iOS/hardware spec issue. Try creating a form in pages mode and adding tons of photos to reproduce.

**Comment by MartijnR** [comment]
iOS device storage space could also be an issue (seems far-fetched)

**Comment by MartijnR** [comment]
I am getting 'An unknown error occurred when trying to save data' with multiple (7) photos in one record on iPod touch.

**Comment by MartijnR** [comment]
I am getting  a browser crash when a submission finished while adding a new record on iPod. I wonder if two database operations (one to remove a record, the other to save the autoSave record) were conflicting.

**Comment by MartijnR** [comment]
Tomorrow, disable autoSave on dev server. See if issue still occurs.

Once it start occurring, it becomes unusable until Safari shutdown and re-launched.

**Comment by MartijnR** [comment]
autoSave is called twice whenever file input changes. Enketo-core sends valuechange.enketo twice on input type=file element

**Comment by MartijnR** [comment]
FileReader error seems to occur when multiple files are converted to data uri's

**Comment by MartijnR** [comment]
current state deployed here: http://enk.to/::YYY1

**Comment by MartijnR** [comment]
Images missing from submissions (in Ona at least - sent with iPod touch - no exceptions). Check console

**Comment by MartijnR** [comment]
Re fileReader issue:

The data URI is generated successfully to create the preview, but then fails for the same fail when done for the storage (because iOS doesn't support storen blobs in IndexedDb). Very odd.

**Comment by MartijnR** [comment]
Still to investigate. Missing photo files in Ona export. Check if they are sent by Enketo.

**Comment by MartijnR** [comment]
The missing file issue is an Enketo bug: #431

**Comment by MartijnR** [comment]
Closing this until we can reproduce crashes again.

**Comment by zspitzer** [comment]
FYI: I have filed a bug against webkit for this problem https://bugs.webkit.org/show_bug.cgi?id=172533

**Comment by MartijnR** [comment]
Thanks!
