### ISSUE TITLE
Switch from applicationCache to service workers

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#401]
applicationCache is being deprecated

https://html.spec.whatwg.org/multipage/browsers.html#offline

Too early at the moment. http://caniuse.com/#feat=serviceworkers

**Comment by MartijnR** [comment]
to fix afterwards:

* [ ] remove awkward method of passing submission parameter to offline view

**Comment by MartijnR** [comment]
First thing to check is the 24 hour thing, as we need users to be able to stay disconnected for much longer.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#55
