### ISSUE TITLE
Preloading data via the API.

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#406]
Hi @MartijnR , I'm meant to understand that a user can preload form fields by adding query params to enketo urls. Is there documentation showing how this is done? Thanks

**Comment by MartijnR** [comment]
Yes, sort of, although don't try to craft the URLs yourself, but **use the API** (v2). This way you're protected when the URL format changes: https://github.com/kobotoolbox/enketo-express/blob/master/doc/APIv2.md#defaults

**Comment by ivermac** [comment]
Thanks

**Comment by MartijnR** [comment]
Let me know if you have questions or comments. It's by far the most powerful unused feature in Enketo. Unfortunately, not possible (nor enabled) in offline capable views though. We could do this after #401.

**Comment by ivermac** [comment]
Sorry I'm responding to this late. I think it does work for both online and offline capable forms, check the following links out:
```
https://enketo.ona.io/_/?d[/sample_fr/father]=father&d[/sample_fr/tea]=tea&d[/sample_fr/head]=head#YyQA
```
and
```
https://enketo.ona.io/::YyQA?d[/sample_fr/father]=father&d[/sample_fr/tea]=tea&d[/sample_fr/head]=head
```

**Comment by MartijnR** [comment]
Ah thanks. Didn't realize it was enabled. Yes it works, but it will mess up the applicationCache, potentially causing people to go the field and realizing their form is not available for offline launch. See #386. We shouldn't use any query parameters on offline-capable webforms at all, and should probably actively disable this functionality.

**Comment by MartijnR** [comment]
I am working (this week) on an alternative way to pass dynamic data to an offline-capable webform via setting a cookie and redirecting. Maybe we can use that for this feature as well (that's what I hope).

**Comment by MartijnR** [comment]
Ah! You handcrafted the URL. In that case no need to actively disable it, since we expect users to use the API.

**Comment by ivermac** [comment]
Yes, I did handcraft the URL :blush:
