### ISSUE TITLE
Multiple people editing same instance

### ISSUE THREAD

**Issue by smusula** [kobotoolbox/enketo-express#416]
Previously if one attempted to open and already opened record for editing an error message appeared that didn't allow the second user to open the same record. I've tested and there seems to be no warning/notification when another user is editing a record. Should two people be able to open the same record and edit it via Enketo?

**Comment by MartijnR** [comment]
Ah. Thanks. In the old app, the protection wasn't very strong either (I think it was blocked for 1 minute only, so after a minute a 2nd person was able to open it, I think). Now, it should be set to 30 seconds.

I'll check if that is broken.

**Comment by MartijnR** [comment]
@smumsula,

I think there is no other difference between Enketo Legacy and Enketo Express. Both have only weak protection.

Both:
- edit urls are only valid for a limited time (EE: 30 seconds, EL: 60 seconds)
- do not allow other users to obtain an edit url for the same record for this 30/60 second period by clicking the Edit button

To properly secure this, would be a lot of effort and I'm not sure if it's worth it. Ideally, we'd have some kind of locking mechanism implemented on the Ona/KoBo side (that disables the Edit button). The difficulty will be to determine when to unlock a record, e.g. what if the user still hasn't submitted a replacement in 1 hour, 2 hours, etc?

I'll close this for now, but we may want to re-open this at some point. Also, if you do notice another difference between EL and EE, let me know as that would likely be a bug.
