### ISSUE TITLE
Can't generate enketo url when redis not in same server as enketo

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#417]
Hi @MartijnR , so we are testing out AWS elastic cache (using redis) with enketo express and we are getting the following error when we try to generate an enketo url - response of a curl request

``` json
{
    "code": 500,
    "message": "EXECABORT Transaction discarded because of previous errors."
}
```

I used `redis-cli`'s `monitor` option to monitor what happens when we try to generate a url and the following was the output

```
ubuntu@ip-172-31-15-212:~$ redis-cli -h <elastic-cache-url> monitor
OK

1455801780.197436 [0 172.31.15.212:54565] "keys" "or:[/,]*"
1455801780.199017 [0 172.31.15.212:54565] "get" "or:stage-api.ona.io/ivermac,monthly_project_report"
1455801780.200072 [0 172.31.15.212:54565] "get" "or:stage-api.ona.io/ivermac,monthly_project_report"
1455801780.201084 [0 172.31.15.212:54565] "incr" "survey:counter"
1455801780.202197 [0 172.31.15.212:54565] "multi"
1455801780.202212 [0 172.31.15.212:54565] "exec"
1455801780.213035 [0 172.31.15.212:54565] "keys" "or:[/,]*"
1455801780.214722 [0 172.31.15.212:54565] "get" "or:stage-api.ona.io/ivermac,monthly_project_report"
1455801780.215777 [0 172.31.15.212:54565] "get" "or:stage-api.ona.io/ivermac,monthly_project_report"
1455801780.216886 [0 172.31.15.212:54565] "incr" "survey:counter"
1455801780.218110 [0 172.31.15.212:54565] "multi"
1455801780.218124 [0 172.31.15.212:54565] "exec"
```

I tried to replicate this locally by starting a [vagrant instance with redis](https://github.com/72squared/vagrant-redis-cluster) and connected it to my local enketo express instance and tried to create an enketo url and the following is the error - sorry the `stack` value is not well formatted:

``` json
{
    "code": 500,
    "message": "MOVED 7339 127.0.0.1:7001",
    "stack": "Error: MOVED 7339 127.0.0.1:7001\n    at JavascriptReplyParser._parseResult (/Users/ekisa/ona/repos/enketo-express/node_modules/redis/lib/parsers/javascript.js:43:16)\n    at JavascriptReplyParser.try_parsing (/Users/ekisa/ona/repos/enketo-express/node_modules/redis/lib/parsers/javascript.js:114:21)\n    at JavascriptReplyParser.run (/Users/ekisa/ona/repos/enketo-express/node_modules/redis/lib/parsers/javascript.js:126:22)\n    at JavascriptReplyParser.execute (/Users/ekisa/ona/repos/enketo-express/node_modules/redis/lib/parsers/javascript.js:107:10)\n    at Socket.<anonymous> (/Users/ekisa/ona/repos/enketo-express/node_modules/redis/index.js:131:27)\n    at Socket.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:765:14)\n    at Socket.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:427:10)\n    at emitReadable (_stream_readable.js:423:5)"
}
```

_NB_: I was using the command line to generate the enketo url and the format of my commandline was
`http -a <enketo-api-token>: POST "<enketo-server-url>?server_url=<local-ona-server>&form_id=<form-id>"`

Have you experienced such an error before when you connected enketo with redis instance that's not in the same server as enketo? Any idea what I might be doing wrong?

**Comment by MartijnR** [comment]
Interesting! No, I have never tried using an external redis server. I assumed it would just work, but alas.

I see quite a few 'redis MOVED error issues' on the web, but don't see an immediate culprit.

**Comment by ivermac** [comment]
I'll try to do more research on what the problem might be

**Comment by MartijnR** [comment]
Let us know if you find out more please.

**Comment by ivermac** [comment]
Apologies I haven't given feedback to this because I have been working on something different. I'll try to do more investigations tomorrow

**Comment by ivermac** [comment]
Hi @MartijnR so I did more research on the issue. [Here is a link to code](http://paste.ofcode.org/FVXE3XK8bUJAcFZRybmtWP) based on `_addSurvey` function in `survey-model-js` file where the error seems to be triggered. I created a file with the code in that link which when I run `node <filename>.js` on our staging server when the `host` variable in line 2 is `127.0.0.1` I get a success response with an id but when I changed the the `host` variable to the elastic cache url an error is triggered as seen on the following screenshot
![image](https://cloud.githubusercontent.com/assets/1128227/13371659/b8618852-dd3c-11e5-99bf-7d136da7f24b.png)
I read about `multi` in [node redis package](https://github.com/NodeRedis/node_redis#user-content-multiexeccallback) and it says that `EXECABORT` is triggered when the code contains errors but I think that would mean I wouldn't have been successful even with the local redis instance. 

I created an [extra file](http://paste.ofcode.org/FgWM8J3AK5WnabUdhMRjgZ) locally to test it with the 
[vagrant redis instance](https://github.com/72squared/vagrant-redis-cluster) I mentioned earlier and the results were not different: it worked with my local redis instance but didn't with the redis instance in vagrant. The first run is with the vagrant redis instance and the next run is with the local redis instance.
<img width="927" alt="screen shot 2016-02-27 at 11 12 14" src="https://cloud.githubusercontent.com/assets/1128227/13372015/db6fe1c2-dd46-11e5-98d6-f0fa6fa05b02.png">

**NB: ** I was using `v4.0.0`

**Comment by MartijnR** [comment]
Thanks! So node_redis multi, possibly in conjunction with redis 4.0.0, has an issue with an external redis instance (local external + elastic cache external). 

I see redis 4.0.0 is not considered stable. No issues on node_redis repo. Have you tried redis 3.x.x perhaps?

**Comment by ivermac** [comment]
Sorry, I meant node version 4.0.0

**Comment by MartijnR** [comment]
ah of course! :)

On Mon, Feb 29, 2016 at 10:58 AM, Mark Ekisa <notifications@github.com>
wrote:

> Sorry, I meant node version 4.0.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kobotoolbox/enketo-express/issues/417#issuecomment-190310820>
> .
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by esmail** [comment]
FYI, the [Docker setup](https://github.com/kobotoolbox/enketo-express/tree/docker#using-docker) operates as if Redis is on another host; not sure if this is helpful or not.

**Comment by MartijnR** [comment]
Ah thanks @esmail. And this is how you're putting Enketo Express through its paces on staging?

**Comment by esmail** [comment]
Yup. Essentially what happens is Docker Compose edits the `/etc/hosts` file in the Enketo container so references to the [`redis_main`](https://github.com/kobotoolbox/enketo-express/blob/docker/setup/docker/envfile.txt#L8) and [`redis_cache`](https://github.com/kobotoolbox/enketo-express/blob/docker/setup/docker/envfile.txt#L11) host names are redirected to the corresponding Redis container.

**Comment by MartijnR** [comment]
If this needs work on Enketo side, please re-open @ivermac .
