### ISSUE TITLE
change logo

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#446]
I changed logo but it never get visible

 "source": "/images/wfp_logo_dark.png",

plz help

**Comment by MartijnR** [comment]
I just checked and it's not broken. Just to be sure:

1. add wfp_logo_dark.png image to public/images
2. add to config/config.json:

```
"logo": {
        "source": "/images/wfp_logo_dark.png",
        "href": ""
    }
```

Did you test it with an online-only form? e.g. http://localhost:8005/::widgets. In an offline-capable form it will take longer for the logo to show unless you clear the manifest cache in redis.
