### ISSUE TITLE
How to update enketo with same form_id

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#450]
Hi Martin,

How to update enketo for same form with same form ID.

Regards,
Imran Ahmedani

**Comment by MartijnR** [comment]
Hi Imran,

That happens automatically, when the form is updated on the server (e.g. KoBoCAT or ODK Aggregate).

If you are using a recent version of Enketo Express, it should happen quite quickly (a few minutes max).

Let us know if there is a bug.
