### ISSUE TITLE
Support for layer switching widget

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#453]
According to [this article](http://blog.enketo.org/geo-layers/) in enketo's blog, a user can be able to switch between streets, terrain and satellite maps. The following screen shot does not show the layer switch widget when a user loads the webform on our instance of enketo express.
![screenshot_032316_103515_am](https://cloud.githubusercontent.com/assets/1128227/13978607/831961be-f0e3-11e5-94ca-c740836fc83c.jpg)

Is this feature supported by enketo express? Also on the [sample form](https://geo.enketo.org/webform), it seems to be supported but I'm not sure if that is enketo express or enketo legacy.

**Comment by MartijnR** [comment]
Hi Mark,

Yes, definitely supported on Enketo Express (this is my Enketo Express production server: https://enke.to/::widgets).

See documentation here: https://github.com/kobotoolbox/enketo-express/blob/master/config/README.md#maps

I recommend at least using names `streets`, `satellite` and `terrain`. This will make forms more portable, as users will be able to define the default map layer in the form (by name).

(P.S. was also reported here: https://groups.google.com/forum/#!topic/enketo-users/oK9zbYvFFSM. I was wonder why Ona wasn't using multiple layers.)

**Comment by ivermac** [comment]
Thanks. I will give a try when I get back to the office

**Comment by ivermac** [comment]
Hi @MartijnR, we were able to add `street`, `satellite` and `terrain` layers

**Comment by MartijnR** [comment]
great!
