### ISSUE TITLE
Other way to install redis

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#458]
Hi martin,

Is there any other way to get same package for redis as I'm trying to get via "sudo add-apt-repository -y ppa:rwky/redis" I'm getting error. 

Please advice.

**Comment by MartijnR** [comment]
Ah thanks.

I think this is the new way: `sudo add-apt-repository -y ppa:chris-lea/redis-server`

Let me if it doesn't work. I'll update the guidance.

**Comment by MartijnR** [comment]
Actually I'm not getting this error with ppa:rwky/redis (and using chris-lea/redis-server means changing some other things in the installation process).

I think it was maybe just a temporary problem with the ppa?
