### ISSUE TITLE
how to enable single use 

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#465]
hi martin,

can you help me or advise how to get form for single use, I tried url but not working.

https://mysite.xxx/single/::abw3e325tt2gdsgsfd

**Comment by MartijnR** [comment]
The feature doesn't exist yet unfortunately. I'm looking for a bit of funding for it. Hopefully soon. It's not much work.

You can track it here: https://github.com/kobotoolbox/enketo-express/issues/97

P.S. never try to craft URLs yourself. It will cause headaches when Enketo changes the URL structure (which can happen at any time). Always use the Enketo API to get the URL. Currently the /survey/single API endpoint should give a 405 response, I think.

**Comment by MartijnR** [comment]
The feature is in latest (unreleased) master if you are still interested. 

Use this API endpoint and experiment with the new `allow_multiple` parameter.
