### ISSUE TITLE
Encoding of formID send by Aggregate

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#473]
FormID: "Linnunpöntöt"

Aggregate sends: "Linnunp\xef\xbf\xbdnt\xef\xbf\xbdt"
When sending via bash:         "Linnunp\xc3\xb6nt\xc3\xb6t" (UTF-8)

This causes Enketo to fail to find the Aggregate-launched formID in the /formList.

**Comment by MartijnR** [comment]
UTF-8: https://mothereff.in/utf-8

**Comment by MartijnR** [comment]
I don't think this is worth spending much more time on. UTF-8 encoded strings work as form IDs in Enketo. That's all that matters I think.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#35
