### ISSUE TITLE
Make the possibility to chain multiple forms data entry with returnUrl parameter

### ISSUE THREAD

**Issue by toskrip** [kobotoolbox/enketo-express#476]
It would be very useful if I could chain the data entry for multiple form by using returnUrl query string pointing to next form URL with its own returnUrl query string ...etc ...until the last form with returnUrl pointing to any page.

I thought that it would work already but the current behaviour is that Enketo opens the first form and after submission redirect to the last returnUrl parameter from the big chained URL.

E.g. for this case where I have two chained forms (see the URL below) after the first form is submitted, the second is ignored and redirection goes to the last returnUrl query string (`http://localhost:8080/participate/home.faces`)

The correct behaviour in my opinion would be find to first returnUrl parameter and take everything that follows as parameter value.

this should work for both, new data entry forms as well as editable forms.

Chained long URL example:
`http://localhost:9005/edit/i/::YYYh?instance_id=660d3ff0298d147e87789da7f4911f9470d5542e5378260d06614087bfdb0ba2&ecid=069c4b0d5e1e9b5cd3c85d7a41d8bc5e2dbfc0095e676a43405e91af6968df35&returnUrl=http://localhost:9005/edit/i/::YYYQ?instance_id=1f9b39bed4fcf08d4632e625c288fcdf24054113d0a2156788698a70600da00f&ecid=2b8c4d98173bce6acd90b9d34b3ac2ee62f8f21b8442505931658378de2c523b&returnUrl=http://localhost:8080/participate/home.faces`

**Comment by MartijnR** [comment]
Very interesting idea! I hadn't thought about this before, but yes, it works already.

You'll just have encode the returnUrl.

E.g. https://enke.to/::YYY8?returnUrl=https%3A%2F%2Fenke.to%2F%3A%3AYYYh%3FreturnUrl%3Dhttps%3A%2F%2Fgoogle.com contains a chain of 3 pages.

**Comment by toskrip** [comment]
Ohh great, thanks this will do it. I am closing the ticket.

**Comment by toskrip** [comment]
Re-opening this ticket, because I hit one issue with this approach. The proposed solution only works when linking two forms and final redirect to external page. However if I have three or more it redirects only to the second and then it get stucked with submission (URL encoding problem).

First the URL looks like:
https://enke.to:9005/::YYYX?iframe=true&ecid=123&returnUrl=https%3A%2F%2Fenke.to%3A9005%2F%3A%3AYYYD%3Fiframe%3Dtrue%26ecid%3D321%26returnUrl%3Dhttps%3A%2F%2Fenke.to%3A9005%2F%3A%3AYYYn%3Fiframe%3Dtrue%26ecid%3D231%26returnUrl%3Dhttps%3A%2F%2Fgoogle.com

After first redirect loads the second but whole following redirection path is already decoded:
https://enke.to:9005/::YYYD?iframe=true&ecid=321&returnUrl=https://enke.to9005/::YYYn?iframe=true&ecid=231&returnUrl=https://google.com

Which cannot be submitted. Is there any possibility that we can preserve the encoding of query parameters after redirect so that the URL stored in returnUrl query string stays in encoded form?

**Comment by MartijnR** [comment]
Hi Thomas!

Ah I see how this could be a problem. I think it should be fixable. Let me have a look hopefully within a week. Please don't hesitate to remind me if you're not seeing any update.

Btw, this is not related to your issue but the latest Enketo is more strictly enforcing Enketo's API. ReturnUrl only works on special single submission webforms now. (All the URLs returned by an API endpoint with 'single/', see https://apidocs.enketo.org/v2). This means you'd have to use slightly different webform URLs (get them from /survey/single/iframe probably).

**Comment by toskrip** [comment]
Hi Martijn

maybe we can close it again. I was doing a bit more testing and when I encode the % control character in returnUrl as many times as redirection, then it works fine.

e.g.
1. form...&returnUrl=
2. form (control characters encoded with % control character e.g. ":"encoded as %3A)&returnUrl=
3. form (all "%" control characters encoded one more time e.g. "%3A" encoded as %253A)&returnUrl=
4. form (again all "% control characters encoded one more time e.g. "&253A" encoded as "%25253A")...etc

when the initial big url is prepared prepared like this, it works without problems.

**Comment by MartijnR** [comment]
Ah great! Yes, that makes sense. I mistakenly thought you double encoding wasn't possible. Thanks.
