### ISSUE TITLE
change Enketo ID generation [2]

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#481]
Sequential is not great (despite some lame obfuscation). **It allows people to guess, or mistype and see another form (quite a surprise if the diff is only in capitalization).** It was chosen to give us the shortest possible URLs, but that shouldn't have been such a heavy requirement in hindsight.

Options to solve:
1. Use random IDs (more characters)
2. Add `enketo_id` parameter to launch API call (that would change quite a lot in the API, but without loosing backwards compatibility). A "vanity" URL is something that is requested fairly frequently by users.

Existing forms will keep working of course.

**Comment by MartijnR** [comment]
for option 1, 8 digits is a good start that will keep Enketo running smoothly until a single Enketo server reaches SurveyMonkey-like scale (i.e. it keeps the chance of collisions below about 10% until about 10,000,000 IDs have been generated, as calculated by all-round wizard @esmail ).

When necessary, a 9th character can be added.

**Comment by MartijnR** [comment]
An additional reason to implement this issue is that if the database gets lost (catastrophic failure, as happened in testing with a heroku-redis upgrade https://github.com/kobotoolbox/enketo-express/issues/519, but **where Enketo will just keep running**). Earlier enketoIDs will start to be created for new forms. You could get people submitting data to the wrong form and just make a bad thing  much much worse.

random IDs would not make this issue worse and you can recover by merging a backup database.

**Comment by MartijnR** [comment]
Instead of 
> it checks our server for the anDvQbCV
implementing 2 from the OP would be much easier (i.e. the vanity URL feature). It avoids requiring a tight coupling with a KoBo feature. What do you think about doing it like that?

**Comment by dorey** [comment]
I think that could work and have the same effect; except

1. we might end up initializing more enketo forms than users access
2. in the (hopefully rare) case of data loss and/or servers somehow getting out of sync, we would have to cycle through the IDs and confirm the existence of each form.
3. ✨ I hope we come up with a name for it that doesn't have 'vanity' in it ✨🌟

**Comment by MartijnR** [comment]
1. This ✨VANITY✨ feature would be part of the launch API call. So no need to communicate with Enketo until requested by the user for the webform. 
2. As long as KoBo retains the IDs we should be good. The enketo_id parameter could be provided in all the API calls (but will be ignored if an entry for this form already exists). A cool side-effect is that if Enketo completely loses its database, it could be re-built by webform button clicks in KoBo (or programmatically by KoBo). But yeah, the other way around (if KoBo looses the IDs), would be a pain. Everything would work but all existing forms would have different IDs in KoBo and Enketo (though not break anything).
3. Haha, good point. Btw, it has been requested often to let the users define a ID themselves, so a nice additional feature you could expose at a later stage.

**Comment by MartijnR** [comment]
* [ ] bug with Parma’s
* [ ] add status code test for failing to generate unused id

**Comment by MartijnR** [comment]
* [ ] check encrypted IDs (single-submission)
