### ISSUE TITLE
Availability of import functionality

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#483]
Hi @MartijnR  This is more of a question than an issue. Is there a way to import instances which a user has exported using the export functionality on the browser? A scenario would be there is problem with browser A so a user would like to try to browser B to submit data that was already exported.

**Comment by MartijnR** [comment]
Hi Mark,

No that's not possible. KoBo concluded that it's not really useful enough (and quite complex to develop properly). In the announcement, I'm referring to using other tools to import straight into Ona/KoBo/Aggregate: http://blog.enketo.org/better-exports/.

For your use case, one would need it, but I think I'd prioritize fixing the issue they are having if they were using a modern browser. 

Still, I would have some interest in adding imports to Enketo and it's still on the [roadmap](http://blog.enketo.org/enketo-roadmap/). If this is important to Ona, I'd be open to doing this with Ona's sponsorship. It's going to be quite expensive though. PR also welcome. For both we should first discuss requirements, and tests, in detail.

**Comment by ivermac** [comment]
Hi Martijn,

Thanks for the feedback and for the blog link, I hadn't read it. @ukanga has also read your response and I think he will be in a better position to make a decision of what can be done next.

**Comment by MartijnR** [comment]
Look into making the export format compatible with ODK Briefcase (it may already be, I don't remember).

**Comment by ivermac** [comment]
Cool, thanks for the heads up!

**Comment by MartijnR** [comment]
You're welcome. :) It is meant for any developer wanting to take this on.

**Comment by MartijnR** [comment]
It turns out to be very easy to make it compatible with Briefcase. Will be done as part of https://github.com/kobotoolbox/enketo-express/issues/298

**Comment by ivermac** [comment]
Wow, that's cool! Thanks @MartijnR
