### ISSUE TITLE
add files parameter to /instance API [5]

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#50]
New functionality where an array of file objects `{filename: url}` can be added to the edit API call. Enketo would then show the previews of these. Or an array.

It would be added to this: http://apidocs.enketo.org/v2/#/post-instance and this: http://apidocs.enketo.org/v2/#/post-instance-iframe API endpoint. 

relates to #9

Note that this will not do anything until a server (KoBoCAT) starts consuming this updated API endpoint by adding these file url arrays.

**Comment by tinok** [comment]
Maybe as an intermediary step we could add a more specific error message ("Your form contains an image but it can't be shown yet while editing."). 

Without this implemented the user sees this when editing an instance containing a photo: ![image](https://cloud.githubusercontent.com/assets/673511/7894704/0ff89240-063d-11e5-91e5-134b8dfb908f.png)

**Comment by overnin** [comment]
@MartijnR do you have any timeline to work on this feature?

**Comment by MartijnR** [comment]
No, not yet. There is one sponsor that recently expressed interest, but no decisions have been made about funding/prioritizing it yet. Note that this would also require support on the Ona/KoBo/Etc side.

**Comment by overnin** [comment]
My organisation could also join as a sponsor on this feature. Could you
give me more details on cost and timeline by email
olivier.vernin@landmapp.net ?

**Comment by MartijnR** [comment]
Thanks. That's great. I'll be in touch about that.

**Comment by geomapdev** [comment]
I am also very interested in this enhancement.  Were you able to find enough sponsors?

**Comment by MartijnR** [comment]
Hi @geomapdev,

No there is no progress on this. It would be easiest if KoBo or Ona wants, and funds, this feature and drives this forward. It's not very complicated on the Enketo side - about 3-4 days of work. We would need to do:

* [ ] Enketo describes API changes
* [ ] Ona or KoBo or Other implements this on their side
* [ ] Enketo implements on Enketo side

**Comment by geomapdev** [comment]
Ok, it looks like the code to show image previews alongside the filepicker widget is already there, but it is failing on fileManager.getFileUrl( existingFileName ):

https://github.com/enketo/enketo-core/blob/61f3b045d22dd45f3c2c493de5c7a590f716786b/src/widget/file/filepicker.js#L88

https://github.com/enketo/enketo-core/blob/master/src/js/file-manager.js#L59

Let me know if there's any way I can help, but I'm new to Kobo and Enketo so I'm pretty limited in that regard...

Thanks,
Dave

**Comment by geomapdev** [comment]
I created a fork of enketo-express to see if I could help with this.  Can you let me know if I'm on the right track with these changes?  I'm assuming it would require a new version (v3) of the api controller.

api-v3-controller.js
https://github.com/geomapdev/enketo-express/blob/master/app/controllers/api-v3-controller.js#L249

instance-model.js
https://github.com/geomapdev/enketo-express/blob/master/app/models/instance-model.js#L43
https://github.com/geomapdev/enketo-express/blob/master/app/models/instance-model.js#L79

**Comment by MartijnR** [comment]
@geomapdev I somehow totally missed your post from 20 days ago. Sorry about that. Yes, I think you're on the right track with this. 👍  

Thanks for looking at this!

P.S. When you look at the filepicker and file-manager this odd separation was done to facilitate mobile app development.

**Comment by geomapdev** [comment]
Thanks for the reply.  It looks like Kobo is using enketo-transformer as a web api, not the enketo v2 api.  Does that sound correct?

[https://github.com/enketo/enketo-transformer](https://github.com/enketo/enketo-transformer)
> full-featured use with: POST /transform with URL-encoded body including xform (required, full XForm as a string), theme (optional, string), and media (optional, map) parameters

But Kobo is not passing the media parameters.  Could that be all that's missing here?

Thanks,
Dave

**Comment by MartijnR** [comment]
Hi Dave,

KoBo is using Enketo's v2 API. Enketo-transformer is added as a module to enketo-express. KoBo and Enketo Express are not using the enketo-transformer web api.

The media map parameter of Enketo transformer is for media labels. It doesn't really play a role here.

The browser code needs to be able to retrieve the preview URLs for the file names in the record that it is loading. It may already make an attempt to do so (from the file-manager), but if so this is failing silently.

**Comment by geomapdev** [comment]
Thanks for keeping me on track, here are my modifications so far.  Let me know if you see anything off base here.
[](https://github.com/kobotoolbox/enketo-express/compare/master...geomapdev:master)
[](https://github.com/kobotoolbox/kobocat/compare/master...geomapdev:master)

**Comment by MartijnR** [comment]
I didn't try to diff the new API file with API v2. We can add this feature to API v2 because it's an optional additional parameter. It won't break any of the existing usage. I'm trying to avoid (ever) creating api v3. I'll have another look if you can change that. Thanks!

**Comment by geomapdev** [comment]
Ok, I will do that.  

I'm trying to get this working just within enketo (to take kobo out of the equation for now), where the forms are visible at a URL like this:  
https://enketo.koboserver.com/edit/::YYY8?instance_id=...&returnUrl=...

**Comment by MartijnR** [comment]
What is the best format for the attachments to receive/store?

a:
```json
{
   "a.jpg" : "https://someulr.com",
   "b.jpg" : "https://someotherurl.com"
} 
```
b: (as I suggested in OP, but seems wrong)
```json
[ 
   {"a.jpg" : "https"}, 
  {"b.jpg" : "https://"}
]
```

c:
```json
[
   {
       "url": "https:///",
       "name": "a.jpg"
    },
   {
       "url": "https:/..d.f",
       "name": "b.jpg"
   }
]
```

**Comment by MartijnR** [comment]
I believe you're using option a, right @geopmapdev? I think that's easiest and nicest.

**Comment by geomapdev** [comment]
Yes, option a.  Key/value pair seemed appropriate.


Dave
