### ISSUE TITLE
Date Constraint for less than or equal to Today, not working as expected

### ISSUE THREAD

**Issue by jmunene** [kobotoolbox/enketo-express#503]
On this XLS Form, there's a constraint that should allow a date that is equal to or less than Today

![screenshot_051316_035447_pm](https://cloud.githubusercontent.com/assets/13235212/15248430/d2d55e08-1922-11e6-9aa1-272c465420ec.jpg)

When you test the form on ODK Collect, it works as expected.

When you test the same form using Enketo, it does not accept Today's date as shown.

![screenshot_051316_035820_pm](https://cloud.githubusercontent.com/assets/13235212/15248508/454b986c-1923-11e6-8ee9-4b081d2edb1c.jpg)

**Comment by MartijnR** [comment]
Thanks!

It's a long outstanding issue (> 3 years). The only bug in the XPath evaluator. I guess it would be good to finally fix this... https://github.com/enketo/enketo-xpathjs/issues/27

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/issues/390

**Comment by faith-mutua** [comment]
Hi @MartijnR 

Should we be expecting a fix for this issue anytime soon? We have a user who hasn't been able to submit an interview application due to this.

**Comment by MartijnR** [comment]
Hi Faith,

I don't think so based on the priorities of clients that I'm aware of. But happy to do it if Ona sponsors it. Hard to estimate the time required. Less than a day I would think.

**Comment by MartijnR** [comment]
Hopefully fixed in 1.67.1

If not, please provide test case mentioning the time and timezone, as I did here: https://github.com/enketo/enketo-core/issues/522#issue-336301077
