### ISSUE TITLE
iOS: cannot assign to readonly property in NON-private browsing [?]

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#504]
Can be reproduced in private browsing mode on latest iOS.

Probably cannot be fixed, but will check.

![screenshot](https://cloud.githubusercontent.com/assets/627350/15255758/3b38babc-18fb-11e6-9a73-ad3a61d9d132.png)

**Comment by MartijnR** [comment]
@dorey writes

My (possibly unhelpful) google-fu reveals
> At least on my configuration, I have narrowed it down to the i18n plugin. When I remove all i18n! imports it loads fine.

**Comment by MartijnR** [comment]
It seems odd that we have a handful of users using private browsing. I don't this should be supported for offline-capable webforms.

However, if it also, under certain mysterious conditions, occurs in regular browsing in Safari on the latest iOS, than at least we may be able to reliably reproduce it.

**Comment by MartijnR** [comment]
also try #434 as it's likely a db.js issue

**Comment by MartijnR** [comment]
can be reproduced on OS X safari as well in private browsing mode

**Comment by MartijnR** [comment]
occurs in call db.open when assigning `.onsuccess` function: https://github.com/aaronpowell/db.js/blob/master/dist/db.js#L865

**Comment by MartijnR** [comment]
Also occurs in FF in private mode with a more helpful 'store is not available' message.

Closing this. If it only occurs in private browsing mode, then it's not an issue. Better to output the error message the browser throws then to try rewriting this. The important thing is that an error is thrown upon loading, so there is no risk of people loosing data.

**Comment by MartijnR** [comment]
It has occurred in non-private browsing mode as well, but seemingly randomly. Not sure if same issue as cannot reproduce outside of private browsing.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#45
