### ISSUE TITLE
Note with image sometimes not loading in offline-capable form.

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#517]
Sometimes, the image is not loading until you switch to a different language.

E.g. 
1. It loads with default English, **without background**,
2. Switching to Spanish, loads Spanish background
3. Switching back to English, loads English **background correctly**

Seen with header widget in UNGA theme/branch. Investigate whether it's a common issue. No issue in online-only webform.

**Comment by MartijnR** [comment]
looks like an issue with retrieving the image from storage.

**Comment by pmusaraj** [comment]
Fixed in `unga-III_docker` (and I removed the extra console.logs in a subsequent commit).
