### ISSUE TITLE
EDIT Instance

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#520]
Dear Martin,

Hope you are doing well.

I am trying to edit instance but the system gives me an error " Record not present. It may have expired.

Url is http://abc.xyz/edit/::YYYy?instance_id=?d4b2b8fa-1740-4e48-8540-7c15781e7886&return_url=http://abc.xyz/edit
![image](https://cloud.githubusercontent.com/assets/17918895/16105005/b52899aa-339f-11e6-8dc6-8847eeb68010.png)

**Comment by MartijnR** [comment]
The URL expires very quickly. It is meant to be used programmatically with an immediate redirect to the returned URL. Does your issue occur with KoBoCat, Ona, Formhub?

**Comment by iahmedani** [comment]
I am using on ODKAggregate server. But it do not spends one second, directly shows this error

**Comment by MartijnR** [comment]
Can you provide an actual curl API call (only change the api key, nothing else)?

**Comment by iahmedani** [comment]
curl --user xyz: -d "server_url=http://me.wfp.org.pk:8050/ODKAggregate&form_id=PDM_CMAM_1&instance=<data><node>DM_CMAM_UCDaag Besud _Location_Daag Besud</node></data>&instance_id=d3effa60-eae1-40da-8c2b-b1dd56670be1&return_url=http://me.wfp.org.pk" http://10.11.70.36/api/v2/instance

**Comment by MartijnR** [comment]
The `instance` is not valid XML instance (unless github stripped away the tags - put the whole snippet between `quotes` to avoid that). I'm surprised Enketo returns a success response. It should return an error response. 

See documentation here: http://apidocs.enketo.org/v2/#/post-instance

**Comment by MartijnR** [comment]
Ok, I was (surprisingly) able to edit your post and add the quotes. So I'll delete my response.

**Comment by MartijnR** [comment]
Will investigate if there is a bug if the instance XML does not match the XForm instance. I'm assuming the primary instance does not have a root node with name `data`. You should in that case get a different error message if you redirect immediately.

It may help if you could also share the XForm or XLSForm.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#38
