### ISSUE TITLE
integer and decimal fields validation

### ISSUE THREAD

**Issue by z-arhaz** [kobotoolbox/enketo-express#521]
Hi,
Currently enketo-express has no form of validation for integer fields.When a use enters an alphabetical character in that field it gives the user no response and saves a null on save..Shouldn't there be a validation preventing users to enter alphabetical characters instead of just saving a null the integer field could be crucial for analyses and one may only notice at the end on seeing all data collected that the integer field has some values as null due to entering alphabetical characters by mistake.

Secondly for a decimal field it allows a user to enter (0.0.2) Cant  we have a validation that ensure the format of the decimal value entered is correct if not some sort of validation message is thrown. instead of just ignoring and saving a null value instead

**Comment by MartijnR** [comment]
3 posts is too much. Pick one :). Either on github or the google dev group in this case.

Continued here: https://groups.google.com/forum/#!topic/enketo-dev/lt3pikoxUPo
