### ISSUE TITLE
record fragment identifier in analytics (#abcd) if possible

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#523]

**Comment by tinok** [comment]
This may be just a one line change: http://mediacause.org/track-anchor-tags-google-analytics-2/

**Comment by MartijnR** [comment]
* [ ] test in production

**Comment by MartijnR** [comment]
This seems to work. It's no longer tracking queryparameters, but I think that's better actually. They are used in previews (mostly), and not having them included, makes it easier to analyze.

<img width="278" alt="screen shot 2017-10-24 at 5 02 51 pm" src="https://user-images.githubusercontent.com/627350/31972299-33c9eb06-b8dd-11e7-8f94-921bab6b74bd.png">
