### ISSUE TITLE
Sync Form language with UI language (if match found)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#526]
Will require recommended language name with iso code such as `English (en)`, `Arabic (ar)` as agreed in ODK Dev forum: https://groups.google.com/forum/#!searchin/opendatakit-developers/language$20names$20proposal%7Csort:relevance/opendatakit-developers/ZLDJanOCudE/T7yTrDMYVAsJ

See "Tip: Prepare for the Future" in this post: http://blog.enketo.org/advanced-language/

Algorithm:

**Comment by smusula** [comment]
How is this expected to work?

Will it possible for someone to have a url like [https://enketo.ona.io/::YYGk?language=Amharic](https://enketo.ona.io/::YYGk?language=Amharic)? - where Amharic is one of the languages defined in the XLSForm.

**Comment by MartijnR** [comment]
It's not determined yet how this will work. Your suggestion is an option but it would use the official 2-character language code instead. I think we should at least include:

1. If browser locale is available as form language load that that form language as default (ignoring XForm default).
2. If user switches form language UI language should also be switched if that language is available.

**Comment by smusula** [comment]
Thanks for the feedback

**Comment by MartijnR** [comment]
point 1 is taken care of by e.g https://github.com/kobotoolbox/enketo-express/commit/57dd427d4f52115ca28ffb2d3ebbd89c72bf6926

**Comment by MartijnR** [comment]
This issue has been reduced to only solve point 1.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#57
