### ISSUE TITLE
nginx time out issue

### ISSUE THREAD

**Issue by joshvizzan** [kobotoolbox/enketo-express#527]
Not able to preview the form or deploy it due to nginx time out issues. Please check below: 

Form preview - xhr request url:
http://172.17.0.1:8005/transform/xform?form=http://172.17.0.1:8000/asset_snapshots/sjh9FrkoMKrnM8RpdVqhBL.xml 

Form preview - xhr response: 
504 Gateway Time-out
nginx/1.4.6

Form deploy - xhr request url: 
http://172.17.0.1:8000/assets/aUxyM4MWCEJk9Xx7pTqFpX/deployment/

Form deploy - xhr response: 
{"detail":"HTTPConnectionPool(host='172.17.0.1', port=8001): Max retries exceeded with url: /api/v1/forms (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fda7acb2110>: Failed to establish a new connection: [Errno 110] Connection timed out',))"}

**Comment by MartijnR** [comment]
Enketo cannot retrieve the resource. Not really possible to investigate for us. It has to do with your form/data server. This has happened in the past with incorrect SSL certificate installation, but that does not appear to the issue on your server. I would try to access the resource from your enketo server (e.g with curl) and see if that shows anything useful.

**Comment by joshvizzan** [comment]
Martin the installation was local so I am not sure if that is an issue with SSL. Is there any specific log I can provide you with that can help in resolving this issue.

**Comment by MartijnR** [comment]
Yes, SSL is not the issue in your case. The logs won't help, as it will just show the request is timing out. Making a curl request from your Enketo server to your form/data server is going to be more useful perhaps. It's likely some kind of networking issue where your form/data server (VM?, container?) is not accessible by your local Enketo app. I have no other suggestions to offer, I'm afraid.
