### ISSUE TITLE
Error during updating 

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/enketo-express#532]
Hi Martin,

Hope you are doing well. I'm facing following error update. 
Plz help me in this regard.

npm ERR! git clone --template=/home/enketo/.npm/_git-remotes/_templates --mirror                          https://github.com/enketo/grunt-i18next.git /home/enketo/.npm/_git-remotes/http                         s-github-com-enketo-grunt-i18next-git-7411fe55: Cloning into bare repository '/h                         ome/enketo/.npm/_git-remotes/https-github-com-enketo-grunt-i18next-git-7411fe55'                         ...
npm ERR! git clone --template=/home/enketo/.npm/_git-remotes/_templates --mirror                          https://github.com/enketo/grunt-i18next.git /home/enketo/.npm/_git-remotes/http                         s-github-com-enketo-grunt-i18next-git-7411fe55: error: RPC failed; result=7, HTT                         P code = 0
npm ERR! git clone --template=/home/enketo/.npm/_git-remotes/_templates --mirror                          https://github.com/enketo/grunt-i18next.git /home/enketo/.npm/_git-remotes/http                         s-github-com-enketo-grunt-i18next-git-7411fe55: fatal: The remote end hung up un                         expectedly
npm ERR! Linux 4.2.0-41-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update" "--production"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/enketo/.npm/_git-remotes/_te                         mplates --mirror https://github.com/enketo/grunt-i18next.git /home/enketo/.npm/_                         git-remotes/https-github-com-enketo-grunt-i18next-git-7411fe55
npm ERR! Cloning into bare repository '/home/enketo/.npm/_git-remotes/https-gith                         ub-com-enketo-grunt-i18next-git-7411fe55'...
npm ERR! error: RPC failed; result=7, HTTP code = 0
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/enketo/enketo-express/npm-debug.log

**Comment by iahmedani** [comment]
error log file

**Comment by iahmedani** [comment]
[npm-debug.zip](https://github.com/kobotoolbox/enketo-express/files/368393/npm-debug.zip)
error log file

**Comment by MartijnR** [comment]
Thanks! I think it has something to do with how I included a new package. I will try a temporary fix and have submitted a [PR](https://github.com/i18next/grunt-i18next/pull/7) for a proper fix.

In the mean time, you'll probably want to use version 1.31.0 on your production server (or try the latest version but upgrade to npm 3 first).

**Comment by MartijnR** [comment]
I was not able to reproduce the issue myself, but I'm fairly confident 1.32.1 will not have this issue any more. It should work with both npm 2.x.x as well as npm 3.x.x. (but note that when switching to another npm version it's probably wise to remove the `node_modules` folder and run `npm install` again.
