### ISSUE TITLE
OC Only: Headless mode with autoqueries

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#533]
Needs to be able to handle large import loads. 

Enketo Express or stand-alone app? Advantages of both: 

| Enketo Express | Standalone |
| --- | --- |
|  | performance, easily scaleable |
|  | imports will not affect regular webforms loading/submissions |
| cheaper to develop |  |
| easier to maintain code (more re-use) |  |
| no extra app to run |  |
| transformer and core automatically in sync |  |

**Comment by MartijnR** [comment]
- record-per-record
- returning list of errors

**Comment by MartijnR** [comment]
as discussed: dedicated "record-validator" Enketo Express instance could be used to get benefits of both columns in above table. Simply don't use the instance for anything else...

**Comment by MartijnR** [comment]
Possibly need to add check for whether irrelevant branches have values in them (they shouldn't). Thanks @dorey! :)

**Comment by MartijnR** [comment]
for OC might need to be combined with auto-queries

**Comment by MartijnR** [comment]
What kind of results are expected from such a request? 

Views: could be a complete or incomplete record in edit mode (so with or without complete button). If RFC required, needs auto-RFC (new feature).

**Comment by MartijnR** [comment]
complete record with or without RFC
incomplete record which would have to be loaded and then either Closed or Completed

**Comment by MartijnR** [comment]
Like edit view:
* always click Close button to trigger autoqueries and finish (after fieldsubmission have completed).
* for incomplete records, the close dialog option for "use queries" should be selected automatically

Differs from edit view:
* pass RFC value (one string)
* probably need different view for completed and incomplete records (because Close button works differently currently for complete and incomplete records). 
* relevantErrors current have no autoqueries but need to get them.

Should we figure out how to properly mark a record as complete?

**Comment by MartijnR** [comment]
for testing: http://localhost:8005/single/fs/i/::uEUZO5H2

**Comment by MartijnR** [comment]
1-2 weeks depending on complexity of logic

**Comment by MartijnR** [comment]
response is best done in the same manner as other API response so with HTTP status code and JSON response body:

2xx
{
  message: "OK",
  code: 2xx
}

200: OK, but not fieldsubmissions were made
201: OK, fieldsubmissions were created and all submitted successfully
408: timeout, something went wrong, some fieldsubmissions may have been made, see message for details?
400: some other error occured before the timeout was exceeded. The process was stopped.

**Comment by MartijnR** [comment]
am experiencing this issue: https://github.com/GoogleChrome/puppeteer/issues/1047

**Comment by MartijnR** [comment]
@pbowen-oc, what should be the difference in between between these scenarios?

1. Process a record that is marked as complete
2. Process a record that is not marked as complete

**Comment by pbowen-oc** [comment]
@MartijnR - Records marked complete would need to have autoqueries added for any error (constraint, required, relevant). I think records not marked complete would only get autoqueries for constraint and relevant errors (not required errors).

Regarding our recent discussion of strict constraint/required, I think this behavior would apply equally to strict and non-strict constraint/required errors. Perhaps, though, in the case of a strict constraint/required error being active, a different response should be sent back to OC so that we can flag the record if needed?

**Comment by MartijnR** [comment]
* [ ] validation issue is the same in regular fieldsubmission view without enketo-core customizations and common KoBo views
* [ ] check kobo/enketo-express

**Comment by MartijnR** [comment]
Ready for testing in `develop` branch. 

Documentation: https://github.com/OpenClinica/enketo-express-oc/blob/develop/doc/oc-api.md#post-instanceheadless

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#47
