### ISSUE TITLE
Can the performance of pulldata() be improved for csv data with over 2000 rows?

### ISSUE THREAD

**Issue by ukanga** [kobotoolbox/enketo-express#534]

**Comment by MartijnR** [comment]
Yes, probably. The current implementation (transforming to regular XPath) might always go through all 2000 rows (even if it finds it in the first row). Would definitely be worth investigating. 

Then, there are more exotic options that would avoid using XPath (and maybe even XML), but those would be less interesting to explore (for me).

Is the performance issue limited to the initial load of the form only? Probably not, but if it is, the transformation from CSV to XML would be the key to look at.

**Comment by MartijnR** [comment]
Note to self: Does XPathJS actually stop looking for more results if resultType is 'node'?

**Comment by pasquierjb** [comment]
Hi MarijnR, the performance issues are not limited to the load of the form but for each query of the pulldata function.

**Comment by MartijnR** [comment]
thanks!

**Comment by MartijnR** [comment]
Confirmed: first item in list takes just as long as last item in list. So there should be scope to improve with factor 2 on average.

**Comment by MartijnR** [comment]
correction: a factor 60-100 improvement seems possible...

**Comment by MartijnR** [comment]
Oops. sorry. That's not true.

**Comment by MartijnR** [comment]
Oops. sorry. That might not be true.
