### ISSUE TITLE
Change instance-Id and deprecated-Id headers

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#536]
It's not a great use of custom HTTP headers, and they are only used by Enketo internally (to log submissions), so they should at least be called "X-Enketo-...". If maintaining these headers is necessary, see if they can be stripped when the request is piped to the OpenRosa server.

**Comment by MartijnR** [comment]
These kind of practices could become problems when servers start relying on them.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#40
