### ISSUE TITLE
form not found in formList error

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#537]
Hi Martijn,
Hope you are well. We have noticed something interesting about how our enketo - I have a feeling it might be my fault but you might help resolve it :-). Try logging in to your ona.io account and try to access `https://enketo.ona.io/x/#Yo8l` - it's a form in my account. You should get the error in the following screenshot.
<img width="787" alt="screen shot 2016-07-22 at 16 36 09" src="https://cloud.githubusercontent.com/assets/1128227/17058666/445f048c-502a-11e6-88af-b21b427a42f1.png">

Log out from your ona.io account and try to access the enketo url again and it should load successfully. The following screenshot is a representation of what you should see.
<img width="738" alt="screen shot 2016-07-22 at 16 39 29" src="https://cloud.githubusercontent.com/assets/1128227/17058854/f3cb47f0-502a-11e6-9e03-e62477bf59a7.png">

I'm not really sure why you have not to be authenticated to access a public enketo url. Any help would highly be appreciated.

Thanks.

**Comment by MartijnR** [comment]
Hi Mark,

I noticed this issue frequently when I use Ona for development purposes. I thought it was related to using the same local Enketo server for both KoBo's and ODK Aggregate (OpenRosa) authentication as well as for Ona's own authentication. My browser may have stored a cookie with OpenRosa credentials and passes those credentials (using Basic/Digest auth) to Ona when requesting stuff. In that case, it only occurs for me basically, but now it seems to have spread. Maybe my diagnosis was incorrect.

See here: https://github.com/onaio/onadata/issues/780

**Comment by ivermac** [comment]
Hi Martijn,
The problem was with our formList and we have deployed a fix for it.

Thanks again.
