### ISSUE TITLE
mp3 file not playing in offline-capable webform views on Android

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#539]
Reproduce with https://enke.to/x/#widgets on latest Chrome/ latest Android.
The media is served by Ona.

May not be an Enketo issue. My first guess is that the media-type gets lost when storing the file in the browser db. This may be because it isn't served correctly.

**Comment by MartijnR** [comment]
possible duplicate of https://github.com/kobotoolbox/enketo-express/issues/256

**Comment by MartijnR** [comment]
On Chrome/OSX:

<img width="953" alt="screen shot 2016-08-03 at 10 35 17 am" src="https://cloud.githubusercontent.com/assets/627350/17373587/158165b6-5966-11e6-9c10-d5d06cbf9561.png">


On Chrome/Android:
<img width="947" alt="screen shot 2016-08-03 at 10 35 26 am" src="https://cloud.githubusercontent.com/assets/627350/17373594/1aeb990e-5966-11e6-9528-a24514c0cf6f.png">

On Android the file is only retrieved partially. Wonder if it would make sense to first see if [this issue](https://github.com/kobotoolbox/enketo-express/issues/155) still occurs, remove base64 conversion and then see if this issue still occurs.

* [ ] check Firefox on Android
* [ ] check Safari on iOS

**Comment by MartijnR** [comment]
No issue of FF/android and Safari/iOS.

**Comment by MartijnR** [comment]
I suspect it's some kind of hidden Chrome/Android restriction on the size it will store in indexedDb. 

When workaround for #155 is removed, the issue does not occur in the same form, possibly because without base64 conversion the size is much smaller (It might recur with a file exceeds a certain size though, or blobs are dealt with differently).

Currently testing whether #155 is resolved in latest Chrome.

**Comment by MartijnR** [comment]
not resolved

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#41
