### ISSUE TITLE
Pulling data from a linked dataset is throwing an error. 

### ISSUE THREAD

**Issue by faith-mutua** [kobotoolbox/enketo-express#546]
Ona has developed a new feature that allows pulling data from a linked form/filtered dataset. This feature enhances pull CSV by making it possible to be used with dynamic datasets. 

The pulldata function is throwing the error below on Enketo when one opens the webform with the linked dataset.
![screenshot_083116_060141_pm](https://cloud.githubusercontent.com/assets/17847885/18133890/fa647552-6fa4-11e6-858e-a929120d2c9a.jpg)

 We are suspecting that the forward slash in the column headers could be the cause for the error since the same form is working fine on ODK Collect. 

Any suggestions or pointers on the above issue will be highly appreciated. 

Thanks

**Comment by MartijnR** [comment]
Ah yes, when converting to XML the column heading becomes the XML nodeName. This means only valid XML nodeName characters can be used, i.e. from the top of my head: alphanumeric, underscore, hyphen, no-number-as-first-character.

**Comment by faith-mutua** [comment]
Thanks Martijn. So this means that we have to change the forward slash on our end to one of the valid XML nodeName characters?

**Comment by MartijnR** [comment]
Yes, that would be the best solution.

**Comment by faith-mutua** [comment]
Thank you

**Comment by MartijnR** [comment]
I'll close this now.

I love this feature and would like to promote it. I this working with Enketo now?

**Comment by faith-mutua** [comment]
Yes, it's now working with Enketo
