### ISSUE TITLE
change OC server - steps?

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#557]

**Comment by MartijnR** [comment]
Account manager + forms

**Comment by MartijnR** [comment]
For all the surveys to change `https://server1.com/a` into `https://server2.com/b`.

1. get list of all server+formID combos for the old server with `keys "or:server1.com/a,*"`
2. rename the keys of all results of 1. This will point the forms on the new server to the same EnketoID as the new server. E.g. `rename "server1.com/a,myForm" "server2.com/b,myForm"` 
3. check the enketoIDs of all results of 1
4. for each EnketoID change the openRosaServer value to "https://server2.com/b". Don't change anything else.
5. [optional?] get the account, `hgetall ac:server1.com/a` and change the `linkedServer` value to "https://server2.com/b"

**Comment by jnm** [comment]
Sorry to comment on a long-closed issue, but I found this while searching in Flowdock for my own Lua script. It changes all `openRosaServer` values that start with `http://` to begin with `https://`instead. It doesn't cover all the steps you've discussed, but maybe it's helpful in some way. The script assumes it's saved to a file called `http-to-https.lua`.
```Lua
-- Run with `redis-cli --eval http-to-https.lua 0`
-- `KEYS` is blocking, but our Redis is too old for `SCAN`
local output = {}
local ee_ids = redis.call('keys', 'id:*')
for _, key in ipairs(ee_ids) do
    local url = redis.call('hget', key, 'openRosaServer')
    local fixed_url = string.gsub(url, 'http://', 'https://')
    if url ~= fixed_url then
        redis.call('hset', key, 'openRosaServer', fixed_url)
        table.insert(output, key .. ' ' .. fixed_url)
    end
end
return output
```
