### ISSUE TITLE
How do you set input value programmatically?

### ISSUE THREAD

**Issue by barrowsglobal** [kobotoolbox/enketo-express#558]
I am using a third party barcode scanner to return the barcode, and then set this barcode in the input field. I have successfully done this, but the value is not recognised as being set.

This is sample code, I've replaced the barcode scanning with setting a test value on click:
```
$('input[data-type-xml="barcode"]').bind('click', function(){
                $(this).val('test').trigger('change');
});
```

If I submit my form, the value does not get submitted, even though I can physically see it before submission. If I have it as a required field, it tells me that the field is required (see below screenshot)
![barcode](https://cloud.githubusercontent.com/assets/22342430/18907501/248e5546-856c-11e6-9d07-293c058e6758.png)

How do I get it to recognise this value as being set for submission or validation?

**Comment by MartijnR** [comment]
Your code works perfectly for me. I tested by submitting to Ona with this form: https://enke.to/::widgets. Whatever value I add, it gets submitted.

I suspect that your server doesn't accept the value as a barcode (Aggregate?).

Regarding the 'this field is required' message, I didn't test this, but I could be something else related to programmatically changing the value after the message was already shown. May need to fire a focusout event (and maybe a focusin event before setting the value). All this is pretty hacky though.

If you have a technical suggestion for adding the barcode feature, do let us know. There is an issue for it here: https://github.com/kobotoolbox/enketo-express/issues/217

**Comment by barrowsglobal** [comment]
I've tried triggering focusin, focusout, but still no luck.

If I were to physically type the same word (ie. "test"), it accepts the value as valid and submits the value. I know there is nothing wrong with the field/form itself as this works as expected - except, of course, when I set a value via javascript. It is as though the form/dom is not seeing the value.

Once I have figured the above out, I will definitely pass on my suggestion (aka hack) to get the barcode scanning working on the web forms.

**Comment by MartijnR** [comment]
I tested by typing in the console. If you are doing this by adding code to Enketo Express, the issue might be that your value is added **before** any eventhandlers are present, i.e. before the form is initialized. This is therefore not recognized as a user input.

**Comment by barrowsglobal** [comment]
I was more than likely doing that, just couldn't figure out where.
Anyway, went on a different route, added my own widget and have managed to get it to work. Should I post my code on [#217](https://github.com/kobotoolbox/enketo-express/issues/217)? I must warn you that it is a bit of hack.

**Comment by MartijnR** [comment]
Great! Yes, please do. It will never hurt. When we are ready to add a widget, we'll definitely see if we can use it.
