### ISSUE TITLE
Images uploaded to a form not showing up in Enketo

### ISSUE THREAD

**Issue by faith-mutua** [kobotoolbox/enketo-express#568]
Hi Martijn,

We have a user who has included questions in his form that display images. The images are uploaded to the form after it has been uploaded on Ona. 
When the form is opened on Enketo, some images are not displayed. We aren't able to tell what the problem could be from our end. 

Have you experienced this before? Any suggestions or pointers on this issue will be highly appreciated. 

Thank you

**Comment by MartijnR** [comment]
Hi Faith,

Do you have a webform URL, preferably a publicly accessible one that demonstrates the issue?

**Comment by faith-mutua** [comment]
Hi Martijn, 

Yes, I have one https://enketo.ona.io/x/#YHUx. In this webform, it's only one image that doesn't show up

**Comment by MartijnR** [comment]
Thanks Faith,

Enketo couldn't find the goose.png message in the XFormsManifest. Please check if it's listed there. 

It could also perhaps be the capitalization in the actual filename vs. the filename in the XFormsManifest vs the filename in the XForm.

**Comment by faith-mutua** [comment]
Sure, let me check then update you on how it goes

**Comment by faith-mutua** [comment]
Hi Martijn, 

In the first web form I had shared https://enketo.ona.io/x/#YHUx the last image was missing from the form's settings page. I think that's why it wasn't showing up. 

In this web form https://enketo.ona.io/x/#YZR8 I have all images uploaded to the form yet, the first two images are not showing up. All images are in .png format

**Comment by MartijnR** [comment]
Thanks Faith,

For the second form, the problem was the same. At the time Enketo requested the XForm and resources in order to transform it to HTML, those 2 images were missing from the XFormManifest.

I think the issue lies on the Ona side, but I'd be happy to look at this issue to figure out where it occurs and fix it if it's an Enketo bug. I would bill Ona for this, so I'll wait for confirmation.

**Comment by faith-mutua** [comment]
Thanks Martijn for the pointers on the issue. I will raise this with our technical team so that they can look into it further. I will update you on the progress.

**Comment by MartijnR** [comment]
please re-open if necessary
