### ISSUE TITLE
Period in Begin Repeat name prevents data in repeat groups from appearing in Enketo for editing 

### ISSUE THREAD

**Issue by msschroeder** [kobotoolbox/enketo-express#571]
Hello Martijn,

We have a user that included periods in the name of the begin repeat group. Collecting data is not an issue. However, if a user wants to edit this data, only the first repeat will appear, and adding another just displays question with no data. However, not including periods, the repeat groups are easily viewable in Enketo? 

Have you experience this before?

Thanks,
Megan

**Comment by MartijnR** [comment]
Hi Megan,

That sounds like a bug. If the form is not confidential could you send/link it perhaps? Otherwise please just share the exact name of the repeat.

Thanks,

**Comment by msschroeder** [comment]
Hi Martijn,

Here is a link to another form, but the same thing occurs. [Form](https://docs.google.com/a/ona.io/spreadsheets/d/1qsn5XJ8uqaLqmWv9sOCeDx0wNgg60mzBW_TX7hsaZk8/edit?usp=sharing)

Megan

**Comment by MartijnR** [comment]
Fixed. Thanks!

Disclaimer, in the process of fixing this, I have become quite convinced that there are more undiscovered bugs related to dots in question/group/repeat names. So do let us know if you find any (or avoid dots)!
