### ISSUE TITLE
remove jQuery queries from Model

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#573]
There are highly likely jQuery-related bugs remaining with nodeNames containing a `.` after fixing #571 

refactor:

- cloneRepeat
- determineIndex (also check for difference between this and getRepeatIndex)
- anything containing `.replace( /\./g, '\\.' )`

it would make sense for NodeSet.get to always return a single Element (not jquerified)
and to add NodeSet.getAll that always returns an array of Elements.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-core#557
