### ISSUE TITLE
Editing a submission with a relevant in a repeat referencing a field in a group before it fails with FormLogic Error

### ISSUE THREAD

**Issue by ukanga** [kobotoolbox/enketo-express#594]
Take the XLSForm
```
type              | name | label      | relevant    |
text              | n    | Name       |             |
begin group       | ab   | group ab   |             |
select_one yes_no | ynab | Yes or No  |             |
end group         | ab     |          |             |
begin repeat      | a    | repeat a   |             |
select_one yes_no | ynaa | Yes or No  | ${ynab} = 1 |
end repeat        | a    |            |             |
```
When you add a submission and try to edit it fails with the FormLogicError:
```
FormLogicError: Could not evaluate: /model/instance[1]/abcabce/a[1]b/ynab = 1, message: The expression is not a legal expression. (line: undefined, character: undefined)
```

I noticed this only happens where the group name `ab` starts with the repeat name `a` and we have a relevant to a field in the group. If the group name did not start with the repeat name, the error does not occur. 
You will also need to have at least two repeats or no repeat at all. One repeat does not seem to have the issue.

[abcabce.xlsx](https://github.com/kobotoolbox/enketo-express/files/648760/abcabce.xlsx)

**Comment by ukanga** [comment]
Requires at least two repeats or none to replicate the error, I updated instructions to reflect this.

**Comment by MartijnR** [comment]
Thanks for the great report! Interesting issue. It seems to be a bug that is related to how the [Great Deviation](https://opendatakit.github.io/odk-xform-spec/#a-big-deviation-with-xforms) is implemented.

**Comment by MartijnR** [comment]
@ukanga FYI, I had some troubles updating to the latest Enketo Express on a production server, related (again) to grunt-sass, and/or libxslt. 

They may very well have been related to my specific server, but I think it might be worthwhile to check that you are running npm 3.x.x (and not 2.x.x like I was, and not 4.x.x like I tried). That eventually solved it for me (and removing node_modules to reinstall with `npm install --production`)
