### ISSUE TITLE
leaflet map tiles

### ISSUE THREAD

**Issue by danielduhh** [kobotoolbox/enketo-express#613]
leaflet map tiles do not render in "production" mode. Looks like its trying to pull map tiles from :8005/a instead of https://a.tile.openstreetmap.org

**Comment by MartijnR** [comment]
Thanks. 

What is your ["maps" configuration](https://github.com/kobotoolbox/enketo-express/blob/master/config/README.md#maps) value?

Are you using docker?

**Comment by danielduhh** [comment]
the default value, and nope, no docker - manually installation

`    "maps": [ {
        "name": "streets",
        "tiles": [ "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" ],
        "attribution": "© <a href=\"http://openstreetmap.org\">OpenStreetMap</a> | <a href=\"www.openstreetmap.org/copyright\">Terms</a>"
    } ]`

**Comment by MartijnR** [comment]
Thanks. I tried to reproduce it, and rule out any npm module differences by doing `rm -R node_modules/ && npm install && grunt && npm start`

I cannot reproduce the issue for geopoint, geotrace and geoshape widgets. Could you try the same?

**Comment by danielduhh** [comment]
cool, thank worked - thanks
