### ISSUE TITLE
OC only: Display participant ID at the top of forms

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#616]
https://jira.openclinica.com/browse/OC-7556

[TITLE] for [ParticipantID] (if there is one)

How to pass this ID?

**Comment by MartijnR** [comment]
Or will OC this dynamically add to XForm title element?

**Comment by MartijnR** [comment]
Variable, so maybe query parameter.

**Comment by MartijnR** [comment]
doing iframe, so closing

**Comment by MartijnR** [comment]
We can do a hacky quick solution to add support for ?PID=abc, by appending this to the title element  during loading.

**Comment by pbowen-oc** [comment]
@Martijn - Can we display the title as "[PID]: [Form Title]" if the PID is passed in and simply "[Form Title]" if the ID is empty?

**Comment by MartijnR** [comment]
yes, definitely

**Comment by MartijnR** [comment]
* [ ] also on 100% readonly views

**Comment by MartijnR** [comment]
so adding ?PID=something to the URL will do the trick
