### ISSUE TITLE
error when submitting/loading dn data

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#644]
user enters a Query, saves it, exits the form, reopens the form and reopens the query. The History section is missing the column that contains the Query icon and the time is broken (both in FF and Chrome)

![query_before_closing_form](https://cloud.githubusercontent.com/assets/627350/22955183/fbeb2a68-f2d7-11e6-9e01-78d9902cc746.PNG)
![query_errors](https://cloud.githubusercontent.com/assets/627350/22955184/fbed35ec-f2d7-11e6-89f2-a97bfa696c5e.PNG)

**Comment by MartijnR** [comment]
Request for  the instance (XML) that is sent to Enketo to be loaded. Alternatively, if there is a live URL I could see this error with, I could use the console to get that.

**Comment by jbonica** [comment]
@MartijnR,
I'm not sure how to get the instance XML. Is this the general form.xml and/or form-queries.xml? Thanks for your help!

**Comment by MartijnR** [comment]
It's the content of the `instance` parameter of the POST API call OC makes to Enketo's api/v2/instance/fieldsubmission/iframe.

What I really only need is just one of the failing stringified JSON data structures for a 'comment' node. My guess is there is something unexpected/missing in that JSON structure (in particular missing `type` and unparsable `date_time`. I believe OC dynamically generates that stringified JSON content just before sending it to api/v2/instance/fieldsubmission/iframe.

e.g. 
```xml
<a_comment>{&quot;queries&quot;:[],&quot;logs&quot;: [{ &quot;type&quot;: &quot;comment&quot;, &quot;status&quot;: &quot;updated&quot;, &quot;message&quot;: &quot;This is an older comment.&quot;, &quot;user&quot; : &quot;Maurice Moss (moss)&quot;, &quot;assigned_to&quot;: &quot;Ada Clare (aclare)&quot;, &quot;date_time&quot; : &quot;2016-04-22 14:44:20 -06:00&quot;},{ &quot;type&quot;: &quot;audit&quot;, &quot;message&quot;: &quot;Item data value updated from old_value to new_value.&quot;, &quot;user&quot; : &quot;Jen Barber (jen)&quot;,&quot;date_time&quot; : &quot;2016-05-18 12:44:20 -06:00&quot; }]}</a_comment>
```

**Comment by MartijnR** [comment]
was found to be OC bug
