### ISSUE TITLE
Relevant + calc in repeat not working properly

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#645]
Repeat group with a question that has a relevant condition that depends on another question the same group. By default the relevant evaluates to false.

If a second repeat is created without changing the first repeat relevant to evaluate to true, the question can never be shown.

It seems that the relevant condition is not following the deviation (doesn't inject positions).

Reported by James (OC) on 2.15. See email for test form. Question ML_not_totalBill in first repeat.

**Comment by MartijnR** [comment]
Could have something to do with nodeNames used in the expression.

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=https://api.ona.io/enketo/forms/183467/form.xml

**Comment by MartijnR** [comment]
simplified test case: http://localhost:8005/?xform=https://api.ona.io/enketo/forms/183468/form.xml

**Comment by MartijnR** [comment]
looks like branchUpdate doesn't pass index

**Comment by MartijnR** [comment]
@jbonica, very glad you found this and figured out how to reproduce it exactly. I think it was a very old bug, but only became apparent once Enketo started supporting calculations on readonly questions (recently). Will merge fix into OC shortly!

**Comment by jbonica** [comment]
Thanks, Martijn!
