### ISSUE TITLE
dynamic markdown links in labels and hints

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#646]
`[link](href)` gets turned into `<a href="href">link</a>`
`this is ${what}` gets turned into `this is <span class="or-output" data-value="/path/to/what"><span>`

To support `this a [dynamic link](${what})`, we could create the following output:

```
this is a <a class="or-output" data-value="/path/to/what" href="">dynamic link</a>
```

and then change the outputUpdate function to do something different if output is an anchor.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-transformer#47
