### ISSUE TITLE
Parsing error with select_one_from_file

### ISSUE THREAD

**Issue by rhunwicks** [kobotoolbox/enketo-express#662]
I am trying to use an XForm containing a `select_one_from_file` to pull data from an external CSV. When Enketo opens the Form I get:

```
Loading Error

Unable to auto-detect delimiting character; defaulted to ','
```

I am guessing this is from https://github.com/mholt/PapaParse/blob/master/papaparse.js#L852 but I can't see why.

The form is deployed in Kobocat, and the CSV file has been uploaded as a Document to Kobocat. If I look at the network requests from the browser using Developer Tools I can see a request to http://server.example.com/enketo/media/get/http/server.example.com/kobocat/userx/xformsMedia/11/29.csv which has a 200 response and contains valid CSV as far as I can tell.

I am attaching a zip file containing the XForm sent to Enketo by Kobocat.

[xform.xml.zip](https://github.com/kobotoolbox/enketo-express/files/809044/xform.xml.zip)

**Comment by rhunwicks** [comment]
Note that I had to make a slight change to Pyxform to get Kobocat to load the XLSForm file - as described in https://github.com/XLSForm/pyxform/issues/87, but I am assuming that once I have an XForm that passes validation then I don't need to worry.

**Comment by MartijnR** [comment]
Does the online parser work for your CSV file? http://papaparse.com/demo

Try forcing the delimiter to `,`.  Different browsers may also have a different result (the other day I found a mysterious CSV parsing issue in IE11).

**Comment by rhunwicks** [comment]
@MartijnR thanks for the pointer to the demo. The problem was caused by Unix line endings in our CSV files - as soon as I save the file with Windows line endings or Mac line endings it works.

When you say "try forcing the delimiter" did you mean in the demo page, or in Enketo - and is there a way to specify it other than changing the code - I can't see any obvious settings in either Enketo or Kobocat to allow me to specify those things.

**Comment by MartijnR** [comment]
Ah thanks. Good to know. I'll close this now.

With forcing the delimiter, I meant in the demo. If that would resolve the issue, we can look into whether we can make a similar code change in Enketo (and still preserving both ; and , delimiters). If so, please re-open this issue and post a problematic csv file.

**Comment by rhunwicks** [comment]
@MartijnR I'd like to reopen this, if possible.

Further investigation shows that PapaParse can't guess the delimiter if there is a trailing newline character and there are less than 10 rows. This is discussed at https://github.com/mholt/PapaParse/issues/309. It doesn't matter if the line ending is Windows or Linux.

CSV files created using Excel or Gedit or Python's `csv.writer` will all have such a trailing newline.

Obviously we can work around this by adding the choices to the XLSForm directly, but given an installation with a large number of Forms with common lookups, it will be very inconvenient to have to update all the Form definitions and then redeploy them if we add a new lookup value. It would be much better to use `select_one_from_file` and then just update the single common file that all the forms share.

I suggest that we pass in ',' as a delimiter in `options` in utils.js:csvToArray()`.

Alternatively, given that the error returned by PapaParse is `UndetectableDelimiter: Unable to auto-detect delimiting character; defaulted to ','` and so it won't break anything and the result contains the correct data, we could change the `if ( result.errors.length )` to `if ( result.errors.length > 1 || (result.errors.length == 1 && result.errors[ 0 ].code != ""UndetectableDelimiter"))`.

For me at least, accepting short external files across many forms is more important than supporting tab-separated or semi-colon separated files.

**Comment by MartijnR** [comment]
Thanks a lot!

Would trimming the csv string be another way of solving it? Otherwise, we'll do one of the options you suggest. I think forcing a comma is acceptable (until somebody objects).

**Comment by rhunwicks** [comment]
Yes, provided that you know what the line terminator is. In Python you could do:

```python
        lineterminator = csv.writer(BytesIO(), **writer_opts).dialect.lineterminator
        if data[-len(lineterminator):] == lineterminator:
            data = data[:-len(lineterminator)]
```

(which is what I am now using on the extract process that writes the CSV files)

In theory, we should have access to PapaParse's `guessLineEndings(input)` somehow.

**Comment by MartijnR** [comment]
Was able to create a failing test and fix that. Please re-open if still an issue for your files. Thanks!
