### ISSUE TITLE
Read-only fields with calculations display before label in Grid Theme

### ISSUE THREAD

**Issue by rhunwicks** [kobotoolbox/enketo-express#665]
I have a Form with a repeating group where one field is calculated from the previous 2. When the field displays the order of the input and the label is reversed. I think this is because the input doesn't have an `order` attribute - the other inputs have `order: 4` set and if I set that manually using Dev Tools in Chrome it displays correctly.

I am attaching a simple XLSForm that demonstrates the problem and a screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/1317567/23692823/b17eadac-03d9-11e7-8adc-8bb14a59becd.png)

[read_only_calculation.xls.zip](https://github.com/kobotoolbox/enketo-express/files/826810/read_only_calculation.xls.zip)

**Comment by MartijnR** [comment]
Are you using a rather old version of Enketo perhaps?

The issue is no longer present it seems: https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmpmsc_eh9r/read_only_calculation.xml (temporary link).

Please re-open if you're using the latest version.
