### ISSUE TITLE
Arabic Language no showing from Right-to-left

### ISSUE THREAD

**Issue by bmalina** [kobotoolbox/enketo-express#667]
Hi Martin

I have a form with Arabic as one of the languages and it displays from left-to-right when using Ona's enketo as shown in the screenshot below instead of right-to-left.

![image](https://cloud.githubusercontent.com/assets/20789710/23799330/34059e80-05b9-11e7-8a5c-eeb0223b9c47.png)

Attached is the xlsform [test_mc+ocha.xlsx](https://github.com/kobotoolbox/enketo-express/files/834215/test_mc.ocha.xlsx)

Here is a link to the [Enketo form](https://ona.io/enketo/152/73760) that has Arabic and works well.
Do you have an idea of what the issue could be?

**Comment by MartijnR** [comment]
Hi Barbara,

Thanks for this. Enketo picks the first text (hint or if no hint, the first label) from each language to determine directionality. In your form the hint it picks is: "القضاء حيث تجري المقابلة.". This is determined to be left-to-right as it seems to be a mix of latin and arabic script characters. When I remove the dot, [it works](https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmpyjjk80h3/test_mc.ocha.xml) (temporary link).

Does this non-arabic-dot-issue make sense to you (or who designed the form), or do you think it's a bug?

P.S. unrelated issue: you should consistently use "English (en)" and "Arabic (ar)" in all the translated headings.

**Comment by bmalina** [comment]
Hi Martin,
I have made the change on the form and it worked well. The form belongs to a client. I don't think its a bug since it only affected that particular form.
Thank you for the tip on language headings.

**Comment by MartijnR** [comment]
thx. Still odd about the dot. But closing for now until an Arabic-speaking person confirms it's a bug.
