### ISSUE TITLE
Audit Event entry in QW being attributed to System user

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#669]
When a user adds a value to an item in OC Enketo (1.41.0), then opens the QW to add a Query, the Audit Event is of the data entry is attributed to the new System user. See screenshot. This System user should only be credited with automatically-generated Queries. Failed on automated regression tests.

![incorrect_user_in_qw](https://cloud.githubusercontent.com/assets/8268232/23861893/d043ca7c-07e1-11e7-9905-5c85f9ed0b8c.PNG)

**Comment by MartijnR** [comment]
Ah thanks. You're referring to the message: "This value has changed from a to b", right?

**Comment by MartijnR** [comment]
Oh sorry, the screenshot wasn't loading before. All clear now.

**Comment by MartijnR** [comment]
fixed in tagged commit 1.41.0.oc-2
