### ISSUE TITLE
prevent autoQueries when iframe closes properly

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#676]
As reported: 

I have a field that has the following constraint.These comment-status part will apply to every field  with constraints in OC.
constraint=" . >= 0 and . <= 100  or comment-status(${dn}) = 'new' or comment-status(${dn}) = 'updated'"

Scenario 1:
I enter invalid value in the field (such as 200), I add manually a query (status=new/updated),
then manually close the query (status =closed).
Manually closing the query will be a violation of constraint which triggers auto-query when closing the form using Close button.
Come back to the form, see duplicate auto-query has been applied to the field.

Scenario 2:
I enter invalid value in the field.  Close the form using Close button that  triggers  auto-query.
Come back to the form and manually close the query by adding Closed type query.
Manually closing the query will be a violation of constraint which triggers auto-query again when closing form using Close button.
Come back to the form, see duplicate auto-query has been applied to the field.

**Comment by MartijnR** [comment]
cannot reproduce. Maybe it has something to do with the iframe element firing an 'unload' event

**Comment by MartijnR** [comment]
Scenario two has two identical auto-queries generated with the 'close' query in between which is by design.

**Comment by jkeremian** [comment]
For Scenario1 : getting  below 2 payloads one after the other:
<instance><simple_crf_v5 xmlns:enk="http://enketo.org/xforms" xmlns:jr="http://openrosa.org/javarosa" xmlns:oc="http://openclinica.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="sc" version="5">
          <SECTION1>
            <GroupG>
              
              
            <item1_comment oc:queryParent="item1">{"queries":[{"type":"comment","id":"3","date_time":"2017-03-16 13:26:46 -04:00","comment":"Automatic query for: validation error message","status":"update","assigned_to":"","notify":false,"user":"root"},{"type":"comment","id":"2","date_time":"2017-03-16 13:26:15 -04:00","comment":"closing","status":"closed","assigned_to":"","notify":false},{"type":"comment","id":"1","date_time":"2017-03-16 13:25:35 -04:00","comment":"validation error message","status":"new","assigned_to":"","notify":false}]}</item1_comment></GroupG>
            
          </SECTION1>
          
        </simple_crf_v5></instance>
        

<instance><simple_crf_v5 xmlns:enk="http://enketo.org/xforms" xmlns:jr="http://openrosa.org/javarosa" xmlns:oc="http://openclinica.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="sc" version="5">
          <SECTION1>
            <GroupG>
              
              
            <item1_comment oc:queryParent="item1">{"queries":[{"type":"comment","id":"4","date_time":"2017-03-16 13:27:14 -04:00","comment":"Automatic query for: validation error message","status":"update","assigned_to":"","notify":false,"user":"root"},{"type":"comment","id":"3","date_time":"2017-03-16 13:26:46 -04:00","comment":"Automatic query for: validation error message","status":"update","assigned_to":"","notify":false,"user":"root"},{"type":"comment","id":"2","date_time":"2017-03-16 13:26:15 -04:00","comment":"closing","status":"closed","assigned_to":"","notify":false},{"type":"comment","id":"1","date_time":"2017-03-16 13:25:35 -04:00","comment":"validation error message","status":"new","assigned_to":"","notify":false}]}</item1_comment></GroupG>
            
          </SECTION1>
          
        </simple_crf_v5></instance>

**Comment by jkeremian** [comment]
For Scenario 2: below are the 2 payloads (There are duplicate "id":"1")

<instance><simple_crf_v5 xmlns:enk="http://enketo.org/xforms" xmlns:jr="http://openrosa.org/javarosa" xmlns:oc="http://openclinica.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="sc" version="5">
          <SECTION1>
            <GroupG>
              
              
            <item1_comment oc:queryParent="item1">{"queries":[{"type":"comment","id":"2","date_time":"2017-03-16 13:35:32 -04:00","comment":"Automatic query for: validation error message","status":"update","assigned_to":"","notify":false,"user":"root"},{"type":"comment","id":"1","date_time":"2017-03-16 13:35:00 -04:00","comment":"closing the query","status":"closed","assigned_to":"","notify":false},{"type":"comment","id":"1","date_time":"2017-03-16 13:34:41 -04:00","comment":"Automatic query for: validation error message","status":"new","notify":false,"user":"root"}]}</item1_comment></GroupG>
            
          </SECTION1>
          
        </simple_crf_v5></instance>

        
<instance><simple_crf_v5 xmlns:enk="http://enketo.org/xforms" xmlns:jr="http://openrosa.org/javarosa" xmlns:oc="http://openclinica.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="sc" version="5">
          <SECTION1>
            <GroupG>
              
              
            <item1_comment oc:queryParent="item1">{"queries":[{"type":"comment","id":"3","date_time":"2017-03-16 13:35:59 -04:00","comment":"Automatic query for: validation error message","status":"update","assigned_to":"","notify":false,"user":"root"},{"type":"comment","id":"2","date_time":"2017-03-16 13:35:32 -04:00","comment":"Automatic query for: validation error message","status":"update","assigned_to":"","notify":false,"user":"root"},{"type":"comment","id":"1","date_time":"2017-03-16 13:35:00 -04:00","comment":"closing the query","status":"closed","assigned_to":"","notify":false},{"type":"comment","id":"1","date_time":"2017-03-16 13:34:41 -04:00","comment":"Automatic query for: validation error message","status":"new","notify":false,"user":"root"}]}</item1_comment></GroupG>
            
          </SECTION1>
          
        </simple_crf_v5></instance>

**Comment by jkeremian** [comment]
Hi @MartijnR 
I merged your latest code. Not sure if you checked in any code to address this issue, but it looks like this is not an issue any more. I'm getting now single payload. thanks. I keep you posted.

**Comment by MartijnR** [comment]
Huh, that's weird. I haven't addressed it! :)

I was about to write to suggest to show during the meeting what happens when the close button is clicked, because I'm pretty sure it has something to do with iframe.

**Comment by MartijnR** [comment]
Aha, it was the 'update' vs 'updated' I think (see the form logic)! The auto-query didn't resolve the constraint.

Still should prevent the autoAddQueries routine to not run again when the iframe is closed I think.

**Comment by jkeremian** [comment]
I see
