### ISSUE TITLE
When multiple items in a select_multiple item are selected, Enketo is not rendering them as selected when re-opening the form in Edit mode

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#685]
If a user clicks on just one checkbox in an item, closes the form and re-opens it, Enketo is correctly rendering the selected item.

If a user clicks on multiple items in a checkbox, closes the form and re-opens it, Enketo is not rendering any of the checkboxes as selected.

The data is correctly saved in OC in either scenario.

**Comment by MartijnR** [comment]
I am not able to reproduce this. E.g with:

https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmp3_w_8yv7/default.xml (a, b and c)

https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmp3_w_8yv7/default.xml&d[%2Fdefault%2Fs1]=d%20e (d and e)

Is it possible that the instance isn't correctly re-recreated from the db on the OC side, before it is sent to Enketo? Multi-select values are space-separated.

**Comment by MartijnR** [comment]
removed second link because github mangles it

**Comment by jbonica** [comment]
@MartijnR 

Thanks for the feedback. Let me check with an OC Dev.
