### ISSUE TITLE
Enketo doesn't work using authenticated forms and setting "base path"

### ISSUE THREAD

**Issue by rhunwicks** [kobotoolbox/enketo-express#693]
Setting the `ENKETO_PREFIX` environment variable allows Enketo to run at a subdirectory URL, e.g. https://survey.example.com/enketo/ and this works correctly for public forms.

However, if the Forms server is setup to require authentication then Enketo fails.

When you open a Form URL, Enketo detects that the form needs authentication and it redirects to `/login` from the code in `public/js/src/main-webform.js:_showErrorOrAuthenticate`. This URL can't be reached if Enketo is running with a URL prefix.

If you change that function to include the correct prefix then the Enketo correctly prompts the user for a username and password when required.

There is an almost identical function in `public/js/src/main-webform-edit.js:_showErrorOrAuthenticate` that probably should be changed as well.

Finally, the URL is listed in `public/src/module/controller-webform.js:_submitRecord` in the contents of the `authLink` variable. This variable is used to populate the contents of the dialog box prompting the user to log in in another window. It should also reflect the correct prefix. However, as it stands it doesn't seem to show a clickable link anyway, because the text seems to rendered as plain text - the <a> tag isn't interpreted as HTML .  See the attached screenshot:

![enketo auth dialog](https://cloud.githubusercontent.com/assets/1317567/24334167/6303c70e-126e-11e7-833f-b4219035c889.png)

It is probable that `src/js/module/gui.js:confrmLogin` also needs to be updated, but I haven't actually been able to trigger that function in order to check.

**Comment by rhunwicks** [comment]
I can confirm that `src/js/module/gui.js:confrmLogin` also needs to be updated, in order to allow prompting for username and password when syncing records entered in offline mode.

**Comment by MartijnR** [comment]
Excellent. Thanks. Would you be able to submit a PR for this perhaps?

I split the rendering issue off into https://github.com/kobotoolbox/enketo-express/issues/694

**Comment by rhunwicks** [comment]
> Would you be able to submit a PR for this perhaps?

Sure.

Is there a recommended way to get the config as an object - it's not currently available in the code in `public/js/src` the way it is in, say, `app/controllers/auth-controller` - I am assuming I need to get access to `app.get( 'base path' )`?

**Comment by MartijnR** [comment]
The code in public is client-side code which will have the settings available in settings.js 
```js
var settings = require('settings');
var path = settings.basePath;
```

On the server-side, if necessary, this can be done as you mentioned (in a router) or anywhere else with 
```js
var config = require( './app/models/config-model' );
var path = config.server['base path'];
```
