### ISSUE TITLE
Make asterisk dynamic for dynamic required

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#699]
https://github.com/enketo/enketo-core/issues/413

**Comment by pbowen-oc** [comment]
I don't think this is working fully.  I have field1 set to be required when field2 != ''.  When I open a new form where field2 is '' (and therefore field1 is not required), the asterisk is appearing next to field1.  Only when I interact with these fields does it appear to evaluate the required expression and show/hide the asterisk as expected.

**Comment by MartijnR** [comment]
Yes, sorry I forgot to explain how the way this has been implemented:

If the input field is validated to show feedback to user, it will hide/show the asterisk.

If validateContinuously is set to true, this is nearly real-time, except upon load.

Otherwise, it occurs when the field itself is updated by the user or the Validate/Submit button is clicked or upon pageflip (if validatePage is set to true)

Doing this upon load is possible with a performance hit. However, looking at the way I thought OC was going to use this feature (required unless bypassed), I figured evaluating upon load wasn't critical.

**Comment by pbowen-oc** [comment]
If an existing form is a opened with a required field already bypassed with a query from the previous session, I think it would be better to be consistent and not show the asterisk for that field starting at form load.

We can discuss the potential performance implications to determine if it would be better to revert to the prior behavior.

**Comment by MartijnR** [comment]
Yes, that makes sense. Maybe we use the `"validate continuously"` setting to check upon load.

**Comment by MartijnR** [comment]
OC would like to hide asterisk if field has value. Can engine be made more modular to do this?

**Comment by MartijnR** [comment]
* [ ] during traversal
* [ ] also when you load a record
