### ISSUE TITLE
dn valuechange audit not added for calculated values

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#701]
https://jira.openclinica.com/browse/OC-7963

**Comment by MartijnR** [comment]
* [ ] listen for inputupdate.enketo event
* [ ] make sure inputupdate.enketo event only fires when the value **changes**

**Comment by MartijnR** [comment]
This approach will only work for calculations that have a form control

**Comment by MartijnR** [comment]
Problem is that widgets are initialized after calculations.

**Comment by MartijnR** [comment]
misunderstood issue. Readonly field never gets auto-audit-log for changed value (see Paul's Vital Signs).

**Comment by MartijnR** [comment]
* [x] not adding audit log when calculated readonly value updates after load
* [ ] not adding audit log when calculated readonly value updates at load

**Comment by MartijnR** [comment]
Issue:

1. calculated item has dn widget
2. value of item changes during load (e.g. today's date)

Seen: since dn widget initializes after calculating items during load, it doesn't detect the value change and therefore doesn't add the log "value changed from '' to '2017-05-05'". No log is added.

Expected: the log "value changed from '' to '2017-05-05'" to be added.

**Comment by MartijnR** [comment]
Problem is that repeat.init has to come after calc.init and widgets.init has to come after repeat.init.

I don't really see a way to implement a 'fix' that won't breaks tons of things.

**Comment by pbowen-oc** [comment]
I confirmed that we are ok with not showing the value change for a calculation made on form load in the current session.  I think this issue can be closed since audit after load appears to be working now.
