### ISSUE TITLE
Grid Theme styling improvements

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#707]
Now:
- [x] dn pulldown assigned_to has no border in Grid theme
- [x] The + icon inside the add-repeat button is slightly off-center (seen in Grid Theme)
- [x] OC ONLY: in Grid theme, the - icon inside the remove-repeat button is not perfectly centered vertically
- [x] appearance="horizontal" with images and text, 4 fields, last field gets full width of 2nd row, see image in next comment (not sure if bug or need to use appearance="horizontal-compact")

Later:
- [x] change styling of readonly input field (transparent bg + grey text) - Not done, but I forgot the purpose (reduce scope for confusion, I think, but I don't remember for what kind of confusion)
- [x] ~~disabled cursor to be shown in note fields without input (and without calculate)~~ - NOT SURE, I'd rather let the cursor be the same as when hovering over any question label.
- [x] DN icon interferes with label (see image 2 comments below)
- [x] second page with group (field-list) has no top-border http://localhost:8005/single/fs/i/::YYYv
- [x] second page with group (field-list) WITHOUT TITLE has no top-border
- [x] hide disabled + button?

**Comment by MartijnR** [comment]
![image resizing issue](https://cloud.githubusercontent.com/assets/627350/25859738/b06ab624-349c-11e7-9889-2d591eaf6863.png)

**Comment by MartijnR** [comment]
<img width="323" alt="screen shot 2017-08-04 at 11 33 50 am" src="https://user-images.githubusercontent.com/627350/28979891-e5a35dae-7908-11e7-9594-bc9c0fe7e0c2.png">

**Comment by MartijnR** [comment]
to reproduce issue with images use Kitchen sink and 


```js
[...document.querySelectorAll('img')].forEach( (img) => img.src='https://enke.to/media/get/https/api.ona.io/enketo/xformsMedia/77509/157136.png')
```
<img width="1048" alt="screen shot 2018-05-03 at 3 21 21 pm" src="https://user-images.githubusercontent.com/627350/39603950-723dc97a-4ee7-11e8-8665-6b0418d1d6c1.png">

**Comment by MartijnR** [comment]
~~strikethrough~~

**Comment by MartijnR** [comment]
Try to eliminate the difference between a note (without calc or default) and a readonly field with a calculation.

**Comment by pbowen-oc** [comment]
@MartijnR - I'm seeing the correct styling now (read-only items now having the style of note items), but I'm seeing an issue. If my read-only item has a constraint on it, the constraint message is not updating dynamically as the result of my calculation changes. Instead, the constraint message is either showing or not showing based on the result of the calculation at the time the form was loaded.

**Comment by MartijnR** [comment]
Ok, thanks. Do you know if this was this updating correctly before?

**Comment by pbowen-oc** [comment]
I just tested on an older deployment and it was not updating within the session there either, so it looks to be unrelated to the work in this ticket.

**Comment by MartijnR** [comment]
moved to #1098

**Comment by pbowen-oc** [comment]
For the read-only and note item styling, it looks like it is not working for rows 2+ in a repeating group (screenshot from my test form):
![2018-08-09 18_44_01-openclinica](https://user-images.githubusercontent.com/25179620/43929925-eb51d936-9c04-11e8-914b-a67c212c3bcd.png)

**Comment by MartijnR** [comment]
* [ ] fix: new repeat questions don't get readonly class on label
