### ISSUE TITLE
Tabbing between input and dn icon

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#709]
Make visually clear focus style.

Also check Grid Theme

**Comment by MartijnR** [comment]
No focus border with radiobuttons and checkboxes at all.

**Comment by pbowen-oc** [comment]
Can we skip over DN fields and just tab between input fields? DN fields would not be accessible using the keyboard only.

**Comment by MartijnR** [comment]
Yes, should be fine. Will do.
