### ISSUE TITLE
Move to specific question upon load

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#711]
Tbc whether DN should be opened automatically

**Comment by pbowen-oc** [comment]
Ideally the DN would be opened automatically.

**Comment by MartijnR** [comment]
we can either implement this with a proper fragment identifier for online-only forms only or use a query parameter across Enketo. It seems to me that online-only should be fine for this feature

**Comment by MartijnR** [comment]
Another option from #543:

2 options:

Use focus attribute in XForm. The first question with that attribute would get focus.

Seems prefer if we can assume that we will never need this feature in an offline-capable webform. I think we can even go further and only enable this feature in the special 'edit' webform view (though OC may require it in the regular webform as well).

**Comment by MartijnR** [comment]
example.com/::abcd#/path/to/repeated[3]/node

**Comment by MartijnR** [comment]
Could be implemented in Enketo Core with a configuration item allowing it to be switched off (for offline-capable forms) and adding the parameter to all online-only API endpoints.

* [ ] add to enketo-core with config
* [ ] add to enketo-express online-only views only
* [ ] add to API v2 online-only views only
* [ ] update API documentation

**Comment by MartijnR** [comment]
this may also work out of the box //rep[@enk:ordinal="2"//question

**Comment by MartijnR** [comment]
This all works, so it should be quite straightforward to do on the OC side if nested repeats are not used: 

* absolute path: http://example.org/form#/path/to/node
* search first node: http://example.org/form#//node
* target child of specific repeat: http://example.org/form#//repeat[3]/node
* target descendent of specific repeat: http://example.org/form#//repeat[enk:ordinal="3"]//node

**Comment by MartijnR** [comment]
@pbowen-oc this is ready for testing in enketo-express-oc
