### ISSUE TITLE
Imagemap widget for select_one and select_multiple

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#720]
SVG image with id attributes that correspond to option values in the itemset. The radiobuttons/checkboxes will be replaced by making the SVG image regions clickable.

* [x] propose feature (appearance="image-map") to ODK group => https://github.com/opendatakit/xforms-spec/issues/108
* [x] check for, or add, SVG image support
* [x] figure out how to swap `<img src>` with `<picture> <svg>...</svg></picture>` or similar manipulatable syntax
* [x] figure out the previous technique for resources loaded from indexedDb (currently converted to URL which won't work)
* [x] unselect functionality
* [x] readonly state
* [x] translations (using a different label)
* [x] loading default value
* [x] changing value with calculation
* [x] test repeats
* [x] svg scaling, incl if width, height attributes are missing
* [x] tooltips with label (in current active language)
* [x] if no option match for path[id], do not show hover effect? Can be done by removing IDs that have no match.
* [x] resolve img load flickering

Not considered part of requirements:

* translations using a different image
* fix IE11 SVG scaling
* keyboard accessibility
* ~intelligent color picking (but I think theme color is okay, users can switch themes if needed formhub/kobo)~

**Comment by MartijnR** [comment]
test form: https://docs.google.com/spreadsheets/d/1JS-3wUKKqPhYGaoxJiKoJZsUik-UVwS_-oQHB_g21uw/edit?usp=sharing

**Comment by MartijnR** [comment]
We should probably not use color fills for _selected_ status, as this will interfere with the image-customization widget. I think the `:hover` state could be the same a the `[or-selected]` state and just apply an opacity.

**Comment by MartijnR** [comment]
in Ona with the widgets form, the same SVG image is requested twice, but simultaneously (with slightly different turnaround times) in Chrome, Safari.

<img width="1746" alt="screen shot 2018-02-23 at 2 23 03 pm" src="https://user-images.githubusercontent.com/627350/36617582-3520193a-18a5-11e8-8e79-adec86431722.png">
<img width="1623" alt="screen shot 2018-02-23 at 2 21 32 pm" src="https://user-images.githubusercontent.com/627350/36617583-3671ec64-18a5-11e8-824a-bc06b3361523.png">

**Comment by plutext** [comment]
test form above https://docs.google.com/spreadsheets/d/1JS-3wUKKqPhYGaoxJiKoJZsUik-UVwS_-oQHB_g21uw/edit?usp=sharing gives an error in kobotoolbox preview: "sequence item 2: expected string or unicode"

**Comment by MartijnR** [comment]
Thanks for reporting this. It may have been resolved in later versions of Enketo. This is the same form (hosted on ODK Aggregate) on the latest version: https://enke.to/::YY1u. Previews (only previews) may show an 'SVG not found error' in the latest Enketo, if the backend (KoBo) doesn't use some trickery to resolve media URLs in the XForm).
