### ISSUE TITLE
OC only: Irrelevants with value will never hide or clear

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#744]

**Comment by MartijnR** [comment]
In fieldsubmission view:
1. field becomes irrelevant
2. value clears in model
3. fieldsubmission for empty value is sent
4. field becomes relevant
5. desired: for the previously-deleted values to come back in both view and model and trigger fieldsubmissions.

**Comment by pbowen-oc** [comment]
@MartijnR - Can you add this to our next milestone?

**Comment by MartijnR** [comment]
check if enketo-core can be customized in OC this way

**Comment by MartijnR** [comment]
Alternatively, branch.js customized to only disabled when field has no value but show a new error message if irrelevant.

**Comment by MartijnR** [comment]
see new title...

**Comment by MartijnR** [comment]
What about groups with relevant expression?

**Comment by MartijnR** [comment]
* support for oc:relevantMsg
* if irrelevant and no value -> no change
* if irrelevant and value -> new ConstraintError state which will show oc:relevantMsg (requiredError and RelevantError are mutually exclusive, and RelevantError has precedence over ConstraintError
* if irrelevant and value -> Do not clear value (ever!)
* let IrrelevantError not influence state of record, i.e. submissions can go ahead

**Comment by pbowen-oc** [comment]
If group has a relevant expression that is false and only one field inside it has a value, can the RelevantError be displayed only on that one field?

**Comment by MartijnR** [comment]
wrt groups, the issues are:
- displaying error message on question that is defined in the bind for the group
- identifying the questions with a value

**Comment by MartijnR** [comment]
https://enketo-aggregate.appspot.com/www/formXml?readable=true&formId=relevant-constraint-required

[relevant-constraint-required.xml.txt](https://github.com/kobotoolbox/enketo-express/files/1140227/relevant-constraint-required.xml.txt)

**Comment by MartijnR** [comment]
Some options for indicating which non-empty question in a group are problematic:

* background color 
* copy field labels to display in group error message

**Comment by pbowen-oc** [comment]
I'm looking at the implementation deployed so far, and I see an issue with interaction with constraint messages. I have two fields that each have the same relevant expression (at the field level, not at the group level). Each also has a required expression and one has a constraint. Initially, when the fields are made relevant they display a constraint error message and/or a required field asterisk as expected. However, once I make the fields irrelevant while they both have values, they stop displaying constraint messages and required field asterisks until both are cleared at the same time.  

Separately, I have a dropdown field with a relevant expression. I selected a value and then made it irrelevant, Once I did this, the dropdown became read-only regardless of how the relevant expression evaluated (so it became stuck in the error state).

I can demonstrate both of these for you today.

**Comment by MartijnR** [comment]
* [ ] css order of relevant message

**Comment by MartijnR** [comment]
To discuss:
* are "relevant" expressions on dn questions there for a reason? If not, don't add them.

**Comment by MartijnR** [comment]
remaining under this issue: group relevant behavior.

**Comment by pbowen-oc** [comment]
I found the following issues using my test form. 

I made weight, height, and units relevant. I entered values that were out of range and observed the constraint error messages. I made these fields irrelevant. As expected, the irrelevant error replaced the constraint errors. I made the fields relevant again. I expected the constraint messages to return, but they did not.

I opened the query widget for a field showing the irrelevant error. The query widget text field showed the irrelevant error, too. That error should only display on the field, not the query widget.

**Comment by MartijnR** [comment]
Thanks. The second part can be fixed. The first tbc.

* [ ] don't add relevant error message as default for query
* [ ] see if it's possible to re-run constraint/required validation after relevant evaluation returns true

**Comment by MartijnR** [comment]
@bowen-oc: I think that the relevant-error-msg-displayed-in-the-query-widget issue is related to the query question having a relevant expression. It seems the behavior is correct. It doesn't turn the relevant error message into the default query value.

**Comment by MartijnR** [comment]
Problem with implementing remaining point is making a distinction between question that previously showed a constraint/required error, and question that were never reached by the user (including upon load).

**Comment by MartijnR** [comment]
required validation not required, so we could do constraint validation only and end up with an okay result. 

Requires splitting up required and constraint evaluation in Enketo Core.

**Comment by pbowen-oc** [comment]
I'm seeing an issue with the current implementation when I follow these steps:
1. Enter data in a required field
2. Make that field irrelevant (observe that is has the relevant error message and does not have the required field asterisk) 
3. Close the form
4. Reopen the form

Observe that the field has the irrelevant error message as expected, but it also has an asterisk to indicate that it is required. That shouldn't be there since it has a value.  Making the field relevant again still leaves it with the required asterisk even though it has a value.

You can observe this with the temperature fields on my test form.

**Comment by MartijnR** [comment]
reproduce with:

```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance_id=a&instance=<demo-vitals-grid><page1><temp_yn>2</temp_yn><temp>3/temp></page1></demo-vitals-grid>" http://localhost:8005/api/v2/instance/view
```

**Comment by MartijnR** [comment]
Validation of question `temp` returns undefined upon load.

**Comment by MartijnR** [comment]
see if this work can start this Friday after QA tests field-level feature

**Comment by MartijnR** [comment]
* [ ] figure out how this can be implemented for groups
* [ ] for groups display error at group level
* [ ] do not forget Grid Theme

**Comment by MartijnR** [comment]
The most challenging issue to remove a group relevant error when all of its problematic question descendants have been emptied.

Maybe a good approach is let to the `activate` function check for any ancestor group element with a relevant error, and if found trigger a re-evaluation of that group's relevant expression.

**Comment by MartijnR** [comment]
@kkrumlian the group-level (ir)relevant behavior is now ready for testing in master. :shipit:
