### ISSUE TITLE
nested repeats issues?

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#746]
https://www.flowdock.com/app/kobotoolbox/support/threads/2510k0EzQiJJptNXNT_gvJUXsgc

> 1. If you enter 2 partners, and a few camps for each partner, and when I save & reload the draft, or submit & edit the submission, the camps of the second partner will always have only one camp (the first camp entered) and the rest disappears from the form (they are actually hidden). This is the first problem.

> 2.    But in addition, if the number of the camps for the second partner is greater (let’s say 5) than that of the first partner (let’s say 3), next time when you reload or edit, you will see the # of camps for the first partner being increased from 3 to 5 (2 additional repeat boxes are empty and prevent the form to finish).

**Comment by danielduhh** [comment]
Im having the same issue ! @MartijnR

**Comment by MartijnR** [comment]
Thanks @danielduhh. Your form is using repeat count for both levels of repeats, right?

**Comment by danielduhh** [comment]
@MartijnR right

here's a copy

[aimform_REDFS2019.xlsx](https://github.com/kobotoolbox/enketo-express/files/1005722/aimform_REDFS2019.xlsx)

**Comment by MartijnR** [comment]
Thanks! If you're REALLY like to help, it would be great to get a reduced version of that form (<10 rows) that I can reproduce the issue with. Your form has about 20 repeats, and I have no idea where the issue would occur ;).

**Comment by danielduhh** [comment]
good idea @MartijnR - here ya go, select Regional Project scope and go from there

[minified-aimform_REDFS2019.xlsx](https://github.com/kobotoolbox/enketo-express/files/1005771/minified-aimform_REDFS2019.xlsx)

**Comment by MartijnR** [comment]
Thank you. I think your issue is different @danielduhh . It looks like a choice_filter issue. I filed it here: https://github.com/kobotoolbox/enketo-express/issues/747

**Comment by MartijnR** [comment]
Can be reproduced with 1.41.1 and 
[testing_loops.xml.zip](https://github.com/kobotoolbox/enketo-express/files/1008430/testing_loops.xml.zip)

* [ ] check if reproducible on latest

**Comment by MartijnR** [comment]
Phew, it's not reproducible on latest: https://enke.to/x/#YYQa
