### ISSUE TITLE
choice-filter in nested repeats

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#747]
[bug747.xlsx](https://github.com/kobotoolbox/enketo-express/files/1005954/bug747.xlsx)

1. select Tigray
2. created 2nd Section-Name repeat

Expected: Both Q33 to have same choices
Actual: The second Q33 has no choices

**Comment by MartijnR** [comment]
It seems that creating another nested repeat instance is not triggering initialization of its itemsets.

**Comment by MartijnR** [comment]
Caused by ${region} not being a part of the `nodes` properties of the `updated` object. It would be best to initialize all itemsets in a newly cloned repeat.

**Comment by MartijnR** [comment]
* [ ] create a test to avoid future regressions

**Comment by danielduhh** [comment]
Should `rm -rf node_modules/enketo-core` enketo-core and re, npm install? Then build? @MartijnR

**Comment by MartijnR** [comment]
The [regular update procedure](https://github.com/kobotoolbox/enketo-express#how-to-update) should be fine.

**Comment by danielduhh** [comment]
I tested out your form 747.xlsx and functionality worked as expected; However when testing my simplified form 
[minified747.xlsx](https://github.com/kobotoolbox/enketo-express/files/1009148/minified747.xlsx), the select one drop downs do not render repeated choices 

![blank-nested-repeat](https://cloud.githubusercontent.com/assets/1947857/26176920/9a0b9f12-3b0c-11e7-8baf-579e943bf01b.png)

This seems related to the original choice-filter issue. Are you able to duplicate?

@MartijnR

**Comment by MartijnR** [comment]
I believe you discovered another bug! 👍 :)

This looks indeed very similar but related to `relevant` instead. I've created an issue here: https://github.com/kobotoolbox/enketo-express/issues/748 and will investigate.

P.S. I just noticed a spelling error in one of the columns: contraint_massage instead of constraint_message.
