### ISSUE TITLE
Media files in a repeat group not displayed after the first entry

### ISSUE THREAD

**Issue by bmalina** [kobotoolbox/enketo-express#761]
Hi Martin

A form with attached media files choices for a select_one question in a repeat group are not displayed after the first entry is entered. The images are displayed well on the 1st repeat entry. The client has mentioned that this was working last week.

![image](https://user-images.githubusercontent.com/20789710/27122440-59315b92-50f3-11e7-9ad3-717cce17ffc2.png)

Sample form: https://ona.io/onahelp/2839/51147
Enketo url:  https://enketo.ona.io/x/#Ynv3
XLSForm: [bird_survey.xlsx](https://github.com/kobotoolbox/enketo-express/files/1073948/bird_survey.xlsx)
Enketo version: 1.47.0
Please note that the online version of the form https://enketo.ona.io/::YkW9 works as expected and the media files are displayed for all the repeat group entries.

**Comment by MartijnR** [comment]
Thanks!

It looks like a regression after the introducing dynamic repeat count.

**Comment by MartijnR** [comment]
local link: http://localhost:8005/x/#YYpw
