### ISSUE TITLE
Required validation unexpected

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#767]
field 1: is required, and has constraint with dependency on field 2
field 2: 

If field 1 is untouched, and field 2 is edited, the error message 'This field is required' is shown for field 1.

Expected: The constraint error message is shown instead.

Requires separating validation types in Enketo Core.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#70
