### ISSUE TITLE
Do not print irrelevant questions when loading a record

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#774]
For empty forms, it makes sense to print irrelevant questions. For records it does not.

**Comment by MartijnR** [comment]
Is this relevant or desired by OC?

**Comment by MartijnR** [comment]
for now /survey all and /instance not irrelevant parts

**Comment by MartijnR** [comment]
* [ ] add support for .print-relevant-only class on form element for regular themes
* [ ] same for grid theme
* [ ] apply the class in EE

**Comment by pbowen-oc** [comment]
Can we print irrelevant fields only when we have a read-only new record (/survey)? Is it possibly to have Preview mode print irrelevant fields, too?

**Comment by MartijnR** [comment]
yes, to both. We can do that in the OC fork

**Comment by MartijnR** [comment]
When you say 'read-only' do you mean to include 'discrepancy-note-only'?

**Comment by pbowen-oc** [comment]
I don't think we are using discrepancy-note-only /survey view (just edit-mode and full read-only for /survey).

**Comment by MartijnR** [comment]
ah yes! thanks!
