### ISSUE TITLE
OC only: Ideas for OC API

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#780]
All are fieldsubmission, all are iframe-optimized, all are POST requests for /oc/api/v1

* **/survey/collect** (new, no close button in dn widget)
* **/survey/collect/c** (same but with close button in dn widget)
* **/survey/view** (new, readonly)
* **/survey/preview** (new, preview, no submit)
* **/instance/edit** (existing, no close button in dn widget)
* **/instance/edit/c** 
* **/instance/edit/rfc** future addition
* **/instance/edit/rfc/c** future addition
* **/instance/view**
* **/instance/view/pdf** future addition
* **/instance/note**
* **/instance/note/c**

All responses have `url` property.

**Comment by MartijnR** [comment]
also form previews (whose implementation would duplicate the regular api/v2)

**Comment by MartijnR** [comment]
for a transition period support both

**Comment by MartijnR** [comment]
1. First create new API
2. Add config option to disable old APIs to facilitate easy testing on the OC side that all endpoints have been updated
3. After all is updated in OC, the old OC api endpoints can be removed

**Comment by MartijnR** [comment]
* [ ] file structure
* [ ] tests
* [ ] es6 conversion of new files
* [ ] refactor

**Comment by MartijnR** [comment]
@pbowen-oc are you using both empty previews (where users enter data to test form logic) as well as readonly empty forms?

**Comment by pbowen-oc** [comment]
@MartijnR  - Yes, we use both.

**Comment by MartijnR** [comment]
@pbowen-oc, @kkrumlian, the beautiful brand new **/oc/api/v1** is ready for testing in the `feature/oc-api` branch (which is on top of the current master).

The old API has been removed in that branch, to easily see which old endpoints need to be updated on the OC side, as none of the existing calls will work any more.

The documentation is [here](https://github.com/OpenClinica/enketo-express-oc/blob/feature/oc-api/doc/oc-api.md).

Note, as described, the responses to all POST calls now return a `url` property now, to simplify things further, so it's not just the endpoints that need updating, but also the response handling.

Let me know when you find issues or when you're ready to get this merged into `master`.
