### ISSUE TITLE
OC only: parsing datetime string in dn something results in "error"

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#783]
The issue seems to be that the Elapsed Time can be negative (showing "error").

**Comment by MartijnR** [comment]
precision is 1/1000 second, so that's not the issue

**Comment by MartijnR** [comment]
Could not reproduce, so I added some logging that should help us figure out why 'error' is displayed instead of "Just now". @pbowen-oc please check the console for helpful error messages (1 or 2) when the issue occurs again.

**Comment by pbowen-oc** [comment]
@MartijnR - We haven't had reports of this occurring again. I'll let you know if we do see it again.

**Comment by pbowen-oc** [comment]
@MartijnR - Our testers are seeing this again. Here is one the console shows when the Query Widget is loaded. They said that after about a minute the timestamp reverts to displaying "Just now" or "1 minute(s)". It seems like this is relatively easy for us to reproduce at the moment.

enketo-webform-fs-bundle.min.js:1 Could not parse elapsed time for elapsed milliseconds: "-31966"

  i._parseElapsedTime       @ enketo-webform-fs-bundle.min.js:1
  i._getParsedElapsedTime   @ enketo-webform-fs-bundle.min.js:1
  i._getRows                @ enketo-webform-fs-bundle.min.js:1
  (anonymous)               @ enketo-webform-fs-bundle.min.js:1
  i._renderHistory          @ enketo-webform-fs-bundle.min.js:1
  i._showCommentModal       @ enketo-webform-fs-bundle.min.js:1
  (anonymous)               @ enketo-webform-fs-bundle.min.js:1
  dispatch                  @ enketo-webform-fs-bundle.min.js:1
  g.handle                  @ enketo-webform-fs-bundle.min.js:1

**Comment by MartijnR** [comment]
Ah great. The logging is helpful. It's trying to pass a negative difference of 32 seconds. This could be caused by an incorrect time on either the server or the user's computer (that added the query).

We could parse negative values to "Just now" if it's always this small of a difference.

**Comment by MartijnR** [comment]
* [ ] have a quick look at code

**Comment by pbowen-oc** [comment]
I confirmed that setting my computer time back 20 minutes results in a large negative difference.

As a short term fix to handle clocks that are off by a small amount, can we show up to -2 minutes as "just now"?

As a longer term improvement, I think we should get away from using the user's local clock in these calculations for historic events and only calculate them based on server time. Or if that isn't feasible, calculate a local time offset at form load and use this as an adjustment factor for all of the historic event time displays on the form. That should protect against everything except someone changing their computer clock while the form is open (which I don't think we need to worry about).

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#73
