### ISSUE TITLE
OC only: in partially and 100% readonly fs views, change submission feedback message

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#784]
* [x] ~~100% readonly, need to customize common webform view
"Form is readonly"~~
* [x] In dn-only: something else, tbc.  "All **query** changes saved" perhaps

Or disregard this and do it in the iframe parent window instead (perhaps just change in string "changes" to "query changes")

**Comment by pbowen-oc** [comment]
For both partial and 100% read-only modes, the desired behavior is to replace the submission feedback message with "You are in read-only mode."  It should say this as soon as the form is opened and remain constant even if queries are saved.

**Comment by MartijnR** [comment]
* [ ] fieldsubmission readonly + note-only views
* [ ] common readonly views

**Comment by MartijnR** [comment]
> For the status message, can we update it depending on full/partial read-only mode as follows?
> Full read-only mode - "You're in read-only mode."
> Partial (queries-only) read-only mode - "You're in review-only mode."
> Can we increase the length allowed at the top of the form for these? The current message is being truncated even at full form width.

**Comment by pbowen-oc** [comment]
@MartijnR - I'm seeing the correct "review-only" status message, but in full read-only view, there is no status message.

Also, I'm not seeing a Close button or Complete button in Edit mode, full read-only mode, or partial read-only modes (ie, I don't see it anywhere). I'm not sure if that was caused by this issue or another one.

**Comment by MartijnR** [comment]
Thanks! Those were all caused by the same regression when introducing the PID feature (they were broken if PID was missing)
