### ISSUE TITLE
OC only: repeat deletion causes 'Changes not saved error'

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#796]
No request is made for the new repeat itself. In fact, no event is fired when a repeat is created that is listened for in the fieldsubmission-controller. 

I think the cause of the error is for a calculated item inside the repeat.

**Comment by pbowen-oc** [comment]
@MartijnR - Sorry for the confusion. The error I keep seeing is on repeat deletion, not creation. I tested on repeats that had calculated values and those that didn't and both produced the error.

**Comment by MartijnR** [comment]
Ah I'm sorry! That is indeed a special request that perhaps is not supported in OC. Will double-check that it is made correctly and describe how it's done.

**Comment by MartijnR** [comment]
Confirmed that a DELETE /fieldsubmission request is sent to OC when a repeat is deleted. It looks like it is conforming to the spec at https://app.swaggerhub.com/apis/martijnr/openclinica-fieldsubmission/1.0.0. So my guess is that the "delete" method doesn't have a handler yet on the OC side.

example of xml_submission_file_fragment sent with DELETE request (cleaned up whitespace):

```xml
<demo-vitals-grid xmlns:enk="http://enketo.org/xforms" xmlns:jr="http://openrosa.org/javarosa" xmlns:oc="http://openclinica.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="vitals" version="1">
    <page2>
        <bp_rg enk:ordinal="3">
        </bp_rg>
    </page2>          
</demo-vitals-grid>
```

**Comment by MartijnR** [comment]
I don't currently have access to a OC dev server, but you could confirm by checking the response of the DELETE request in the Network tab of the Developer console. If not implemented on the OC side the statusCode is probably 404 or 405.

**Comment by pbowen-oc** [comment]
Thanks, @MartijnR . I checked as you recommended and I see a 500 response. Can you change the title of this issue from creation to deletion to avoid confusion?
@kkrumlian - Can you look into this?

**Comment by pbowen-oc** [comment]
@MartijnR - It looks like this is working correctly for us now.
