### ISSUE TITLE
Missing data after editing a record.

### ISSUE THREAD

**Issue by bmalina** [kobotoolbox/enketo-express#797]
Hi Martijn,

We have a unique case when editing records. A repeat group has 2 select_one questions both having the required field as 'Yes'. The second question has a relevant condition in that it appears once a certain choice is selected in the first question. Find attached the sample form.
[Enketo_tests.xlsx](https://github.com/kobotoolbox/enketo-express/files/1199467/Enketo_tests.xlsx)

Example
1. Collect the data using Enketo and select the option "mango" to have the 2nd question appear and select any option.
2. Once the submission is sent to the Ona server, edit the record using Enketo webform and uncheck the "mango" and select another option then select "mango" again. Submit the changes.
3. When viewing the data in Ona, you notice that for some of the repeat groups the option "mango" is selected in the first question and the second question does not exist in the xml.

Please note that this behavior is intermittent.

Let me know if you require further information.

**Comment by MartijnR** [comment]
thanks @bmalina!

**Comment by bmalina** [comment]
Hi Martijn,

Do you have any feedback regarding this issue?

**Comment by MartijnR** [comment]
reproduce with 

```bash
curl --user enketorules: -d "server_url=https://api.ona.io/enketo&form_id=Enketo_tests&instance_id=a&instance=<Enketo_tests><details><fruits>mango</fruits><location>kiumu</location></details><details><fruits>mango</fruits><location>kisumu</location></details><meta><instanceID>a</instanceID></meta></Enketo_tests>&return_url=https://google.com" http://localhost:8005/api/v2/instance
```

**Comment by MartijnR** [comment]
* [ ] relevant not evaluated when new repeat is created during record loading
* [ ] when selecting 'pear' in second repeat (with curl above) the record to be submitted still contains the existing `<location>kisumu</location>` even though it is irrelevant and should have been cleared

**Comment by MartijnR** [comment]
Glad you found this. Pretty serious regression! I added a test to prevent it from recurring. 

You can either deploy the last commit or wait until the forthcoming patch release 1.50.1 (this week I think). 

Thanks!

**Comment by ukanga** [comment]
This is awesome, thank you.

**Comment by bmalina** [comment]
Thank you Martijn.
