### ISSUE TITLE
nested repeat losing value w/ text datatype

### ISSUE THREAD

**Issue by danielduhh** [kobotoolbox/enketo-express#803]
Hello again @MartijnR !
There's a weird issue w/ text data types losing its value inside a nested repeat. I attached a test form for you

tested on v.1.50.1 (latest version)

Steps to reproduce.
1. Open form via  /api/v2/survey/offline
2. Select "Region" for 23. Project Scope (this is the the parent repeat)
3. Select any value but "other" for 29. Livestock type (i.e. Dairy_cattle)
4. Press the "+" for this child repeat, select "Other" & enter some free text
5. Press "+" for the parent repeat and repeat steps 3/4
6. Repeat step 5
7. Edit form via /api/v2/instance

You will see that the 2nd of 3 child repeats loses its value. The textbox is left blank. However, the 1st and 3rd text values are still present. Also, when skipping step 3, all 3 child repeat free text values persists. Not sure whats going on!  Let me know if you cant reroduce...

[nested-repeat-v5.xlsx](https://github.com/kobotoolbox/enketo-express/files/1219017/nested-repeat-v5.xlsx)

**Comment by MartijnR** [comment]
Thanks @danielduhh. Nice report. Too bad it's about nested repeats  :anguished:...

**Comment by MartijnR** [comment]
* [ ] reproduce in Enketo Core

**Comment by danielduhh** [comment]
hello @MartijnR - any progress with the daunted nested repeats? We've got some people waiting urgently for this issue to be resolved. Anyway I can assist? Thanks!

**Comment by MartijnR** [comment]
I haven't looked at it yet and since it deals with nested repeats (which I am assuming are used by very few), it gets de-prioritized a bit, I must admit.

I see you have already minimized the form, so that's great. The next thing that would help is to provide an XML instance that when loaded into the form reproduces the error. This would be the first thing I'll have to do. It would speed things up a bit if you provided it.

I won't have time to look at this today. Maybe tomorrow.

**Comment by MartijnR** [comment]
Never mind the XML instance.

```xml
<nested-repeat-v5><start>2017-08-15T14:24:26.000-06:00</start><end>2017-08-15T14:24:26.000-06:00</end><today>2017-08-15</today><deviceid>localhost:BgIE8gkFewoARkO3</deviceid><program_info/><project_scope>regional</project_scope><name_of_region><project_focus_areas_livestock><livestock_type>dairy_cattle</livestock_type></project_focus_areas_livestock><project_focus_areas_livestock><livestock_type>other</livestock_type><livestock_type_other>other 1</livestock_type_other></project_focus_areas_livestock></name_of_region><name_of_region><project_focus_areas_livestock><livestock_type>beef_cattel</livestock_type><livestock_type_other/></project_focus_areas_livestock><project_focus_areas_livestock><livestock_type>other</livestock_type></project_focus_areas_livestock></name_of_region><program_information/><meta><instanceID>uuid:e8c03b34-4439-4692-85f1-d6297031cade</instanceID></meta></nested-repeat-v5>
```

**Comment by danielduhh** [comment]
Yeah, I was in the middle of debugging - looks like the xml instance is saved without the missing value. Somewhere in between submitting the form & enketo-express writing the data.json/data.xml, the value goes missing

```
<nested-repeat-v5>
  <start>2017-08-15T13:23:42.000-07:00</start>
  <end>2017-08-15T13:24:45.000-07:00</end>
  <today>2017-08-15</today>
  <deviceid>52.14.154.36:u29LoD6zN54AT02x</deviceid>
  <project_scope>regional</project_scope>
  <name_of_region>
    <project_focus_areas_livestock>
      <livestock_type>sheep</livestock_type>
    </project_focus_areas_livestock>
    <project_focus_areas_livestock>
      <livestock_type>other</livestock_type>
      <livestock_type_other>other name</livestock_type_other>
    </project_focus_areas_livestock>
  </name_of_region>
  <name_of_region>
    <project_focus_areas_livestock>
      <livestock_type>beef_cattel</livestock_type>

    </project_focus_areas_livestock>
    <project_focus_areas_livestock>
      <livestock_type>other</livestock_type>
    </project_focus_areas_livestock>
  </name_of_region>
  <meta>
    <instanceId>uuid:8a363e79-16de-455b-ab13-830d76a408d9</instanceId>
    <instanceName>nested-repeat-v5</instanceName>
    <formId>nested-repeat-v5</formId>
    <submissionTime>2017-08-15T20:29:01.901Z</submissionTime>
  </meta>
</nested-repeat-v5>
```

**Comment by MartijnR** [comment]
Yes, exactly. It looks like it's never stored in the model. So that makes the issue more serious. It's not related to editing but initial collection.

**Comment by MartijnR** [comment]
I think I found the issue and fix! Will write a test and if all is okay deploy this in Enketo Express today.

**Comment by MartijnR** [comment]
@danielduhh The fix in the latest commit in `master`. No new version has been released yet. It would be great if you could confirm this fixed it for you.

Thanks again! Great report.

**Comment by danielduhh** [comment]
@MartijnR - you are the man. Thank you from Seattle & Ethiopia
