### ISSUE TITLE
repeat questions not rendering in /edit

### ISSUE THREAD

**Issue by danielduhh** [kobotoolbox/enketo-express#805]
This may be unrelated issue #803 - The issue itself has some similarities. Child questions inside parent repeat are not rendering the second time around. Label, hint & type are missing.

This is using  commit: https://github.com/kobotoolbox/enketo-express/commit/6a82012ee6cdcc018366c72b215d24e8b3611ea0

I included a simplified form. Here are Steps to reproduce
1. Upload form
2. Open w/ /v2/survey/offline
3. Select regional radio button, select a region & then a zone name
4. Hit the "+" to repeat the parent question & repeat the 3rd step
5. Save and open form w/ /v2/instance

first child question:
![before](https://user-images.githubusercontent.com/1947857/29375461-e7cb1eb8-8269-11e7-8a1b-53cde775323c.png)

second child question w/ missing label, hint & type:
![after](https://user-images.githubusercontent.com/1947857/29375479-fcf25d6a-8269-11e7-8eda-a2793269f4d5.png)

example form:
[repeat-missing-child-example.xlsx](https://github.com/kobotoolbox/enketo-express/files/1228956/repeat-missing-child-example.xlsx)

**Comment by MartijnR** [comment]
Ah I thought we were done! ;) Thanks. I am able to reproduce. This one is related to loading a record with nested repeats (the record itself is okay).

**Comment by MartijnR** [comment]
Thanks for finding and taking the time to report this!

**Comment by danielduhh** [comment]
np, thanks for the swift action
