### ISSUE TITLE
OC only: change query icon colors

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#808]
no query - same as current (no fill)
New - same as current (red/pink)
Updated - change to yellow/orange (try to match the flag color in the attached image file)Inline image 2
Closed - change to black
Closed-Modified - same as current (gray)
![unnamed](https://user-images.githubusercontent.com/627350/29944995-b0ae9c94-8e5c-11e7-96f8-93018c59674f.gif)

**Comment by pbowen-oc** [comment]
Here are the CSS definitions we have for the orange and black colors:

.fa-bubble-orange:before {
  content: "\f075";
  margin: 0 10px 0 10px;
  padding: 0;
  color: orange;
  background: none;
  border: none;
  box-shadow: none;
  opacity: 0.7; }

.fa-bubble-black:before {
  content: "\f075";
  margin: 0 10px 0 10px;
  padding: 0;
  color: black;
  background: none;
  border: none;
  box-shadow: none;
  opacity: 0.7; }

**Comment by MartijnR** [comment]
check if closed-modified is clearly greyer (lighter) than closed
