### ISSUE TITLE
OC Only: check: first repeat irrelevant should not calculate until relevant

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#812]
1. open Vitals
2. Don't change values.
3. Open Vitals and load record created in 2. 

Seen: the repeat is visible with a Relevant Error
Expected: no repeat visibile, no Relevant Error

**Comment by MartijnR** [comment]
tried to reproduce with:

```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance_id=A&instance=<demo-vitals-grid xmlns:enk=\"http://enketo.org/xforms\" xmlns:jr=\"http://openrosa.org/javarosa\" xmlns:oc=\"http://openclinica.org/xforms\" xmlns:orx=\"http://openrosa.org/xforms\" id=\"vitals\" version=\"1\"><page1><ins_note/><rndm>2</rndm><cohort>B</cohort><cohort_note/><temp_yn/><temp/><temp_units/><temp_unit_des>temperature not entered</temp_unit_des><wh_y/><wh_units/><weight/><weight_unit_des>weight not entered</weight_unit_des><height/><height_unit_des>height not entered</height_unit_des><calc_note/><bmi/><bmi_calc>0</bmi_calc><bmi_ro/><bmi_rad/><resp_rate/><pulse/><temp_yn_comment oc:queryParent=\"temp_yn\"/><temp_comment oc:queryParent=\"temp\"/><temp_units_comment oc:queryParent=\"temp_units\"/><wh_y_comment oc:queryParent=\"wh_y\"/><wh_units_comment oc:queryParent=\"wh_units\"/><weight_comment oc:queryParent=\"weight\"/><height_comment oc:queryParent=\"height\"/><bmi_comment oc:queryParent=\"bmi\"/><bmi_rad_comment oc:queryParent=\"bmi_rad\"/><resp_rate_comment oc:queryParent=\"resp_rate\"/><pulse_comment oc:queryParent=\"pulse\"/></page1><page2><bp_yn/><bp_note/><bp_rg><bp_rg_num_init>1</bp_rg_num_init><bp_rg_num>1</bp_rg_num><bp_pos/><bp_sys/><bp_sys_val>0</bp_sys_val><bp_sys_count>0</bp_sys_count><bp_dia/><bp_dia_val>0</bp_dia_val><bp_dia_count>0</bp_dia_count><bp_dt_prec/><bp_dt_ymd/><bp_dt_ym/><bp_dt_y/><date_note/><bp_pos_comment oc:queryParent=\"bp_pos\"/><bp_sys_comment oc:queryParent=\"bp_sys\"/><bp_dia_comment oc:queryParent=\"bp_dia\"/><bp_dt_prec_comment oc:queryParent=\"bp_dt_prec\"/><bp_dt_ymd_comment oc:queryParent=\"bp_dt_ymd\"/><bp_dt_ym_comment oc:queryParent=\"bp_dt_ym\"/><bp_dt_y_comment oc:queryParent=\"bp_dt_y\"/></bp_rg><bp_sys_mean/><bp_dia_mean/><likert_note/><systolic_agreement/><diastolic_agreement/><pain_level/><vas_question/><media_yn/><pic/><ecg_picture/><cascade1/><cascade2/><cascade3/><us_map/><image_map_note/><add_notes/><bp_yn_comment oc:queryParent=\"bp_yn\"/><bp_sys_mean_comment oc:queryParent=\"bp_sys_mean\"/><bp_dia_mean_comment oc:queryParent=\"bp_dia_mean\"/><systolic_agreement_comment oc:queryParent=\"systolic_agreement\"/><diastolic_agreement_comment oc:queryParent=\"diastolic_agreement\"/><pain_level_comment oc:queryParent=\"pain_level\"/><vas_question_comment oc:queryParent=\"vas_question\"/><media_yn_comment oc:queryParent=\"media_yn\"/><pic_comment oc:queryParent=\"pic\"/><ecg_picture_comment oc:queryParent=\"ecg_picture\"/><cascade1_comment oc:queryParent=\"cascade1\"/><cascade2_comment oc:queryParent=\"cascade2\"/><cascade3_comment oc:queryParent=\"cascade3\"/><us_map_comment oc:queryParent=\"us_map\"/><add_notes_comment oc:queryParent=\"add_notes\"/></page2><meta><instanceID>uuid:dc2fd0d4-62fe-47a3-ae83-7057d400a3b0</instanceID><instanceID_comment oc:queryParent=\"instanceID\"/></meta></demo-vitals-grid>&complete_button=false" http://localhost:8005/api/v2/instance/fieldsubmission/iframe
```

I think this issue might be related to how the instance is assembled on the OC side before it's sent to Enketo's API.

**Comment by MartijnR** [comment]
I think no fieldsubmissions are sent for the calculations inside the group/repeat when it becomes irrelevant.

**Comment by MartijnR** [comment]
* [ ]  Calculations are never cleared when they become irrelevant -> send fs for them

**Comment by MartijnR** [comment]
see if there is a way to circumvent this issue

**Comment by MartijnR** [comment]
some things to explore:

* [ ] clear all descendants of a model node when that node becomes irrelevant. Check if view is already cleared correctly (e.g. readonly item with calculation).

**Comment by MartijnR** [comment]
The proper fix would be to remove the distinction between a calculated item with a form control and one without it, by adding calculated items in the DOM where they belong (ie. under a group). However, this is actually very difficult to do in XSLT: https://github.com/enketo/enketo-xslt/issues/31. Right now the ones without a form control are added in a special calculated items section at the bottom of the form.

A pragmatic way to deal with this implementation issue, by circumventing it, is to:

*  Call calc.update when a group becomes relevant or irrelevant. Pass a new type of ‘updated’ object that includes a `group` property` and contains the path of the group that just become relevant/irrelevant.
* Somehow let calc.update find all the nodes in that group with a calculation, including the ones that have no form control, e.g. search for the ‘name/data-name’ attribute that starts with that path?
* Fix enketo-core #458
* Add comprehensive tests for calculated items inside and outside of groups, with or without form controls.

**Comment by pbowen-oc** [comment]
@MartijnR - I'm still seeing this issue but in a slightly different scenario. If I open a new form, close it without interacting with the repeating group, and reopen it, I don't see the relevant error like I did before. However, if I make the repeating group relevant and then irrelevant the first time the form is opened, I'll see the relevant error when I open the form next time. Or, if I don't interact with the repeating group at all the first time the form is opened, and then I later reopen the form, if I make the repeating group relevant and then irrelevant I'll get the relevant error immediately.

**Comment by MartijnR** [comment]
ah, I wonder if this has to do with discrepancy notes. Will try to reproduce

**Comment by pbowen-oc** [comment]
{
    "instance": "<demo-vitals-grid xmlns:enk=\"http://enketo.org/xforms\" ><page1><rndm>5</rndm><cohort>E</cohort><temp_yn></temp_yn><temp></temp><temp_units></temp_units><temp_unit_des>temperature not entered</temp_unit_des><wh_y></wh_y><wh_units></wh_units><weight></weight><weight_unit_des>weight not entered</weight_unit_des><height></height><height_unit_des>height not entered</height_unit_des><bmi></bmi><bmi_calc>0</bmi_calc><bmi_rad></bmi_rad><resp_rate></resp_rate><pulse></pulse><pulse_comment></pulse_comment><cohort_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"E\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:16.158 Z\"}]}</cohort_comment><height_unit_des_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"height not entered\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:16.825 Z\"}]}</height_unit_des_comment><resp_rate_comment></resp_rate_comment><temp_yn_comment></temp_yn_comment><weight_comment></weight_comment><height_comment></height_comment><rndm_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"5\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:15.729 Z\"}]}</rndm_comment><temp_units_comment></temp_units_comment><wh_y_comment></wh_y_comment><temp_unit_des_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"temperature not entered\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:16.329 Z\"}]}</temp_unit_des_comment><bmi_comment></bmi_comment><weight_unit_des_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"weight not entered\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:16.514 Z\"}]}</weight_unit_des_comment><bmi_calc_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"0\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:17.059 Z\"}]}</bmi_calc_comment><bmi_rad_comment></bmi_rad_comment><temp_comment></temp_comment><wh_units_comment></wh_units_comment></page1><page2><bp_yn>2</bp_yn><bp_rg enk:last-used-ordinal=\"1\"  enk:ordinal=\"1\" ><bp_rg_num_init></bp_rg_num_init><bp_rg_num></bp_rg_num><bp_pos></bp_pos><bp_sys></bp_sys><bp_sys_val></bp_sys_val><bp_sys_count></bp_sys_count><bp_dia></bp_dia><bp_dia_val></bp_dia_val><bp_dia_count></bp_dia_count><bp_dt_prec></bp_dt_prec><bp_dt_ymd></bp_dt_ymd><bp_dt_ym></bp_dt_ym><bp_dt_y></bp_dt_y><bp_dia_count_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"0\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:42.508 Z\"},{\"type\":\"audit\",\"message\":\"Value Changed from \\\"0\\\" to \\\"\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:45.817 Z\"}]}</bp_dia_count_comment><bp_dt_y_comment></bp_dt_y_comment><bp_rg_num_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"1\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:41.730 Z\"},{\"type\":\"audit\",\"message\":\"Value Changed from \\\"1\\\" to \\\"\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:44.999 Z\"}]}</bp_rg_num_comment><bp_rg_num_init_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"1\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:41.562 Z\"},{\"type\":\"audit\",\"message\":\"Value Changed from \\\"1\\\" to \\\"\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:44.807 Z\"}]}</bp_rg_num_init_comment><bp_pos_comment></bp_pos_comment><bp_dt_ym_comment></bp_dt_ym_comment><bp_dt_prec_comment></bp_dt_prec_comment><bp_sys_comment></bp_sys_comment><bp_dia_val_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"0\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:42.320 Z\"},{\"type\":\"audit\",\"message\":\"Value Changed from \\\"0\\\" to \\\"\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:45.596 Z\"}]}</bp_dia_val_comment><bp_sys_val_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"0\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:41.927 Z\"},{\"type\":\"audit\",\"message\":\"Value Changed from \\\"0\\\" to \\\"\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:45.183 Z\"}]}</bp_sys_val_comment><bp_sys_count_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"0\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:42.123 Z\"},{\"type\":\"audit\",\"message\":\"Value Changed from \\\"0\\\" to \\\"\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:45.382 Z\"}]}</bp_sys_count_comment><bp_dt_ymd_comment></bp_dt_ymd_comment><bp_dia_comment></bp_dia_comment></bp_rg><bp_sys_mean></bp_sys_mean><bp_dia_mean></bp_dia_mean><likert_group><systolic_agreement></systolic_agreement><diastolic_agreement></diastolic_agreement><diastolic_agreement_comment></diastolic_agreement_comment><systolic_agreement_comment></systolic_agreement_comment></likert_group><pain_level></pain_level><vas_question></vas_question><media_yn></media_yn><pic></pic><ecg_picture></ecg_picture><cascade1></cascade1><cascade2></cascade2><cascade3></cascade3><us_map></us_map><add_notes></add_notes><us_map_comment></us_map_comment><add_notes_comment></add_notes_comment><pic_comment></pic_comment><bp_yn_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value Changed from \\\"\\\" to \\\"1\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:41.384 Z\"},{\"type\":\"audit\",\"message\":\"Value Changed from \\\"1\\\" to \\\"2\\\"\",\"user\":\"root\",\"assigned_to\":\"root\",\"date_time\":\"2017-09-27 19:11:44.617 Z\"}]}</bp_yn_comment><bp_dia_mean_comment></bp_dia_mean_comment><cascade1_comment></cascade1_comment><cascade3_comment></cascade3_comment><bp_sys_mean_comment></bp_sys_mean_comment><ecg_picture_comment></ecg_picture_comment><media_yn_comment></media_yn_comment><cascade2_comment></cascade2_comment><pain_level_comment></pain_level_comment><vas_question_comment></vas_question_comment></page2><meta><instanceID>uuid:1234</instanceID><instanceID_comment></instanceID_comment></meta></demo-vitals-grid>",
    "instanceAttachments": {}
}

**Comment by pbowen-oc** [comment]
<iframe id="enketo" style="position:fixed;z-index:1011;top:0;left:0;width:100vw;height:100vh;" src="http://104.236.18.199:8005/edit/fs/c/i/::e4dd401f78c0f9842652e47c396917d6?instance_id=f374d1dd0600ce6f15f1fe58cfe0e501bb737ded90070320ea4d3885bc0f006f&amp;returnUrl=http%3A%2F%2Fcust7.dev-runtime.openclinica.info%3A8080%2FOpenClinica-cust7%2FMainMenu&amp;completeButton=true&amp;ecid=57374168687088aeb2fa41668ede3c92a3c1015dada4a050de5b5133bddf17bf&amp;parentWindowOrigin=http%3A%2F%2Fcust7.dev-runtime.openclinica.info%3A8080&amp;PID=003">

&lt;script type="text/javascript"&gt;window.NREUM||(NREUM={});NREUM.info={"errorBeacon":"bam.nr-data.net","licenseKey":"9d149a0021","agent":"","beacon":"bam.nr-data.net","applicationTime":671,"applicationID":"49188693","transactionName":"blNUNRcAXhdRVkVdDlcZfDI1Tmchchh4eicWXEURShJFBl1cRRsEV11TFQonXxZdZlRGF1VTQk8PEkA=","queueTime":0}&lt;/script&gt;&lt;/body&gt;

&lt;/html&gt;</iframe>

**Comment by MartijnR** [comment]
Cannot reproduce. The "instance" is not complete. To reproduce I need:

* [ ] the instance (with properly escaped " characters)
* [ ] the XForm

**Comment by MartijnR** [comment]
let me try something else first

**Comment by MartijnR** [comment]
Can reproduce now

* [ ] make it easier to get XForm from views with encrypted IDs
* [ ] fix bug, if bug

**Comment by MartijnR** [comment]
Enketo excludes dn values when it decides to display the relevant error. The way it does that it, e.g. in this case is by looking at the content of `x/page2/bp_rg` in the model and check for each node whether it is a discrepancy note by looking at the view. The model itself has no information about whether a node is a calculation, user input, discrepancy note, etc.

When loading this record the model looks like this:

<img width="666" alt="screen shot 2017-09-28 at 2 46 31 pm" src="https://user-images.githubusercontent.com/627350/30989815-47048ebe-a45c-11e7-93c9-f9fbf4532b64.png">

See for example the node `bp_dia_count_comment` which has a value (provided by OC). There is no matching discrepancy note question in the view for `bp_dia_count_comment` because it is actually a calculated item without a form control. So Enketo has no way of determining whether this value should be ignored.

The algorithm to dynamically add `_comment` nodes needs to be fixed on the OC side.

**Comment by MartijnR** [comment]
I see the `oc:queryParent` attribute. Do you want me to use this instead of checking the view? This attribute is new to me, so I'm not sure if I can rely on it. This wouldn't solve the underlying issue though as `bp_dia_count_comment` should not have been created, I think.

**Comment by MartijnR** [comment]
Might be much easier to dynamically add discrepancy notes to XLSForm instead of XForm

**Comment by pbowen-oc** [comment]
@MartijnR - We have fixed this on our end by  not adding query elements to those fields.
