### ISSUE TITLE
OC Only: Close button behavior for Complete forms in Edit mode

### ISSUE THREAD

**Issue by pbowen-oc** [kobotoolbox/enketo-express#813]
For a Complete form opened in Edit mode, the Close button should have the following functionality:
1. If there are any fields with Relevant errors, the user can only go back to the form to fix the issues.  There is no option to add autoqueries or just leave the form.
2. If there are no fields with Relevant errors, but there are fields with Constraint violations or missing Required fields, the user will have the option of returning to the form to fix the issues or continuing to close the form by adding autoqueries for any fields with Constraint or Required errors.
3. If there are no fields with Relevant, Constraint, or Required errors, the form closes.

**Comment by MartijnR** [comment]
Martijn to continue this work and test with: ```curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=discrepancy-notes&instance_id=A&instance=<discrepancy-notes><meta><instanceID>AA/instanceID></meta></discrepancy-notes>&complete_button=false" http://localhost:8005/api/v2/instance/fieldsubmission/c/iframe```

**Comment by MartijnR** [comment]
Do we need a special message for \#1? I imagine you'd want to somehow guide the user about which errors to fix if there are also constraint errors present.

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, probably one message if there are any relevant errors (regardless of constraints or required fields) and another message if there are errors but not relevant errors.

**Comment by MartijnR** [comment]
autoqueries also for required questions, but only in this case (not for regular Close)

**Comment by MartijnR** [comment]
functionally completed but the following tweaks will probably be required:

1. change text, see "fieldsubmission.alert.relevantvalidationerror.msg" in translation-additions.json
2. the modal in the screenshot below might have to be shown earlier if there are errors

<img width="608" alt="screen shot 2017-08-30 at 2 02 43 pm" src="https://user-images.githubusercontent.com/627350/30231933-8ec1401a-94aa-11e7-956d-85117f7b0ae0.png">

**Comment by pbowen-oc** [comment]
@MartijnR - I think it would make sense to show the confirmation after the Relevant error check passes.

The text of this message might need to be different than the message the user sees when they click the Complete button. I'll look into this.

**Comment by pbowen-oc** [comment]
@MartijnR - Upon further consideration, we do not need that confirmation since the form is already complete at the time the Close button is clicked.

**Comment by pbowen-oc** [comment]
@MartijnR - For the alert that comes up when there is a Relevant error and I hit close on my Complete form, can we change the text to:
"Response(s) in some field(s) make some data on this form invalid. This must be corrected to retain the form's complete status."

**Comment by MartijnR** [comment]
No problem. Will do.
