### ISSUE TITLE
Nested repeat picks repeat count of the first loop

### ISSUE THREAD

**Issue by dkwamboka** [kobotoolbox/enketo-express#815]
Hi Martijn,

We have a household survey where we want to know what schools each household member attended and what level of education each school offered.

You have a repeat group within a repeat group, lets call the big repeat group, _repeat group A_ and the one inside it, _repeat group B_.

We start with the question, *How many members stay in this household?* this value is used as a repeat count for _repeat group A_.

 _Repeat group A_ asks a household member personal details upto the question, *How many schools have you attended all your life?* which generates a repeat count for  _repeat group B_, whereby the member lists the schools he/she attended and the level of education attained in each. We then move to the next household member until every household member fills this survey.

However, if for the first loop of _repeat group A_, this question generates a value, say 3 for _repeat group B_, for the recurrent loops of _repeat group A_, even if this question generates different values, like 1 or 2 or 4, the repeat count for _repeat group B_ remains the same as was first generated, i.e 3, instead of changing to the new value generated.

The calculated value is the right value, but the value picked as the repeat count is the first value that was calculated for the first repeat. 

I tested the form on ODK Collect, it worked fine. Has this to do with how calculations are done in Enketo? I also noticed if you entered the value a second time, it then picked the right value as the repeat count.

Sample form: [nested_repeat.xlsx](https://docs.google.com/spreadsheets/d/1k1sasaQgEgqZheToZdXACgGKEx7ka2JiGj2hUyOuS1w/edit#gid=1331743052)
Browser: Chrome
Server: Ona

**Comment by MartijnR** [comment]
Thanks for this great report. It's a bug.

**Comment by MartijnR** [comment]
Issue is that the context for the evaluation is not supplied if the nested repeat series has 0 instances.
