### ISSUE TITLE
Pulldata() function nested in an if() function doesn't work in Enketo

### ISSUE THREAD

**Issue by dkwamboka** [kobotoolbox/enketo-express#818]
Hi Martijn,

Using a pulldata() function nested in an if() function does not work on Enketo.

In the form attached, if a person selects the answer to **Q2** as _Child under 5_, then data is pulled using the unique number 1, from the external file, otherwise, whatever number answer given for **Q3** is used as the key to  pulled data from the external file.

This is the error I get on Enketo:
![if_pulldata](https://user-images.githubusercontent.com/20725261/30482093-633fe632-9a2a-11e7-8bd9-609861f200cb.png)

 I tested this on ODK Collect and it worked fine.

Sample form: [if_pulldata.xlsx](https://docs.google.com/spreadsheets/d/1s-6d5rKLX9ruhirHtEKp5-N42s71bR6p__mofu588ys/edit#gid=216006020)
External csv: [schools.csv](https://docs.google.com/spreadsheets/d/1hpUM8H6vmGrM91dMU2nhnvM44WEJJopKvxhVfITI5Jg/edit#gid=853565344)
Browser: Chrome
Server: Ona

**Comment by MartijnR** [comment]
Hi @dkwamboka,

This looks like a pyxform bug. The issue is that in your form the `<instance id="schools" src="..."/>` is not created in the XForm. Would you mind reporting it there?  I see you're with Ona, so @ukanga is the one you want to see this. ;)
