### ISSUE TITLE
Native datepicker won't initialize in Safari (and other iOS browsers)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#820]
https://ee.kobotoolbox.org/::YQxS

https://codepen.io/MartijnR/pen/ZXOQPq (this works when opening on mobile device)

**Comment by MartijnR** [comment]
Weird stuff. If anybody can help figure this out, this is very welcome.

**Comment by pmusaraj** [comment]
I tested this using an iOS simulator and Safari's inspector attached to it. The date field has `type="text"` when inspecting the element: 

<img width="1366" alt="screen shot 2017-09-28 at 2 41 30 pm" src="https://user-images.githubusercontent.com/368961/30984381-2aec5370-a45b-11e7-99e5-3859e0ee10f7.png">

This doesn't happen on my local copy of Enketo. There, the element is of `type="date"`, and it loads the date picker correctly.

**Comment by MartijnR** [comment]
Ah interesting. Thanks!

**Comment by MartijnR** [comment]
caused by https://github.com/kobotoolbox/enketo-express/issues/787. Will find alternative solution

**Comment by MartijnR** [comment]
received report that there is still an issue
