### ISSUE TITLE
problem parsing submission XML iOS10

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#822]
See Vickie's message on how to reproduce https://groups.google.com/forum/#!topic/enketo-users/O6bzk5q73CA (Sep 21). She has the problem with KoBo.

I've reproduced the issue with ODK Aggregate. It responds:

<img width="585" alt="screen shot 2017-09-22 at 12 15 21 pm" src="https://user-images.githubusercontent.com/627350/30758518-f4e54676-9f8f-11e7-81b5-eaea0031477e.png">

I suspect it has something to do with removing empty nodes, but cannot see an actual invalid XML string being created (yet).

* [ ] try to reproduce in KoBo (need XLSForm)

**Comment by MartijnR** [comment]
Oddly enough, I'm not able to reproduce this with KoBoToolbox.

**Comment by vickiedenicola** [comment]
This issue seemed to resolve with an update to iOS 11.0.2.  Other users on my team who haven't upgraded are still having the problem.  Not sure if it is still relevant, given it exists in an older OS, but here's what is happening on iOS 10.x:

- Here is the form: https://ee.kobotoolbox.org/x/#YylB
- If you want to complete a test form, please do, just enter values below and we can delete.
- Choose any Transport Lead
- Choose "Recovered Animal"
- Enter Ear Tag Number = 999
- Enter Ear Tag Color = White
- Pick a location
- Leave telazol, xylazine, ketamine blank
- Select "None" for collar
- Enter 999 for weight
- Select "male"
- Select ".5" for age
- Leave photo and notes blank
- Select "submit"

What is happening on the team's phones (when they were using iOS older than 11) is the submit button would show a loading bar and never complete submission.  Our workaround was to select anything other than "none" on the collar type and the records will submit.

Any thoughts/help are appreciated.  Not sure if this is impacting anything else.

**Comment by MartijnR** [comment]
Thanks a lot. I love it when these issues resolve themselves in new browser versions.

> Our workaround was to select anything other than "none" on the collar type and the records will submit.

That is particularly interesting. I am not sure if I'll be able to look at this issue before iOS10 stops being relevant, but I'll try.

**Comment by vickiedenicola** [comment]
I was pretty happy it self-resolved, but it bugs me when I don't know why.
I just wanted to let y'all know the outcome, not sure if there are any
other ripple effects.


Vickie DeNicola  | White Buffalo Inc.
M: (818) 261-1319  |  vickie.denicola@whitebuffaloinc.org
Find Us: whitebuffaloinc.org | Facebook
<https://www.facebook.com/whitebuffaloinc> | LinkedIn
<https://www.linkedin.com/company/white-buffalo-inc-?trk=nmp_rec_act_company_photo>

**Comment by MartijnR** [comment]
Yes, true. Would be good to know.

**Comment by MartijnR** [comment]
on iOS 9, safari:

<img width="954" alt="screen shot 2017-10-11 at 10 22 15 am" src="https://user-images.githubusercontent.com/627350/31453091-25a9f936-ae6e-11e7-8821-507fd56859c6.png">

**Comment by MartijnR** [comment]
* [ ] see if this can be tested on iOS10 somewhere
* [ ] test in iOS11

**Comment by MartijnR** [comment]
The issue seems to be here: `delete this.dataset.loadedFilename` (on iOS9)

**Comment by MartijnR** [comment]
I think this issue was resolved. The code `delete this.dataset.loadedFilename` doesn't appear to exist any longer
