### ISSUE TITLE
Enketo-express with vagrant not working with odk install on tomcat

### ISSUE THREAD

**Issue by Nickytg** [kobotoolbox/enketo-express#828]
I have setup ODK Aggregate and enketo-express using vagrant following this introduction (for enketo-express)

https://github.com/kobotoolbox/enketo-express#using-vagrant

And both run fine on these url:

ODK (Tomcat8): http://localhost:8080/ODKAggregate/

Enketo (Vagrant): http://localhost:8006

And I already enabled Enketo webform on ODK ( Added Enketo API token and Enketo API URL)
The problem is when I click enketo button on ODK it's redirect to enketo page but it's display "Internal Server Error"
I tried to investigate by running develop mode on vagrant "grunt develop" and got this error

openrosa-communicator Error occurred when requesting http://localhost:8080/ODKAggregate/formList?formID=build_Sample-Form-1_1506929262 { Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080 }

Could you help me how to fix this?

My OS is : Ubuntu 16.04

**Comment by MartijnR** [comment]
Sorry, didn't see this and responded on the forum already: https://groups.google.com/forum/#!topic/enketo-users/2Z4--Qd74ok
