### ISSUE TITLE
OC Only: relevant error message tweaks

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#830]
> I loaded a new (not Complete) record. I made the irrelevant error appear for a single field and also for a group. It reads, "Response(s) in some field(s) make some data on this form invalid. This must be corrected to retain the form's complete status."

> I don't think this is what we had wanted. The text I quoted above looks like what I wanted to be displayed if I click Close on an already Completed record and there is an irrelevant error present. For the error message that is displayed on the form next to a field with this issue, we need something different.  It looks like we previously had, "Response(s) in related field(s) make this data invalid. This must be corrected to mark the form complete."

> Can we have different text on the form vs in the Close/Complete error alert?  I'm assuming it is much easier to at least have the same text for records that are not yet complete and records that are already complete.  Assuming that is true, can we have this text:

> Field/Group error message: "Response(s) in related field(s) make this data invalid. This must be corrected to mark the form complete."
Close/Complete error message: "Response(s) in some field(s) make some data on this form invalid. This must be corrected to mark the form complete."

**Comment by MartijnR** [comment]
I had no idea there was a difference. Will check if feasible.

**Comment by MartijnR** [comment]
Actually I'm confused about the use of the word 'alert' here. Will discuss.

**Comment by pbowen-oc** [comment]
@MartijnR - I was referring to the popup window that appears when you try to Complete a form that has an irrelevant error or Close an already complete form that has an irrelevant error. For usability purposes, we want this text to be different from the error text that appears on the form itself by the irrelevant items.

**Comment by MartijnR** [comment]
Thanks. I see. I may have overwritten the wrong translation string.

**Comment by pbowen-oc** [comment]
@MartijnR - It doesn't look like this update made it in. I'm still seeing the original message I reported.  I looked in translation-additions.json and I don't see the requested text.

I see:
"relevantvalidationerror": {
                "msg": "Response(s) in some field(s) make some data on this form invalid. This must be corrected to retain the form's complete status."
            }
and
"constraint": {
        "relevant": "Response(s) in some field(s) make some data on this form invalid. This must be corrected to retain the form's complete status."
    },

I'd like the message appearing on the field/group itself to be:
"Response(s) in related field(s) make this data invalid. This must be corrected to mark the form complete."
I'd like the message that appears in the modal window when am trying to close/complete the from to be:
"Response(s) in some field(s) make some data on this form invalid. This must be corrected to mark the form complete."

**Comment by MartijnR** [comment]
Oops (again). Sorry. I attempted to fix this in 1.53.0.oc-1 (but haven't tested as I have no time today).

**Comment by pbowen-oc** [comment]
@MartijnR - Looking at the json file, it looks like constraint relevant was updated but relevantvalidationerror msg was not.  Please update it to "Response(s) in some field(s) make some data on this form invalid. This must be corrected to mark the form complete." when you have a chance.  Thanks.

**Comment by MartijnR** [comment]
Oh dear, I have the feeling it may take me a few more commits to get this right... :anguished:

Sorry again.
