### ISSUE TITLE
The max() function is not working

### ISSUE THREAD

**Issue by dkwamboka** [kobotoolbox/enketo-express#831]
Hi Martijn,

The **max()** function is not working on Enketo. I recently uploaded a form with this function and when I tried opening the form, I got the error message shown below.

![ona_max](https://user-images.githubusercontent.com/20725261/31167060-728f8718-a8f9-11e7-8847-35c3a5f197af.png)

I previously uploaded a form with the **max()** function used in a similar way, and it worked just fine then. (uploaded around February this year), but when I open it now, I get the error above.

I also tried the same form on Kobo Toolbox and got the same error as shown in the screenshot below.

![kobo_max](https://user-images.githubusercontent.com/20725261/31167080-8019b692-a8f9-11e7-9ded-5b44c84786f0.png)

On ODK Collect, the form worked fine and collected data as it should.

Sample form: [weighted_random_124.xlsx](https://docs.google.com/spreadsheets/d/1u3L6etDGhxpQ0l1-lnHPdJnCEfg_F_ojVHu-jUnKEYA/edit#gid=1914880730)
Browser: Chrome
Server: Ona and Kobo Toolbox

**Comment by MartijnR** [comment]
Thanks! This is a bug caused by having a repeat-count of 0. I've copied it here as well: https://github.com/enketo/enketo-xpathjs/issues/69
