### ISSUE TITLE
OC only: Survey with this ID not found

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#833]
http://DOMAIN/single/fs/c/i/::6068ee5eb4f0f1edc505c75d3b464a55?ecid=c9daf3a6703c3ff073f99dcb3d6ea63&parentWindowOrigin=http%3A%2F%2Fqe1.dev-r......info%3A8080&PID=Q03.....Sub

Shows up occasionally.

* [x] Provide guidance on how to provide debugging info

**Comment by MartijnR** [comment]
1. API call is made to /survey/single/fieldsubmission/c/iframe
2. If the survey was not launched before, Enketo will generate an Enketo ID and store the form info in its database.
3. API call returns a URL containing a long enketo ID 6068....a55. This is actually an encrypted version of the real short Enketo ID that Enketo uses in its database
4. The URL is loaded
5. Enketo decrypts the long Enketo ID to get the real one.
6. Enketo does a database lookup with the short Enketo ID but cannot find it.

I wonder if something happens with the main redis instance between step 2 and 5 in the test setup. 

One thing that could help rule out any issue with the encryption/decryption step is to see if the same test but for API endpoint /survey/single/fieldsubmission/iframe instead has the same problem. That API endpoint will return a URL with the unencrypted (short) Enketo ID.

**Comment by kkrumlian** [comment]
Hey @MartijnR ,
Joe Switched the URL to /survey/single/fieldsubmission/iframe and it looks like it does resolve the problem. Can you see what is causing the issue with the URLs that the /c/ ?

**Comment by MartijnR** [comment]
Thanks. So the issue is related to encryption/decryption. There may be a flaw in that logic. I'll try to write a test to see if I can reproduce that when generating thousands of IDs.

**Comment by kkrumlian** [comment]
Thank you sir.

Krikor

**Comment by MartijnR** [comment]
@kkrumlian Do the tests always use the same `"less secure encryption key"` value in config.json? If so which value?

So far I'm not able to reproduce an encryption issue with the default key value, which is `"this $3cr3t key is crackable"`.

Knowing the encryption key used to create the URL in the first message in this thread with encrypted ID `6068ee5eb4f0f1edc505c75d3b464a55` will allow a quick non-brute-force check to see if that value can be decrypted. My guess is that you're using the default value which decrypts to 'YYO9'. In that case the bug is probably not encryption-related after all.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#66
