### ISSUE TITLE
Time format from ODK submission not showing on enketo

### ISSUE THREAD

**Issue by ivermac** [kobotoolbox/enketo-express#834]
Hi @MartijnR,
A client was trying to edit data collected by odk for a time field and the client wasn't able to because the field on enketo wasn't showing the data on the xml file. A colleague, @faith-mutua, tested 
 [this form](https://ona.io/qastuff/45103/247164) - [enketo url](https://enketo.ona.io/x/#Y444)- on odk collect and noticed that she couldn't be able edit the `start_time` and `end_time` for data submitted by odk because the time format is slightly different as seen below:

_xml submitted by enketo_
```xml
<Time_test xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" id="Time_test" version="201710080603">
    <formhub>
    <uuid>5bf6578cf5b04dd1b4f533b8e35f6c7f</uuid>
    </formhub>
    <start>2017-10-08T09:03:12.000+03:00</start>
    <end>2017-10-08T09:03:59.000+03:00</end>
    <start_time>09:15</start_time>
    <resp_name>Sally</resp_name>
    <resp_age>26</resp_age>
    <end_time>09:25</end_time>
    <meta>
    <instanceID>uuid:333c392d-7ede-45df-892c-c50e4426502d</instanceID>
    </meta>
</Time_test>
```

_xml submitted  by odk collect_
```xml
<?xml version='1.0' ?>
    <Time_test id="Time_test" version="201710080603" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:orx="http://openrosa.org/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:jr="http://openrosa.org/javarosa" xmlns:h="http://www.w3.org/1999/xhtml">
    <formhub>
    <uuid>5bf6578cf5b04dd1b4f533b8e35f6c7f</uuid>
    </formhub>
    <start>2017-10-08T09:07:12.111+03</start>
    <end>2017-10-08T09:07:33.658+03</end>
    <start_time>09:07:00.000+03</start_time>
    <resp_name>Troy</resp_name>
    <resp_age>28</resp_age>
    <end_time>09:15:00.000+03</end_time>
    <meta>
    <instanceID>uuid:ef91938f-7032-4c26-82f3-a43f35065bc0</instanceID>
    </meta
    ></Time_test>
```

It seems enketo supports `hh:mm` format at the moment. Any recommendations you can make or advice you can give so that we can be able to assist this client?

**Comment by MartijnR** [comment]
Interesting. It looks like this might be a recent change in ODK Collect, though ODK Collect is now conforming to the spec and Enketo isn't, I think.

This is fairly significant work. I think about 16-32 hours. Could Ona sponsor it?

@jnm, @dorey do you foresee any issues with fixing this in Enketo? I guess not if KoBoCollect already uses the proper format, but just checking.

**Comment by ivermac** [comment]
I have had a chat with @ukanga about this and either of us will get back to you as soon as possible.

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/issues/463
