### ISSUE TITLE
Printed Relevant conditions appear as both grey and black text

### ISSUE THREAD

**Issue by msschroeder** [kobotoolbox/enketo-express#835]
Currently, questions which have relevant conditions appear as both grey and black text. Please see the attached example and associated printout. I would have expected all the questions after "Have you ever attended school?" to be grey text as they all depend on a relevant condition.

[Printout_test.pdf](https://github.com/kobotoolbox/enketo-express/files/1371984/Printout_test.pdf)
[Print out Test3.xlsx](https://github.com/kobotoolbox/enketo-express/files/1371987/Print.out.Test3.xlsx)

**Comment by MartijnR** [comment]
Indeed. All that are not currently relevant should look grey. Thanks!

Fixing this issue would need sponsorship or code contribution even though it may be only 1-3 hours of work. Ona perhaps?

* [ ] regular formhub theme
* [ ] Grid theme
* [ ] also check questions inside irrelevant groups in formhub theme
* [ ] ibid in Grid theme

**Comment by msschroeder** [comment]
Hi Martijn,

We will see in the future if our team can do a code contribution. 

Thanks,
Megan

**Comment by MartijnR** [comment]
* [ ] apply opacity to non-regular-select questions
* [ ] avoid regular select questions getting opacity applied twice
