### ISSUE TITLE
OC only: load errors

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#837]
Scenario 1:
Form cannot be loaded
"Survey with this ID not found" error. Exit button will redirect back to OC. No other close button (no x button).

Scenario 2:
Form is loaded, but there are loadErrors (such as XPath formula or not being able to download data).
Turn off fieldsubmissions (e.g. for calculated items). Tbc because we need to classify errors as serious or not serious (goto errors, or user list downoading e.g.)

**Comment by MartijnR** [comment]
Might be more robust to use the better-safe-than-sorry approach and disable all functionality, including fieldsubmissions and buttons, if there is a load Error, with the only exception being a hidden goto field.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#68
