### ISSUE TITLE
Appearance widgets are failing on Enketo

### ISSUE THREAD

**Issue by faith-mutua** [kobotoolbox/enketo-express#841]
Hi @MartijnR 

We have an issue where appearance widgets are not working as expected on Enketo. This seems to have been broken by an Enketo deployment that was done today fixing this issue https://github.com/kobotoolbox/enketo-express/issues/834. The deploy has since been reverted. You can reproduce the issue using [this form](https://stage.ona.io/qastuff/41757/234891) - [enketo url](https://enketo-stage.ona.io/x/#YpGw)

**Comment by MartijnR** [comment]
see answer in https://github.com/kobotoolbox/enketo-express/issues/840. It's likely the same issue. Otherwise just re-open this please (and mention which widget is not working).

https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmp06m1yr8v/appearance_widgets.xml
