### ISSUE TITLE
Show signed state

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#843]
* show signed state with text string + name + timestamps
* during session, remove signed state when a single value changes

The signing itself takes place in OC interface.

**Comment by MartijnR** [comment]
```xml
<meta>
    <oc:signedBy></oc:signedBy>
    <oc:signedOn></oc:signedOn>
</meta>
```

**Comment by MartijnR** [comment]
should work everywhere, incl in edit, note-only and readonly views to load a record

**Comment by MartijnR** [comment]
* [ ] namespaced `<orx:meta>` node too?
* [ ] test with form that is missing oc namespace declaration

**Comment by pbowen-oc** [comment]
@MartijnR - We have a change of requirements on this. We actually want to pass the entire string in rather than pass the name/timestamp and have Enketo insert them. This means Enketo will just display the message as-is (no localization).

**Comment by MartijnR** [comment]
```xml
<meta>
    <oc:signature>This record was signed by Martijn on November 2nd, 2017</oc:signature>
</meta>
```
