### ISSUE TITLE
OC only: Dn history changes

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#847]
* [x] ~~History shown for historic value changes (passed in with the form) are displayed as "Value Changed" with a capital "C". This should be lower case. Note that entries added by Enketo during the session already have a lowercase "c".~~ - **TO BE DONE ON OC SIDE**

* [x] For file uploads or removals within the session, we want to show something different for the change entry. We would like to display the following as the full change entry for uploads: "New file uploaded". For file removals, just display "File removed".  For historic file uploads, we'll still pass in an old filename and new filename and display them in the normal way.

* [x] For history items within the session, we want to show the username of the current user (instead of "Me") for consistency with how we show historic entries. Can you do this now or do we need to make a change to pass in the current user's username?

* [x] fix bug with displaying full name in History

**Comment by MartijnR** [comment]
For the last point OC would need to pass in the current username somehow. There is no mechanism for this at the moment (apart from OpenRosa authentication which you're not using I believe).

**Comment by MartijnR** [comment]
If we narrow down the `users` list part of dn widgets, to only use XML from now onwards (and remove the CSV option).

Assumption tbc: the current user is always included in that list.

Add the `current` attribute to the item containing the current user: `<item current></item>`

**Comment by pbowen-oc** [comment]
@MartijnR - For the user display, this approach should work for us.  Joe suggests that we pass in `<item current=true></item>` for the current user. If we do not pass a current user in, defaulting to the current behavior ("Me") will work.

**Comment by MartijnR** [comment]
@pbowen-oc Due to a bug Enketo has never parsed the full name correctly from the username. E.g. the queries are supposed to have user `pbowen` but were meant to display `Paul Bowen`. Now, I'm afraid OC may have worked around this bug, so wanted to check with you whether it should be fixed.

**Comment by MartijnR** [comment]
Note this fixes were made in `master` (not in the `reason-for-change-I` branch, which I'm hoping we can merge into master as well)

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks for the heads up on the text issue. I logged it on my end.

I think you are right about displaying the full name and not just username. I think we may need username to disambiguate common names or user's whose names in the system have changed. Could we either display both in the History (which might take too much space) or maybe display full name and show username on mouse over?

**Comment by MartijnR** [comment]
Yes, we could definitely show username on mouseover.

**Comment by pbowen-oc** [comment]
Great. I'll check tomorrow to confirm if we want to proceed with that. Thanks.

**Comment by pbowen-oc** [comment]
Let's show Full Name in the History list and have the mouse-over text be "Full Name (Username)".

**Comment by MartijnR** [comment]
Ok, great
