### ISSUE TITLE
When deleting repeat, calculation inside repeat with position(..) should re-evaluate

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#849]
for this particular case this is for all repeats that follow the repeat that was removed

**Comment by MartijnR** [comment]
This will definitely be a change in Enketo Core, which means, we should just merge with the latest KoBoToolbox/enketo-express

**Comment by MartijnR** [comment]
don't put in master yet, keep in separate branch

**Comment by pbowen-oc** [comment]
@MArtijn - It doesn't look like this is working for me. A calculation that uses position(..) in the repeating group is still not updating when I deleted a row above it.

**Comment by MartijnR** [comment]
It was included [demo](https://odk.enke.to/preview?form=http://82.196.7.170/downloads/fy5m4rc1/position.xml). Will check what's going on in OC fork.

**Comment by MartijnR** [comment]
Cannot reproduce the issue in latest OC master. I should probably use your form.

**Comment by MartijnR** [comment]
Received form, but could not reproduce. Either I'm not looking at the right calculation or the OC server is not using the correct version of Enketo Core

**Comment by MartijnR** [comment]
all i
