### ISSUE TITLE
OC Only: add new type of autoquery when user exits by closing browser/tab and required RFC fields exist

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#855]
value: "Automatic query for: value changed and no reason for change provided"

required = not filled in and submitted (but may be emptied after 1 submission)

**Comment by MartijnR** [comment]
nice to have: show asterisk for (still) required fields

**Comment by MartijnR** [comment]
I am able to reproduce situations where the alert is not shown even though there are items in the queue.  Seems to have to do with a) how much interaction the user had with the page, b) whether it is in 'edit' mode (which is mysterious).

**Comment by MartijnR** [comment]
I'm afraid that we cannot make this more robust. Sometimes, it doesn't work.

**Comment by pbowen-oc** [comment]
@MartijnR - So there will be a required asterisk and autoqueries for Reason fields, but the autoqueries might be not be added in some cases when the user leaves? Is that correct?

**Comment by MartijnR** [comment]
Yes, that's correct. Sometimes we cannot capture the event of closing the tab/browser. This is already the case and I expect it to get worse (due to browser developments).

**Comment by pbowen-oc** [comment]
Got it. Thanks!

**Comment by pbowen-oc** [comment]
@MartijnR - The asterisk behavior is a little quirky. It disappears after I've entered my RFC text (as expected). But if I start typing in the field again, the asterisk reappears. Then it disappears again once I've move focus out of the field. This isn't a top priority if it's only a visual thing, but it is a little confusing.
