### ISSUE TITLE
OC Only: when Close/Complete is blocked because of missing RFC, scroll to RFC (not first error in form)

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#856]
Right now, it scrolls to the first constraint or required error in the form, which may be on a different page.

**Comment by MartijnR** [comment]
There is another similar issue with relevantErrors. 

If there is a relevantError on a different page, Enketo will flip to that page, so the shown RFC field refers to a field no longer on the current page.

**Comment by MartijnR** [comment]
I think the best solution would be to:

1. first check RFC Fields and scroll to a missing one (this will always keep the user on the same page).
2. then check for relevant errors and scroll to the first (I do not think this is done correctly either at the moment actually)
3. then check for other errors and scroll to the first

**Comment by pbowen-oc** [comment]
@MartijnR - That sounds like the right order to check for these to me.

**Comment by pbowen-oc** [comment]
@MartijnR - I noticed that when it changes pages to go to a relevant error or a constraint error, any RFC fields from the current page get carried along to the new page. Was that intentional? It was unexpected to me, but probably not a big deal.

**Comment by MartijnR** [comment]
@pbowen-oc Oh, I see what you mean. The filled in RFC fields. Yes, I should just clear them when they pass RFC validation. Will do.
