### ISSUE TITLE
Offline is working on MacBook but not in iPhone

### ISSUE THREAD

**Issue by shivareddyiirs** [kobotoolbox/enketo-express#857]
I am facing this problem since iOS update.
I updated enketo express installation to 1.55.2 but still problem exist.
I can not fill forms while offline through my iphone.

**Comment by MartijnR** [comment]
Hi Shiva,

Let's figure out if the issue is specific to your installation or to Enketo Express generally.

Do you have the same issue with this form: https://enke.to/x/#widgets ?
Can you share a public offline-capable webform URL on your server?

Cheers,
Martijn

**Comment by shivareddyiirs** [comment]
No for this form, I don’t have this issue.

Can you please check my form which is https://ec2-13-126-63-147.ap-south-1.compute.amazonaws.com/x/#YYYS

Let me know what’s going wrong

**Comment by MartijnR** [comment]
I'm 99.9% sure this is related to not having an SSL certificate installed. The applicationCache is pretty sensitive about that. Please re-open if an SSL certificate doesn't resolve it.
