### ISSUE TITLE
Pages mode quite seriously broken, inputs not registering clicks

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#877]
Text and number inputs. See enke.to/::pages (if using latest version, but am downgrading now)

**Comment by MartijnR** [comment]
Hmm. Ona is on 1.55.2 and doesn't seem to have a problem and I downgraded to 1.55.0 and still see the problem. It might be an npm dependency.

**Comment by MartijnR** [comment]
Locally on 1.55.4 also no problem.

**Comment by MartijnR** [comment]
Jquery-touchswipe module is the likely culprit but simply downgrading it does not resolve it. I had to actually remove swipe functionality

**Comment by MartijnR** [comment]
This is actually caused by the workaround to block page navigation while a new error is being revealed.

**Comment by MartijnR** [comment]
Ona 1.55.2 (no problem): https://enketo.ona.io/::Ya6V

**Comment by MartijnR** [comment]
THe issue is that the input (text,number) doesn't get focus (no focus event fires on them when clicking on the element).

**Comment by MartijnR** [comment]
Never figured out why this issue only appeared yesterday. The publication of a new jquery-touchswipe version yesterday may have been a coincidence. However, the issue was definitely caused by jquery-touchswipe by prevent default events from being handled.

**Comment by pbowen-oc** [comment]
@MartijnR - I think this has been affecting our current branch. Several times I just saw numbers, text, and date fields not letting me click into them. This was only observed in Preview mode. It did sometimes let me click into a field and type into it, only to not let me click into that same field a minute later. Does it sounds like the same issue? If so, could we get this fix pushed to our branch? I'm concerned it might be affecting regular edit mode and we just haven't observed it yet.

**Comment by MartijnR** [comment]
Yes, I think that's a good idea because a simple npm update might suddenly make the issue appear (without Enketo code changes).

I think it would make sense to just merge from the latest KoBoToolbox/enketo-express. I has some (minor) print fixes and it has the position(..) fix, which I think is safe. There is anyway no easy way to avoid the other fixes because they're all in enketo-core.

**Comment by pbowen-oc** [comment]
OK, please push those changes to our branch as soon as you can. Thanks.

**Comment by MartijnR** [comment]
For the record, this issue popped up again. It was resolved by copying node_modules from a functioining server that had jquery-touchswipe 1.6.15 installed.
