### ISSUE TITLE
repeat-as-page removal reveals unexpected page

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#879]
> If each repeat displays on a new page, I can add a repeat and it it takes me to the next page automatically. If I then delete that last repeat, it should take me back to the previous page and show me what is now the last repeat. Instead, it is showing me only the Add repeat button and it is treating it as the first page of the form. I can use the Next button to navigate through all the pages and come to the repeat.

see email and test form by Paul on 11/29/17

**Comment by MartijnR** [comment]
Form VitalSignsimg.xml

**Comment by MartijnR** [comment]
I believe this is fixed (accidentally when fixing another issue).

**Comment by pbowen-oc** [comment]
@MartijnR - This is still broken.

**Comment by MartijnR** [comment]
http://localhost:8005/preview?form=http://82.196.7.170/downloads/a73sc6kz/VitalSignsimg.xml

**Comment by MartijnR** [comment]
the cause probably lies in fieldsubmission.scss

**Comment by MartijnR** [comment]
move enketo-core fix to OC's customized page.js! https://github.com/enketo/enketo-core/commit/fa839e34ea0e44136b5720c7387725f4c800b2a1#diff-9432b5d904c474efef4df65c28544fc9
