### ISSUE TITLE
Don't convert invalid dates, set to empty instead

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#881]
>I noticed that if I enter a date of 2017-11-55, it immediately changes to 2017-12-25.  Any bad value I put in gets converted to a value that is valid. There's some sense to the logic used here, but it is not what we want. We'd like the field to be cleared if I enter a date that is not valid.

This would only be under our control in the JS widget, not the native inputs (touch/readonly).

**Comment by kkrumlian** [comment]
This is top priority for us

**Comment by MartijnR** [comment]
* [ ] dates
* [ ] same with datetimes

**Comment by MartijnR** [comment]
Should be completed on Monday.
