### ISSUE TITLE
ToC in pages mode

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#887]
Requirements still under discussion.

Label could be in the first label (group or question) on the page.

* ToC accessible on all pages or just first page?
* behavior with pageValidation: true
* behavior with pageValidation: false, when error message is just being shown (might not actually be relevant if the ToC is a pulldown menu as it will take time between clicking the pulldown and clicking the page, sufficient to see the error).
* OC only behavior with RFC fields

**Comment by MartijnR** [comment]
* behavior with translated forms (update ToC when language switches)

**Comment by MartijnR** [comment]
just lay the groundwork to build a ToC and flip to a page

**Comment by MartijnR** [comment]
figure out how best to suppress a ToC (form-wide (API, or style?))

**Comment by MartijnR** [comment]
<img width="859" alt="screen shot 2018-08-09 at 3 53 28 pm" src="https://user-images.githubusercontent.com/627350/43928099-f0099f12-9bec-11e8-9314-ab49e433ccac.png">
<img width="716" alt="screen shot 2018-08-09 at 3 53 23 pm" src="https://user-images.githubusercontent.com/627350/43928101-f2a8c82e-9bec-11e8-81ab-63f7d1a27d33.png">

**Comment by MartijnR** [comment]
https://forum.opendatakit.org/t/blocking-page-jumps/14500

**Comment by MartijnR** [comment]
When blocking jumps, we should probably also block GoToFirst and GoToLast.

**Comment by MartijnR** [comment]
<img width="855" alt="screen shot 2018-08-10 at 1 16 38 pm" src="https://user-images.githubusercontent.com/627350/43976928-aca45ccc-9c9f-11e8-80e4-79dea971c2af.png">

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#49
