### ISSUE TITLE
Off-line mode fails in Swedish on Android/iOS

### ISSUE THREAD

**Issue by niklaslj** [kobotoolbox/enketo-express#891]
When reloading a form without Internet connection the load is failing. 
`Loading Error` / `Alert` is displayed in an dialog box and no form is opened.
The problem occurs only when the browser is requesting the page in swedish and only on mobile devices (both Andriod/Chrome and iOS/Safari).
Works fine in english browsers even mobile. Also works in swedish in Win10/Chrome as far as I have been able to test.
Seems the translation tables is not loaded for offline use.

Tested with the form [https://enke.to/_#widgets]( https://enke.to/_#widgets) that is running Enketo 1.55.5. Same error in Enketo 1.55.2.

Chrome console snippet from offline use:
`enketo-webform-bundle.min.js:1 GET https://enke.to/locales/sv/translation-combined.json net::ERR_INTERNET_DISCONNECTED`
`enketo-webform-bundle.min.js:1 ["failed parsing /locales/sv/translation-combined.json to json"] undefined`
`["failed parsing /locales/sv/translation-combined.json to json"]`

_My problem is that firemen all over Sweden is now stucked when doing home visits to inspect smoke detectors. Very important work around Christmas!
Begging for a quick fix!_

**Comment by niklaslj** [comment]
Deeper investigations hints that the problem is related to the problem when the browser gives the `Accept-Language:` in the form language-region, i.e. `sv-SE` instead of only language, i.e. `fr`. 
Using Android/FireFox, that allows easy language change, and trying some languages  with and without region attachment the following visualizes:
German (language code: `de`) works
French (language code: `fr`) works 
Spanish (language code: `es-ES`): fails
Swedish (language code: `sv-SE`): fails

Testing offline on  Win10:
Chrome, Swedish (language code: `sv`): works
Edge, Swedish (language code: `sv-SE`): fails

My theory is that this is residues from the earlier bug when handling language codes.
When offline mode is handled in the browser the cached translation table is named "sv", but the language code from the browser asks for "sv-SE".

_Hope this will help you to find the bug!_

**Comment by niklaslj** [comment]
Easy way to see/debug the bug in Win10/Chrome:

1. Change the language setting in Chrome to one that include regions i.e. `German (Schweiz)` to get language code `de-CH`.
2. Reload the form twice to get the new language.
3. In DevTool/Network-tab, check `offline`.
4. Reload form.

Now I get an alert `Loading Error` and some debug text in console claiming the translation table is missing.

**Comment by MartijnR** [comment]
Many thanks for this useful report. Will have a look to see if this can be fixed quickly. Very cool to hear that fire fighters in Sweden are using this!

**Comment by MartijnR** [comment]
@niklaslj I added a quick fix. It's one commit beyond version 1.55.6 (so not released yet). If you are running your own server, please check if this resolves it. You can also check this form https://odk.enke.to/x/#YYYV (the enke.to server, with the widgets form has not yet been updated).

Thanks again, and keep those excellent bug reports coming please! 👍

**Comment by niklaslj** [comment]
@MartijnR Sorry, no server yet. Using Onas services.
Verifying [https://odk.enke.to/x/#YYYV]( https://odk.enke.to/x/#YYYV) is working offline - using Android/Chrome in Swedish  (language code `sv-SE`)
(I will test other combinations later)
Good work! Many thanks!
When will this version be released?

**Comment by MartijnR** [comment]
Thank you for checking. A new version was just released that includes the fix (1.55.7).
