### ISSUE TITLE
Relevant condition prevents submission with 'Syntax error, unrecognized expression' error

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/enketo-express#892]
When trying to submit a response users get this error, apparently only since deployment of latest master (on 12/6/2017 on our end): 

![image](https://user-images.githubusercontent.com/673511/33845043-276440a6-de70-11e7-946f-049361a0cc69.png)

To test: 
1. https://ee.kobotoolbox.org/::YLzG
1. Try to submit without choosing any response or select No or select Don't know. 
1. Only choosing 'Yes' allows the submission

Source form file [test_enketo_bug.xlsx](https://github.com/kobotoolbox/enketo-express/files/1548787/test_enketo_bug.xlsx) uses a period in the variable name but that is not rejected by KC and isn't a problem otherwise.

**Comment by MartijnR** [comment]
Happens in function to clear irrelevant nodes from submission. JQuery sizzle engine cannot deal with dots in the node name. Needs to be escaped before passing to jquery.
