### ISSUE TITLE
no-collapse appearance doesn't work for nested repeat

### ISSUE THREAD

**Issue by pbowen-oc** [kobotoolbox/enketo-express#899]
We observed a test form with a repeat nested in a non-repeating group.  When the nested repeat had no-collapse appearance, it still displayed as collapsible in Enketo. In this case, the outer group did not have any appearance defined.

**Comment by MartijnR** [comment]
I think I may have only tested this with a hand-coded XForm. In pyxform the no-collapse appearance is added on the repeat instead of the parent group of the repeat. 

https://docs.google.com/spreadsheets/d/1yoAKd2i9hJaVkE-1NfIGDYPf81chfxqWDSFLqMWwMbM/edit#gid=0
