### ISSUE TITLE
Offline loading error "Alert"

### ISSUE THREAD

**Issue by Benidrissa** [kobotoolbox/enketo-express#905]
We are unable to load form offline.
We used chrome, safari, on iOS, Android and windows 10. 
It only work on Microsoft Edge  windows 10 pro.
![loading-error-alert](https://user-images.githubusercontent.com/11193109/34654940-9d0cc54a-f3fa-11e7-9b8b-d6fa4bde3787.PNG)

**Comment by Benidrissa** [comment]
solved here https://github.com/kobotoolbox/enketo-express/issues/891
but not on https://kobo.humanitarianresponse.info , https://ee.kobotoolbox.org instance

**Comment by MartijnR** [comment]
Ah great. Thanks for following up.
