### ISSUE TITLE
Docker image failing to connect on localhost

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/enketo-express#911]
Running locally on OSX. Freshly updated docker installation.

Please find attached logs.

[docker_nginx_1.log.txt](https://github.com/kobotoolbox/enketo-express/files/1627653/docker_nginx_1.log.txt)
[docker_enketo_express_1.log.txt](https://github.com/kobotoolbox/enketo-express/files/1627654/docker_enketo_express_1.log.txt)

**Comment by MartijnR** [comment]
Thanks. I hope some docker enthusiast can help with this.

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#48
