### ISSUE TITLE
constraint message not displaying on readonly field

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#912]
Might be by design, but it is showing red background. See XForm sent by Paul on 1/16

**Comment by MartijnR** [comment]
Constraint and required messages are deliberately excluded in enketo-xslt for readonly questions. However, the engine still validates readonly questions (since recently I think). So this is not consistent any more.

**Comment by pbowen-oc** [comment]
@MartijnR - The constraint wouldn't fire for hidden items (including calculate item type), right?

**Comment by MartijnR** [comment]
No, it wouldn't. It excludes hidden (no body element) and disabled (irrelevant) questions.

**Comment by pbowen-oc** [comment]
Perfect, thanks!

**Comment by MartijnR** [comment]
(in `master` now, so not in new cache branch)
