### ISSUE TITLE
OC Only: Upon close and complete, re-fresh some externaldata.

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#919]
The purpose is to get calculations with oc:external="clinicaldata" to re-calculate after refreshing the external data.

The cascade of consequences of those value changes should run automatically.

To start with just re-download the instance with id `"clinicaldata"`.

**Comment by MartijnR** [comment]
If there was a change in any of the external data calculations, that was triggered by the refresh, a modal dialog to be shown: "External Data was updated, please review". Only option in that modal is to exit back to the form.

**Comment by MartijnR** [comment]
if document retrieval fails, keep external data unchanged and proceed with Close/Complete

**Comment by MartijnR** [comment]
up to 3 days of work, I think

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#56
