### ISSUE TITLE
Authentication by token

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#920]
Add 3rd authentication option to use a token passed as query parameter in the webform URL. The name of the token could be defined in the configuration. OpenRosa auth should be disabled. The existing 'External Authentication' may not have to be disabled as it shouldn't really interfere.

Pass the value of the query parameter to **all** server requests as a special fixed header

* [x] redesign configuration
* [x] add backwards compatibility for old configurations
* [x] xform directly with /xform/::abcd
* [x] submissions, 
* [x] XForm, 
* [x] FormList, 
* [x] media and external data
* [x]  HEAD quests for max submission size
* [x] figure out what's the deal with the return_url being mysteriously decoded
* [ ] fieldsubmission in OC: HEAD request to fieldsubmission is not passing token
* [x] add redirect mechanism or error message if token is invalid
* [x] update documentation on enketo.org/develop/authentication

**Comment by MartijnR** [comment]
@kkrumlian could please you send a link, or describe, how the header should be added?

**Comment by MartijnR** [comment]
we also need a URL to redirect to in case the token is invalid

**Comment by MartijnR** [comment]
Basic authentication (default ODK):
```json
"authentication" : {
        "type": "basic",
        "allow insecure transport": "false"
    }

```
External cookie authentication:
```json
"authentication" : {
        "type": "cookie",
        "url": "http://example.com/login?return={RETURNURL}"
    }

```
External token authentication: 
```json
"authentication" : {
        "type": "token",
        "query parameter": "my_token",
        "url": "http://example.com/login?return={RETURNURL}"
    }
```

**Comment by MartijnR** [comment]
@ivermac fyi see above commit. It fixes at least one issue that I think Ona had identified and fixed in their fork (encodeURIComponent of the return URL). If there are other changes you still have to make to get authentication to work properly within Ona, please let me know. I'd like to merge those as well. Also, as you will see the authentication configuration has changed and is much more sensible now (though old config should still work for now).

**Comment by MartijnR** [comment]
The problem in the OC fork is with HEAD /fieldsubmission, not HEAD /submission

**Comment by ivermac** [comment]
Hey @MartijnR , thanks for the update. I'll pull the latest changes once you have created the new release. I'll let you know if we still need our changes for enketo to work properly with Ona. I'll make a PR if we'll still be needing the changes that we have and wait for your approval if that's okay with you.

**Comment by MartijnR** [comment]
Sounds great. Thanks!
