### ISSUE TITLE
In Enketo Validate add --oc rules

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#922]
1. If instance('clinicaldata') is used in a type="calculation", the bind should have an oc:external="clinicaldata"

2. If calc with  oc:external="clinicaldata" bind present, the calculation should include instance('clinicaldata')

**Comment by MartijnR** [comment]
try to also automically swap the XPath evaluator when the --oc flag is used

**Comment by MartijnR** [comment]
output as error I think

**Comment by MartijnR** [comment]
Also do a namespace (URI) check

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/18jFHL43Fhu0vdL13dSLRAPTIkPj8ulvEAAXXxtu51_w/edit?usp=sharing

**Comment by pbowen-oc** [comment]
@MartijnR - It doesn't look like item 2 is working.  I have an item defined with oc:external=clinicaldata and calculation=10 and it is not giving me an error.

Also, I noticed that when the error for item 1 is shown and the error from issue #925 is shown, they come through in the same block of text as just consecutive sentences. Can we get line breaks added between error messages that come through together? We want to display them to the user as a list, not  a paragraph.

**Comment by MartijnR** [comment]
oops, yes, I forgot about that rule. Sorry about that. Will add to enketo-validate shortly

**Comment by MartijnR** [comment]
The latest enketo-validate (1.2.0) now has this rule added.
