### ISSUE TITLE
Additional validation rule

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#925]
We would like a validation that fires if an item:
1) Is any type except calculate
2) Has a non-null value in the calculation column
3) Does not have yes or true in the readonly column

Can this be added to the Enketo Validator along with the validations in #922?  The intent is that if a calculation is populating an item, the user will not be able to manually override the calculated value. We also don't want to force users to define type calculate item as readonly since that is confusing.

This type of logic was difficult for us to implement internally. If you are able to easily tell the difference between a calculate type item and any other item with a calculation, there are probably some other validations we would look to add.

**Comment by MartijnR** [comment]
This would actually be good to have for everybody. It's not so straightforward to robustly find a type="calculate" (i.e. no body element), but definitely possible for XLSForm-produced forms.

**Comment by MartijnR** [comment]
@pbowen-oc would you like this to be a warning or an error? (In the latter case, that would probably be a special OC customization).

**Comment by pbowen-oc** [comment]
We would like it to be an error.

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/18jFHL43Fhu0vdL13dSLRAPTIkPj8ulvEAAXXxtu51_w/edit?usp=sharing
