### ISSUE TITLE
OC only: autoquery when constraint changes from false to true and current state=open

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#929]
May need to add some hardcoded logic for constraints to look at query status, instead of the currently auto-added comment-status clauses to constraints.

Think about this

**Comment by MartijnR** [comment]
In order to meet this requirement we would indeed have to remove the auto-added constraint clauses and hardcode those in the constraint evaluation logic. If I remember correctly those clauses check whether the linked dn question has a particular status.

In order to do that we'd need to be able to figure out from the actual question, what the name of the linked dn question is. Unfortunately, the `for` attribute that we introduced does exactly the opposite (it links from dn to question instead of from question to dn)

**Comment by MartijnR** [comment]
A possible other direction is to use the currently-unused `constraint` on the dn questions themselves. We'd still be fighting the Enketo Form engine though.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#58
