### ISSUE TITLE
date picker only accepting dates in 2017 on iphone

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/enketo-express#930]
https://ee.humanitarianresponse.info/x/#YQAI

Use iphone to test form and trigger the bug.

![image](https://user-images.githubusercontent.com/15673694/35680188-9c00c22e-0727-11e8-9734-75fbd5dc6949.png)

**Comment by emilykferguson** [comment]
Another example can be found here: https://ee.humanitarianresponse.info/x/#YHsh

To trigger, select Activity to be recorded> MOU. Then "Have you signed the MoU > yes. Using today's date triggers an error.

**Comment by MartijnR** [comment]
ah yes, this was quite a nice one. It occurs in Safari when one of the date components (e.g. day or month) is less than 10... :)

It was fixed in [1.55.7](https://github.com/kobotoolbox/enketo-express/blob/master/CHANGELOG.md#1570---2018-01-08) (Esri)
