### ISSUE TITLE
OC Only: Draw on default image

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#941]
extend draw widget or create new one. (e.g. `appearance="draw default-circle"`)

How many images? Can they all be hardcoded?

**Comment by MartijnR** [comment]
Possible approaches (but suitability depending on final requirements):

1. Use an appearance that shows a hardcoded default vector image
2. Use an appearance and image label, where the image label is shown inside the widget, instead of next to the label
3. Add the vector string or image URL as custom body attribute, e.g. oc:default.
4. Use repeat template (somehow)

**Comment by MartijnR** [comment]
number 2 would correspond with https://github.com/opendatakit/collect/issues/84

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#59
