### ISSUE TITLE
Consider configuration restrictions for number and strings.

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#955]
Not sure how to do this in each widget. Could also be linked with (OC) hard validation, #944

**Comment by MartijnR** [comment]
maybe just provide feedback to user, but keep value

**Comment by MartijnR** [comment]
Alternatively the server could return an error message and Enketo could display this.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#63
