### ISSUE TITLE
Get PDF empty form or of record loaded into form

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#958]
General part:
* [x] endpoints in /api/v2
* [x] do a check-chrome-install check? - puppeteer installs a bundled version
* [x] pdf ~~streaming~~ file response
* [x] load record into form, and return pdf print result (headless Chrome?)
* [ ] consider caching or using a remote server for stability
* [x] performance: directly inject html on server in special print view that loads print css only
* [x] grid theme: js processing ~~required?~~ reorganize function in enketo-core
* [x] margin setting not working in print script. 
* [x] figure out recent doubling in processing time
 * [x] add api tests
* [x] add options to API
* [x] document API
* [x] rewrite to support nodeJS 6+
* [ ] approve geolocation (or disapprove): https://github.com/GoogleChrome/puppeteer/pull/1297
* [ ] add support for scaling (can be faked with paper formats though)
* [x] use "view" mode for /instance/view/pdf perhaps

OC only part:

* [x]  /instance/view/pdf endpoint in /oc/api/v1
* [x]  /survey/view/pdf in /oc/api/v1
* [x] for both views in OC, make sure the "view" mode is used that doesn't submit! (or calculate)
* [x] grid js processing not running in OC fs views
* [x] Print discrepancy notes in order of XForm
* [x] Print history of discrepancy notes
* [x] Include label of linked question above discrepancy note
* [x] bug with pages mode in Grid theme (page still has flex, is that right?)
* [x] show dn's (after new views used)
* [x] analog scale label : only first part

**Comment by MartijnR** [comment]
https://github.com/graphcool/chromeless

**Comment by MartijnR** [comment]
I would make sense to create a view that directly load the print css, and for the Grid Theme runs the print script.

Having to load the screen version first and then click the print button seems inefficient.

**Comment by MartijnR** [comment]
interestingly chrome's (or puppeteer's) pdf function applies the print css automatically

**Comment by MartijnR** [comment]
This is pretty cool. Easy to customize paper sizes and margins as well.

**Comment by MartijnR** [comment]
A problem with the Grid theme is that we still need the JS processing to add page breaks. This means that we either cannot use the full scale/paper/margin customizability of Chrome headless or we need to add all that functionality to the print script.

**Comment by MartijnR** [comment]
scale support not added yet. Needs to be added to JS function for grid. Possibly CSS `transform: scale(factor)` may work before calculation widths and heights.

**Comment by MartijnR** [comment]
Some outstanding question for printing discrepancy notes:

* should each dn question be forced to full form width (without doing this it would seem impossible to display the history nicely)?
* is any information from the dn history irrelevant for the pdf? 
* should the dn question's own label be hidden?

**Comment by pbowen-oc** [comment]
@MartijnR - 
1. Yes, full width makes sense to me.
2. No. We need to print all items that we might show there (value changes, queries, reasons for change, and anything we might add in the future) as well as the user and timestamp for each item.
3. Is the DN question's label "Comment:"? If so, we won't need that. I think we will need the primary form item's label attached to its DN item: example "History for - Medication Name:" where "Medication Name:" would be the primary form item's label.

**Comment by MartijnR** [comment]
added CSS patch in sourceTree (in case css customization cannot be avoided)
