### ISSUE TITLE
Beforeunload handling

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#964]
https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload

> Various browsers ignore the result of the event and do not ask the user for confirmation at all. The document will always be unloaded automatically. Firefox has a switch named dom.disable_beforeunload in about:config to enable this behaviour.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#64
