### ISSUE TITLE
OC Only: Complete Button redesign

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#972]
3 options:

1. Use API to indicate this (e.g. `complete` parameter) and change Enketo code to handle this more robustly (probably by adding information to the `<data>` instance that is sent to Enketo). This would require adding some server-side logic (parsing and manipulating XML) that is currently not there.
2. Use XML record to indicate this. The main difference with the previous option is that the logic is done on the OC-side and that this is view-independent (no automatic fine-grained control for specific API endpoints, except if added on the OC side).
3. Create additional specific views/endpoints for when a CompleteButton should be shown.

Possibly remove the /fieldsubmission/complete endpoints from the [OC fieldsubmission API](https://app.swaggerhub.com/apis/martijnr/openclinica-fieldsubmission/1.0.0), if the record itself can indicate whether it is complete or incomplete.

**Comment by MartijnR** [comment]
Do this on Enketo side (API + record). Would be good to rename `completeButton` param in API.

**Comment by pbowen-oc** [comment]
@kkrumlian - Do you have any comments on this?

**Comment by MartijnR** [comment]
@kkrumlian I think option 2 is the way to go, despite some changes required on the OC side.

It's the most logical solution and also seem to fit well with a future requirement to have complete/incomplete toggle in the form.

**Comment by kkrumlian** [comment]
When you say use Use XML record to indicate this. Is this xml record a file that appears in the manifest?

**Comment by MartijnR** [comment]
No, it's XML string (`instance`) that OC sends to be edited as part of the API call.

**Comment by MartijnR** [comment]
Yes, I think `complete` with values `"true"` and `"false"` (default `"false"`) in the http://openclinica.org/xforms namespace would be great e.g.:

`<data xmlns:oc="http://openclinica.org/xforms" oc:complete="true">
     <question1>5</question1>
</data>`

However, Paul just mentioned a possible future Participate requirement where the ability to mark a form as complete is dependent on the user role (not on the record itself). To be considered if option 2 is still the best choice in that case.

**Comment by MartijnR** [comment]
Since a record on the OC side is either complete or incomplete, it seems to fit well to use the attribute to pass the completeness state to Enketo.

We could maintain the API call (/fieldsubmission/complete) communicate a change in completeness state from Enketo to OC.

**Comment by MartijnR** [comment]
As discussed:

Looks like the proposed method would work for passing completeness state to Enketo.

For passing the changed completeness state to OC, we could do:

a. Keep the /fieldsubmisssion/complete API call: https://app.swaggerhub.com/apis/martijnr/openclinica-fieldsubmission/1.0.0#/
b. Or let the XML Fragment sent in each fieldsubmission contain that info in the root node attribute (so same method used in both directions).

Decision on the latter tbc.

**Comment by MartijnR** [comment]
The changed approach to pass completeness state of a record to Enketo is now implemented in the `develop` branch.

Enketo will show the Complete button if the record is not marked as complete, but only does this for certain views that have the Complete button feature.

It seems easiest and safest to simply add `xmlns:oc="http://openclinica.org/xforms" oc:complete="true"` or `xmlns:oc="http://openclinica.org/xforms" oc:complete="false"` to ALL instances that OC creates and passes as a parameter to API calls. This way you can simply rely on Enketo to know when to do something with this information (e.g. do nothing in readonly or noteonly views that load a provided record).

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#50
