### ISSUE TITLE
Reset button for drawing/signature and upload not working

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#990]
> This is for file upload/drawing item types. The reset button does not work for any of these, so it is not possible to clear the image/file/drawing. Note that the Undo button works for draw/annotate, but it is only undoing the lines, not the image upload for annotate.

> Note that the reset button is not doing anything (there is no popup confirmation of the action like there was before).

**Comment by MartijnR** [comment]
* [ ] In Enketo Core this is all working.
* [ ] EE:
* [ ] EE-oc:

**Comment by MartijnR** [comment]
in dialog.js, the `gui` object is empty. Could be an aliasify issue.

**Comment by MartijnR** [comment]
very mysterious. If I copy gui.js to gui.1.js and change require('./gui) to require('./gui.1') all is good again. This seems like some kind of interaction with another module with the same name.

**Comment by MartijnR** [comment]
You can trick the system into a correct build by calling require('../dialog') from e.g. the main-webform.js entry file.

**Comment by MartijnR** [comment]
Leaving this open. I was not able to find the actual cause of this JS build issue yet. I added a temporary workaround for now.

**Comment by pbowen-oc** [comment]
@MartijnR - The Reset Button is generally working now, but it is not considering whether the form is open in edit/review-only/read-only mode. We expect that the file should be able to be reset in edit mode, but not review-only or read-only mode. However, we are observing that the reset button is present and active in review-only and read-only mode. The button should be disabled in these modes or not visible at all. (Note that review-only mode is actually submitting the file removal back to us, but read-only is not submitting it.)

**Comment by MartijnR** [comment]
ah yes, of course. That was never implemented (including geo widgets).

**Comment by pbowen-oc** [comment]
@MartijnR - Ideally, the Reset button and Undo button would not be visible in review-only and read-only modes. The Download button should still be visible and functional in all modes.

**Comment by MartijnR** [comment]
* [ ] do final check in special fs note-only views

**Comment by MartijnR** [comment]
working too fast. Reset no longer functional in drawings in note-only mode, but still visible

* [ ] hide reset button in drawing widget when drawing is readonly

**Comment by MartijnR** [comment]
reopening as this this needs a proper fix (without the temporary workaround)

**Comment by MartijnR** [comment]
I think this is because of the way gui.js self-initializes.

**Comment by MartijnR** [comment]
Finally figured it out. It's very subtle so here is the post-op for posterity:

TL/DR; it's a circular reference

1. dialog.js (aliasified from enketo/dialog) requires gui.js
2. gui.js requires ../core/print.js
3. ../core/print.js requires dialog.js (aliasified from enketo/dialog)
4. for some reason that results in the gui module becoming an empty object

Commenting out the require('../core/print') eliminates the issue.

The fix:
