### ISSUE TITLE
Print button in edit or view mode 

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#992]
>We are experiencing another issue with the Enketo print-form link. It works as expected in the initial data entry session, when there is no data in the form and when data is entered.
The print-form link does not work when reopening the form in edit or view mode after the initial data entry session. It seems as if the link is disabled.

* [ ] check whether in regular EE as well or only in OC (fs)

**Comment by MartijnR** [comment]
Looks like the workaround for #990 also works around this issue.

Will leave open as this workaround is temporary.

**Comment by pbowen-oc** [comment]
@MartijnR - We're still observing this issue. Note that the issue from #990 appears to be fixed as expected.

**Comment by MartijnR** [comment]
cannot reproduce with 

```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9/>&instance_id=b" http://localhost:8005/oc/api/1/instance/edit
```

This may have something to do with the values of empty discrepancy notes questions that are in the record to be edited.

@pbowen-oc, could you please paste the screenshot of the console error we saw when clicking the Print button?

**Comment by pbowen-oc** [comment]
@MartijnR - 
![image](https://user-images.githubusercontent.com/25179620/39276966-7b0a1498-48b9-11e8-862d-b863203d88ec.png)

**Comment by MartijnR** [comment]
Can be reproduced with a record that includes at least one query with a `user` property.

**Comment by MartijnR** [comment]
@pbowen-oc, version `1.65.0.oc-1` has the two urgent fixes and is ready for testing.
