### ISSUE TITLE
Huge external data files

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#996]
OC will sent realistic file,

and realistic sample query on that file

**Comment by MartijnR** [comment]
* check bottlenecks after network request has been completed. Parsing XML? Searching XML?

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::NZptMW13

**Comment by MartijnR** [comment]
When continuing this work, try a version of this form with XML instead of CSV.

**Comment by MartijnR** [comment]
conversion from CSV to XML string -> 256ms (so no big deal)

parsing XML from string ->

**Comment by MartijnR** [comment]
itemsetUpdate performance findings:

* `value = $item.children( valueRef ).text();` is a major cause of slowdown (oddly)

**Comment by MartijnR** [comment]
Need to rewrite most of itemset.js:
* don't do translations like this
* remove jquery manipulation and use pure Javascript with createDocumentFragment() and appendChild
*

**Comment by MartijnR** [comment]
Note that the XForm actually had incorrect reference to value and label for the first question. This should be:

```xml
<itemset nodeset="instance('medications')/root/item">
                    <value ref="NONPROPRIETARYNAME"/>
                    <label ref="PRODUCTNDC"/>
                </itemset>
```

but easier to change the CSV headers instead to ('label' and 'value')

**Comment by MartijnR** [comment]
Safari cannot deal with large autocomplete list (but that's a slightly different issue) due to lack of `<datalist>` support.

**Comment by MartijnR** [comment]
* [ ] what kind of queries are needed?

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#53
