### ISSUE TITLE
edit fs view, the loader image moves to the top of the screen

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#999]

**Comment by MartijnR** [comment]
possibly related to iframe (and size of iframe)

**Comment by MartijnR** [comment]
* [ ] try view-only 
* [ ] try note-only

**Comment by MartijnR** [comment]
In order to reproduce this:

* check with @pbowen-oc if an empty form has the same behavior
* if so, get an OC url to reproduce with (likely to do with iframe CSS)
* if not, does it happen in edit mode for small/empty records? (If not, it is likely related to loading large records).

**Comment by MartijnR** [comment]
https://form.dev.openclinica.io/single/fs/c/i/::d7417e80eecfa318f0ab70a779363946?ecid=76dc8953cf1b9d6b802c2f2837534f66286d99620f26903a3cfbb679d52d8de1&parentWindowOrigin=https%3A%2F%2Fcust1.dev.openclinica.io&PID=001

**Comment by MartijnR** [comment]
Very interesting. When looking at the actual **Enketo webform url**, i.e. the src of the iframe in the window served by OC, I see a whole bunch of stuff that is added to the HTML outside of Enketo.

This is causing the odd behavior. It's also showing a different loading image at some point:

<img width="140" alt="screen shot 2018-05-08 at 2 47 16 pm" src="https://user-images.githubusercontent.com/627350/39782208-bf07f5f6-52ce-11e8-80a4-a9a8a455e044.png">

Some of the things that are loaded are fairly heavy too (jQuery, which is already part the Enketo bundle, Angular, etc.).

If these scripts and styles are not injected deliberately, it would be good to remove them

<img width="1465" alt="screen shot 2018-05-08 at 2 39 54 pm" src="https://user-images.githubusercontent.com/627350/39782336-1b33c62a-52cf-11e8-94df-1f1345cc0c88.png">
.

**Comment by pbowen-oc** [comment]
@MartijnR - The other loading image you pointed out is from a separate integration we are testing.  I'm not sure about the rest of the scripts and styles you noticed.

**Comment by MartijnR** [comment]
Thanks. It may just be one script that dynamically loads all the other scripts and stylesheets.
